import 'dart:io';

import 'package:_fe_analyzer_shared/src/type_inference/nullability_suffix.dart';
import 'package:analyzer/dart/analysis/features.dart';
import 'package:analyzer/dart/analysis/session.dart';
import 'package:analyzer/dart/element/element2.dart';
import 'package:analyzer/src/dart/element/element.dart';
import 'package:analyzer/src/generated/utilities_dart.dart';
import 'package:analyzer/src/utilities/extensions/string.dart';
import 'package:analyzer/src/dart/analysis/session.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/element/nullability_suffix.dart';
import 'package:generator/gen.dart';
import 'package:path/path.dart' as path;
import 'package:analyzer/dart/analysis/analysis_context_collection.dart';
import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/element/element.dart';
import 'package:analyzer/dart/element/type.dart';

import 'diagnostics.dart';
import 'emit/emit_context.dart';
import 'lang_writers.dart';
import 'types.dart';
import 'context_bindings.dart';

part 'emit/base/a_gen.dart';
part 'emit/base/widget_gen.dart';
part 'emit/base/obj_st_gen.dart';
part 'emit/base/immutable_gen.dart';
part 'emit/base/subclass_gen.dart';
part 'emit/base/enum_gen.dart';
part 'pre_generation.dart';
part 'gen_helpers.dart';
part 'generation.dart';
part 'params.dart';

part 'emit/c_emitter.dart';
part 'emit/dart_emitter.dart';
part 'emit/java_emitter.dart';
part 'emit/member_emitter.dart';
part 'emit/web_emitter.dart';
part 'emit/serialize/serialize_strategy.dart';
part 'emit/serialize/to_c.dart';
part 'emit/serialize/to_dart.dart';
part 'emit/serialize/to_json.dart';
part 'emit/shape/abstract_factory_host_gen.dart';
part 'emit/shape/builder_expansion_gen.dart';
part 'emit/shape/color_swatch_gen.dart';
part 'emit/shape/imperative_controller_gen.dart';
part 'emit/shape/sub_animated_state_gen.dart';
part 'emit/shape/sub_state_gen.dart';
part 'emit/shape/drag_target_gen.dart';
part 'emit/shape/tracked_sub_widget_gen.dart';
part 'emit/shape/unique_key_defaulter_gen.dart';
