import 'package:flutter/rendering.dart';
import 'package:flutter/widgets.dart' as w;
import 'package:flutter/material.dart' as m;
import 'subwidgets.dart' as s;
import 'animated_wrapper.dart' as a;

w.Widget? widget;
// w.StatefulWidget? statefulWidget;
w.TextStyle? textStyle;
w.Text? text;
w.InlineSpan? inlineSpan;
w.TextSpan? textSpan;
w.RichText? richText;
w.Center? center;
w.Column? column;
w.Row? row;
w.IconData? iconData;
w.Icon? icon;
w.BuildContext? buildContext;
w.Color? color;
w.Transform? transform;
w.Opacity? opacity;
w.Stack? stack;
w.BoxConstraints? boxConstraints;
w.Container? container;
RenderObject? renderObject;
w.RenderBox? renderBox;
StackParentData? stackParentData;
FlexParentData? flexParentData;
w.Positioned? positioned;
w.BoxDecoration? boxDecoration;
w.Radius? radius;
w.BorderRadius? borderRadius;
w.BoxShadow? boxShadow;
w.Padding? padding;
w.EdgeInsets? edgeInsets;
w.BorderSide? borderSide;
w.Border? border;
w.RoundedRectangleBorder? roundedRectangleBorder;
w.TickerProvider? tickerProvider;
w.AnimationController? animationController;
w.AnimatedBuilder? animatedBuilder;
w.Offset? offset;
w.Curve? curve;
w.Cubic? cubic;
w.ThreePointCubic? threePointCubic;
w.ElasticOutCurve? elasticOutCurve;
w.ElasticInCurve? elasticInCurve;
w.ElasticInOutCurve? elasticInOutCurve;
w.Curves? curves;
w.CurvedAnimation? curvedAnimation;
w.SizedBox? sizedBox;
w.Alignment? alignment;
w.AlignmentDirectional? alignmentDirectional;
w.MouseRegion? mouseRegion;
w.FontWeight? fontWeight;
Duration? duration;
w.Expanded? expanded;
w.SafeArea? safeArea;
w.MatrixTransition? matrixTransition;
w.RotationTransition? rotationTransition;
w.FadeTransition? fadeTransition;
w.ScaleTransition? scaleTransition;

// w.FontWeight? fontWeight; constants accessing privates

m.Durations? durations;
m.ColorScheme? colorScheme;
m.TextTheme? textTheme;
m.VisualDensity? visualDensity;
m.ThemeData? themeData;
m.MaterialAccentColor? materialAccentColor;
m.MaterialColor? materialColor;
m.Colors? colors;
m.Material? material;
m.IconButton? iconButton;
m.AppBar? appBar;
m.Scaffold? scaffold;
m.MaterialApp? materialApp;
m.FloatingActionButton? floatingActionButton;
m.Icons? icons;
m.Theme? theme;
m.ElevatedButton? elevatedButton;
m.OutlinedButton? outlinedButton;
m.TextButton? textButton;
m.NavigatorState? navigatorState;
m.Navigator? navigator;
m.AlertDialog? alertDialog;
m.InputDecoration? inputDecoration;
m.TextField? textField;
m.TextDecoration? textDecoration;
m.Divider? divider;
m.FilledButton? filledButton;
m.OutlineInputBorder? outlineInputBorder;
m.SnackBarAction? snackBarAction;
m.SnackBar? snackBar;
m.ScaffoldMessenger? scaffoldMessenger;
m.Card? card;
m.Chip? chip;
w.GestureDetector? gestureDetector;
m.ListTile? listTile;
w.Wrap? wrap;
w.SingleChildScrollView? singleChildScrollView;
m.CircularProgressIndicator? circularProgressIndicator;
m.LinearProgressIndicator? linearProgressIndicator;

s.SubState? subState;
s.SubStatefulWidget? subStatefulWidget;
s.SubStatelessWidget? subStatelessWidget;

a.AnimatedWrapper? animatedWrapper;

const showDialog = m.showDialog;

void main() {
  //print('I am an index with the widgets to generate');
}