package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class AboutDialogVariants {

  private AboutDialogVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("aboutDialog_allSet", List.of(PropExpectation.equalTo("applicationName", "hello"), PropExpectation.equalTo("applicationVersion", "hello"), PropExpectation.notNull("applicationIcon"), PropExpectation.equalTo("applicationLegalese", "hello"))),
          Map.entry("aboutDialog_boundary", List.of(PropExpectation.equalTo("applicationName", ""), PropExpectation.equalTo("applicationVersion", ""), PropExpectation.notNull("applicationIcon"), PropExpectation.equalTo("applicationLegalese", ""))),
          Map.entry("adaptive_allSet", List.of(PropExpectation.equalTo("applicationName", "hello"), PropExpectation.equalTo("applicationVersion", "hello"), PropExpectation.notNull("applicationIcon"), PropExpectation.equalTo("applicationLegalese", "hello"))),
          Map.entry("adaptive_boundary", List.of(PropExpectation.equalTo("applicationName", ""), PropExpectation.equalTo("applicationVersion", ""), PropExpectation.notNull("applicationIcon"), PropExpectation.equalTo("applicationLegalese", "")))
      );

  public static Widget aboutDialog_required() {
    return AboutDialog.aboutDialog().build();
  }

  public static Widget aboutDialog_allSet() {
    return AboutDialog.aboutDialog().applicationName("hello").applicationVersion("hello").applicationIcon(SizedBox().width(1.0).height(1.0).build()).applicationLegalese("hello").build();
  }

  public static Widget aboutDialog_boundary() {
    return AboutDialog.aboutDialog().applicationName("").applicationVersion("").applicationIcon(SizedBox().width(1.0).height(1.0).build()).applicationLegalese("").build();
  }

  public static Widget adaptive_required() {
    return AboutDialog.adaptive().build();
  }

  public static Widget adaptive_allSet() {
    return AboutDialog.adaptive().applicationName("hello").applicationVersion("hello").applicationIcon(SizedBox().width(1.0).height(1.0).build()).applicationLegalese("hello").build();
  }

  public static Widget adaptive_boundary() {
    return AboutDialog.adaptive().applicationName("").applicationVersion("").applicationIcon(SizedBox().width(1.0).height(1.0).build()).applicationLegalese("").build();
  }

}
