package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class AboutListTileVariants {

  private AboutListTileVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("aboutListTile_allSet", List.of(PropExpectation.notNull("icon"), PropExpectation.notNull("child"), PropExpectation.equalTo("applicationName", "hello"), PropExpectation.equalTo("applicationVersion", "hello"), PropExpectation.notNull("applicationIcon"), PropExpectation.equalTo("applicationLegalese", "hello"), PropExpectation.equalTo("dense", true))),
          Map.entry("aboutListTile_boundary", List.of(PropExpectation.notNull("icon"), PropExpectation.notNull("child"), PropExpectation.equalTo("applicationName", ""), PropExpectation.equalTo("applicationVersion", ""), PropExpectation.notNull("applicationIcon"), PropExpectation.equalTo("applicationLegalese", ""), PropExpectation.equalTo("dense", false)))
      );

  public static Widget aboutListTile_required() {
    return Material.material().child(AboutListTile.aboutListTile().build()).build();
  }

  public static Widget aboutListTile_allSet() {
    return Material.material().child(AboutListTile.aboutListTile().icon(SizedBox().width(1.0).height(1.0).build()).child(SizedBox().width(1.0).height(1.0).build()).applicationName("hello").applicationVersion("hello").applicationIcon(SizedBox().width(1.0).height(1.0).build()).applicationLegalese("hello").dense(true).build()).build();
  }

  public static Widget aboutListTile_boundary() {
    return Material.material().child(AboutListTile.aboutListTile().icon(SizedBox().width(1.0).height(1.0).build()).child(SizedBox().width(1.0).height(1.0).build()).applicationName("").applicationVersion("").applicationIcon(SizedBox().width(1.0).height(1.0).build()).applicationLegalese("").dense(false).build()).build();
  }

}
