package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class AbsorbPointerVariants {

  private AbsorbPointerVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("absorbPointer_allSet", List.of(PropExpectation.equalTo("absorbing", true), PropExpectation.equalTo("ignoringSemantics", true), PropExpectation.notNull("child"))),
          Map.entry("absorbPointer_boundary", List.of(PropExpectation.equalTo("absorbing", false), PropExpectation.equalTo("ignoringSemantics", false), PropExpectation.notNull("child")))
      );

  public static Widget absorbPointer_required() {
    return AbsorbPointer.absorbPointer().build();
  }

  public static Widget absorbPointer_allSet() {
    return AbsorbPointer.absorbPointer().absorbing(true).ignoringSemantics(true).child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget absorbPointer_boundary() {
    return AbsorbPointer.absorbPointer().absorbing(false).ignoringSemantics(false).child(SizedBox().width(1.0).height(1.0).build()).build();
  }

}
