package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class AppBarThemeVariants {

  private AppBarThemeVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("appBarTheme_allSet", List.of(PropExpectation.notNull("color"), PropExpectation.notNull("backgroundColor"), PropExpectation.notNull("foregroundColor"), PropExpectation.equalTo("elevation", 1.0), PropExpectation.equalTo("scrolledUnderElevation", 1.0), PropExpectation.notNull("shadowColor"), PropExpectation.notNull("surfaceTintColor"), PropExpectation.notNull("shape"), PropExpectation.equalTo("centerTitle", true), PropExpectation.equalTo("titleSpacing", 1.0), PropExpectation.equalTo("leadingWidth", 1.0), PropExpectation.equalTo("toolbarHeight", 1.0), PropExpectation.notNull("toolbarTextStyle"), PropExpectation.notNull("titleTextStyle"), PropExpectation.notNull("actionsPadding"), PropExpectation.notNull("child"))),
          Map.entry("appBarTheme_boundary", List.of(PropExpectation.notNull("color"), PropExpectation.notNull("backgroundColor"), PropExpectation.notNull("foregroundColor"), PropExpectation.equalTo("elevation", 0.0), PropExpectation.equalTo("scrolledUnderElevation", 0.0), PropExpectation.notNull("shadowColor"), PropExpectation.notNull("surfaceTintColor"), PropExpectation.notNull("shape"), PropExpectation.equalTo("centerTitle", false), PropExpectation.equalTo("titleSpacing", 0.0), PropExpectation.equalTo("leadingWidth", 0.0), PropExpectation.equalTo("toolbarHeight", 0.0), PropExpectation.notNull("toolbarTextStyle"), PropExpectation.notNull("titleTextStyle"), PropExpectation.notNull("actionsPadding"), PropExpectation.notNull("child")))
      );

  public static Widget appBarTheme_required() {
    return AppBarTheme.appBarTheme().build();
  }

  public static Widget appBarTheme_allSet() {
    return AppBarTheme.appBarTheme().color(Color(0xff0000ff).build()).backgroundColor(Color(0xff0000ff).build()).foregroundColor(Color(0xff0000ff).build()).elevation(1.0).scrolledUnderElevation(1.0).shadowColor(Color(0xff0000ff).build()).surfaceTintColor(Color(0xff0000ff).build()).shape(RoundedRectangleBorder.roundedRectangleBorder().build()).centerTitle(true).titleSpacing(1.0).leadingWidth(1.0).toolbarHeight(1.0).toolbarTextStyle(TextStyle.textStyle().build()).titleTextStyle(TextStyle.textStyle().build()).actionsPadding(EdgeInsets_all(8.0).build()).child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget appBarTheme_boundary() {
    return AppBarTheme.appBarTheme().color(Color(0xff0000ff).build()).backgroundColor(Color(0xff0000ff).build()).foregroundColor(Color(0xff0000ff).build()).elevation(0.0).scrolledUnderElevation(0.0).shadowColor(Color(0xff0000ff).build()).surfaceTintColor(Color(0xff0000ff).build()).shape(RoundedRectangleBorder.roundedRectangleBorder().build()).centerTitle(false).titleSpacing(0.0).leadingWidth(0.0).toolbarHeight(0.0).toolbarTextStyle(TextStyle.textStyle().build()).titleTextStyle(TextStyle.textStyle().build()).actionsPadding(EdgeInsets_all(8.0).build()).child(SizedBox().width(1.0).height(1.0).build()).build();
  }

}
