package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class AutomaticKeepAliveVariants {

  private AutomaticKeepAliveVariants() {}

  public static Widget automaticKeepAlive_required() {
    return AutomaticKeepAlive.automaticKeepAlive(SizedBox().width(1.0).height(1.0).build()).build();
  }

}
