package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class BackButtonIconVariants {

  private BackButtonIconVariants() {}

  public static Widget backButtonIcon_required() {
    return BackButtonIcon.backButtonIcon().build();
  }

}
