package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class CardVariants {

  private CardVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("card_allSet", List.of(PropExpectation.notNull("color"), PropExpectation.notNull("shadowColor"), PropExpectation.notNull("surfaceTintColor"), PropExpectation.equalTo("elevation", 1.0), PropExpectation.notNull("shape"), PropExpectation.equalTo("borderOnForeground", true), PropExpectation.notNull("margin"), PropExpectation.equalTo("clipBehavior", Clip.none), PropExpectation.notNull("child"), PropExpectation.equalTo("semanticContainer", true))),
          Map.entry("card_boundary", List.of(PropExpectation.notNull("color"), PropExpectation.notNull("shadowColor"), PropExpectation.notNull("surfaceTintColor"), PropExpectation.equalTo("elevation", 0.0), PropExpectation.notNull("shape"), PropExpectation.equalTo("borderOnForeground", false), PropExpectation.notNull("margin"), PropExpectation.equalTo("clipBehavior", Clip.none), PropExpectation.notNull("child"), PropExpectation.equalTo("semanticContainer", false))),
          Map.entry("filled_allSet", List.of(PropExpectation.notNull("color"), PropExpectation.notNull("shadowColor"), PropExpectation.notNull("surfaceTintColor"), PropExpectation.equalTo("elevation", 1.0), PropExpectation.notNull("shape"), PropExpectation.equalTo("borderOnForeground", true), PropExpectation.notNull("margin"), PropExpectation.equalTo("clipBehavior", Clip.none), PropExpectation.notNull("child"), PropExpectation.equalTo("semanticContainer", true))),
          Map.entry("filled_boundary", List.of(PropExpectation.notNull("color"), PropExpectation.notNull("shadowColor"), PropExpectation.notNull("surfaceTintColor"), PropExpectation.equalTo("elevation", 0.0), PropExpectation.notNull("shape"), PropExpectation.equalTo("borderOnForeground", false), PropExpectation.notNull("margin"), PropExpectation.equalTo("clipBehavior", Clip.none), PropExpectation.notNull("child"), PropExpectation.equalTo("semanticContainer", false))),
          Map.entry("outlined_allSet", List.of(PropExpectation.notNull("color"), PropExpectation.notNull("shadowColor"), PropExpectation.notNull("surfaceTintColor"), PropExpectation.equalTo("elevation", 1.0), PropExpectation.notNull("shape"), PropExpectation.equalTo("borderOnForeground", true), PropExpectation.notNull("margin"), PropExpectation.equalTo("clipBehavior", Clip.none), PropExpectation.notNull("child"), PropExpectation.equalTo("semanticContainer", true))),
          Map.entry("outlined_boundary", List.of(PropExpectation.notNull("color"), PropExpectation.notNull("shadowColor"), PropExpectation.notNull("surfaceTintColor"), PropExpectation.equalTo("elevation", 0.0), PropExpectation.notNull("shape"), PropExpectation.equalTo("borderOnForeground", false), PropExpectation.notNull("margin"), PropExpectation.equalTo("clipBehavior", Clip.none), PropExpectation.notNull("child"), PropExpectation.equalTo("semanticContainer", false)))
      );

  public static Widget card_required() {
    return Card.card().build();
  }

  public static Widget card_allSet() {
    return Card.card().color(Color(0xff0000ff).build()).shadowColor(Color(0xff0000ff).build()).surfaceTintColor(Color(0xff0000ff).build()).elevation(1.0).shape(RoundedRectangleBorder.roundedRectangleBorder().build()).borderOnForeground(true).margin(EdgeInsets_all(8.0).build()).clipBehavior(Clip.none).child(SizedBox().width(1.0).height(1.0).build()).semanticContainer(true).build();
  }

  public static Widget card_boundary() {
    return Card.card().color(Color(0xff0000ff).build()).shadowColor(Color(0xff0000ff).build()).surfaceTintColor(Color(0xff0000ff).build()).elevation(0.0).shape(RoundedRectangleBorder.roundedRectangleBorder().build()).borderOnForeground(false).margin(EdgeInsets_all(8.0).build()).clipBehavior(Clip.none).child(SizedBox().width(1.0).height(1.0).build()).semanticContainer(false).build();
  }

  public static Widget filled_required() {
    return Card.filled().build();
  }

  public static Widget filled_allSet() {
    return Card.filled().color(Color(0xff0000ff).build()).shadowColor(Color(0xff0000ff).build()).surfaceTintColor(Color(0xff0000ff).build()).elevation(1.0).shape(RoundedRectangleBorder.roundedRectangleBorder().build()).borderOnForeground(true).margin(EdgeInsets_all(8.0).build()).clipBehavior(Clip.none).child(SizedBox().width(1.0).height(1.0).build()).semanticContainer(true).build();
  }

  public static Widget filled_boundary() {
    return Card.filled().color(Color(0xff0000ff).build()).shadowColor(Color(0xff0000ff).build()).surfaceTintColor(Color(0xff0000ff).build()).elevation(0.0).shape(RoundedRectangleBorder.roundedRectangleBorder().build()).borderOnForeground(false).margin(EdgeInsets_all(8.0).build()).clipBehavior(Clip.none).child(SizedBox().width(1.0).height(1.0).build()).semanticContainer(false).build();
  }

  public static Widget outlined_required() {
    return Card.outlined().build();
  }

  public static Widget outlined_allSet() {
    return Card.outlined().color(Color(0xff0000ff).build()).shadowColor(Color(0xff0000ff).build()).surfaceTintColor(Color(0xff0000ff).build()).elevation(1.0).shape(RoundedRectangleBorder.roundedRectangleBorder().build()).borderOnForeground(true).margin(EdgeInsets_all(8.0).build()).clipBehavior(Clip.none).child(SizedBox().width(1.0).height(1.0).build()).semanticContainer(true).build();
  }

  public static Widget outlined_boundary() {
    return Card.outlined().color(Color(0xff0000ff).build()).shadowColor(Color(0xff0000ff).build()).surfaceTintColor(Color(0xff0000ff).build()).elevation(0.0).shape(RoundedRectangleBorder.roundedRectangleBorder().build()).borderOnForeground(false).margin(EdgeInsets_all(8.0).build()).clipBehavior(Clip.none).child(SizedBox().width(1.0).height(1.0).build()).semanticContainer(false).build();
  }

}
