package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class ColoredBoxVariants {

  private ColoredBoxVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("coloredBox_allSet", List.of(PropExpectation.notNull("child"))),
          Map.entry("coloredBox_boundary", List.of(PropExpectation.notNull("child")))
      );

  public static Widget coloredBox_required() {
    return ColoredBox.coloredBox(Color(0xff0000ff).build()).build();
  }

  public static Widget coloredBox_allSet() {
    return ColoredBox.coloredBox(Color(0xff0000ff).build()).child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget coloredBox_boundary() {
    return ColoredBox.coloredBox(Color(0xff0000ff).build()).child(SizedBox().width(1.0).height(1.0).build()).build();
  }

}
