package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class ConstrainedBoxVariants {

  private ConstrainedBoxVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("constrainedBox_allSet", List.of(PropExpectation.notNull("child"))),
          Map.entry("constrainedBox_boundary", List.of(PropExpectation.notNull("child")))
      );

  public static Widget constrainedBox_required() {
    return ConstrainedBox.constrainedBox(BoxConstraints.boxConstraints().build()).build();
  }

  public static Widget constrainedBox_allSet() {
    return ConstrainedBox.constrainedBox(BoxConstraints.boxConstraints().build()).child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget constrainedBox_boundary() {
    return ConstrainedBox.constrainedBox(BoxConstraints.boxConstraints().build()).child(SizedBox().width(1.0).height(1.0).build()).build();
  }

}
