package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class CupertinoSliverNavigationBarVariants {

  private CupertinoSliverNavigationBarVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("cupertinoSliverNavigationBar_allSet", List.of(PropExpectation.notNull("largeTitle"), PropExpectation.notNull("leading"), PropExpectation.equalTo("automaticallyImplyLeading", true), PropExpectation.equalTo("automaticallyImplyTitle", true), PropExpectation.equalTo("alwaysShowMiddle", true), PropExpectation.equalTo("previousPageTitle", "hello"), PropExpectation.notNull("middle"), PropExpectation.notNull("trailing"), PropExpectation.notNull("backgroundColor"), PropExpectation.equalTo("automaticBackgroundVisibility", true), PropExpectation.equalTo("enableBackgroundFilterBlur", true), PropExpectation.equalTo("brightness", Brightness.dark), PropExpectation.equalTo("transitionBetweenRoutes", true), PropExpectation.equalTo("stretch", true), PropExpectation.equalTo("bottomMode", NavigationBarBottomMode.automatic))),
          Map.entry("cupertinoSliverNavigationBar_boundary", List.of(PropExpectation.notNull("largeTitle"), PropExpectation.notNull("leading"), PropExpectation.equalTo("automaticallyImplyLeading", false), PropExpectation.equalTo("automaticallyImplyTitle", false), PropExpectation.equalTo("alwaysShowMiddle", false), PropExpectation.equalTo("previousPageTitle", ""), PropExpectation.notNull("middle"), PropExpectation.notNull("trailing"), PropExpectation.notNull("backgroundColor"), PropExpectation.equalTo("automaticBackgroundVisibility", false), PropExpectation.equalTo("enableBackgroundFilterBlur", false), PropExpectation.equalTo("brightness", Brightness.dark), PropExpectation.equalTo("transitionBetweenRoutes", false), PropExpectation.equalTo("stretch", false), PropExpectation.equalTo("bottomMode", NavigationBarBottomMode.automatic))),
          Map.entry("search_allSet", List.of(PropExpectation.notNull("largeTitle"), PropExpectation.notNull("leading"), PropExpectation.equalTo("automaticallyImplyLeading", true), PropExpectation.equalTo("automaticallyImplyTitle", true), PropExpectation.equalTo("alwaysShowMiddle", true), PropExpectation.equalTo("previousPageTitle", "hello"), PropExpectation.notNull("middle"), PropExpectation.notNull("trailing"), PropExpectation.notNull("backgroundColor"), PropExpectation.equalTo("automaticBackgroundVisibility", true), PropExpectation.equalTo("enableBackgroundFilterBlur", true), PropExpectation.equalTo("brightness", Brightness.dark), PropExpectation.equalTo("transitionBetweenRoutes", true), PropExpectation.equalTo("stretch", true), PropExpectation.equalTo("bottomMode", NavigationBarBottomMode.automatic))),
          Map.entry("search_boundary", List.of(PropExpectation.notNull("largeTitle"), PropExpectation.notNull("leading"), PropExpectation.equalTo("automaticallyImplyLeading", false), PropExpectation.equalTo("automaticallyImplyTitle", false), PropExpectation.equalTo("alwaysShowMiddle", false), PropExpectation.equalTo("previousPageTitle", ""), PropExpectation.notNull("middle"), PropExpectation.notNull("trailing"), PropExpectation.notNull("backgroundColor"), PropExpectation.equalTo("automaticBackgroundVisibility", false), PropExpectation.equalTo("enableBackgroundFilterBlur", false), PropExpectation.equalTo("brightness", Brightness.dark), PropExpectation.equalTo("transitionBetweenRoutes", false), PropExpectation.equalTo("stretch", false), PropExpectation.equalTo("bottomMode", NavigationBarBottomMode.automatic)))
      );

  public static Widget cupertinoSliverNavigationBar_required() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(CupertinoSliverNavigationBar.cupertinoSliverNavigationBar().build())).build();
  }

  public static Widget cupertinoSliverNavigationBar_allSet() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(CupertinoSliverNavigationBar.cupertinoSliverNavigationBar().largeTitle(SizedBox().width(1.0).height(1.0).build()).leading(SizedBox().width(1.0).height(1.0).build()).automaticallyImplyLeading(true).automaticallyImplyTitle(true).alwaysShowMiddle(true).previousPageTitle("hello").middle(SizedBox().width(1.0).height(1.0).build()).trailing(SizedBox().width(1.0).height(1.0).build()).backgroundColor(Color(0xff0000ff).build()).automaticBackgroundVisibility(true).enableBackgroundFilterBlur(true).brightness(Brightness.dark).transitionBetweenRoutes(true).stretch(true).bottomMode(NavigationBarBottomMode.automatic).build())).build();
  }

  public static Widget cupertinoSliverNavigationBar_boundary() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(CupertinoSliverNavigationBar.cupertinoSliverNavigationBar().largeTitle(SizedBox().width(1.0).height(1.0).build()).leading(SizedBox().width(1.0).height(1.0).build()).automaticallyImplyLeading(false).automaticallyImplyTitle(false).alwaysShowMiddle(false).previousPageTitle("").middle(SizedBox().width(1.0).height(1.0).build()).trailing(SizedBox().width(1.0).height(1.0).build()).backgroundColor(Color(0xff0000ff).build()).automaticBackgroundVisibility(false).enableBackgroundFilterBlur(false).brightness(Brightness.dark).transitionBetweenRoutes(false).stretch(false).bottomMode(NavigationBarBottomMode.automatic).build())).build();
  }

  public static Widget search_required() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(CupertinoSliverNavigationBar.search(SizedBox().width(1.0).height(1.0).build()).build())).build();
  }

  public static Widget search_allSet() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(CupertinoSliverNavigationBar.search(SizedBox().width(1.0).height(1.0).build()).largeTitle(SizedBox().width(1.0).height(1.0).build()).leading(SizedBox().width(1.0).height(1.0).build()).automaticallyImplyLeading(true).automaticallyImplyTitle(true).alwaysShowMiddle(true).previousPageTitle("hello").middle(SizedBox().width(1.0).height(1.0).build()).trailing(SizedBox().width(1.0).height(1.0).build()).backgroundColor(Color(0xff0000ff).build()).automaticBackgroundVisibility(true).enableBackgroundFilterBlur(true).brightness(Brightness.dark).transitionBetweenRoutes(true).stretch(true).bottomMode(NavigationBarBottomMode.automatic).onSearchableBottomTap((_a0) -> {}).build())).build();
  }

  public static Widget search_boundary() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(CupertinoSliverNavigationBar.search(SizedBox().width(1.0).height(1.0).build()).largeTitle(SizedBox().width(1.0).height(1.0).build()).leading(SizedBox().width(1.0).height(1.0).build()).automaticallyImplyLeading(false).automaticallyImplyTitle(false).alwaysShowMiddle(false).previousPageTitle("").middle(SizedBox().width(1.0).height(1.0).build()).trailing(SizedBox().width(1.0).height(1.0).build()).backgroundColor(Color(0xff0000ff).build()).automaticBackgroundVisibility(false).enableBackgroundFilterBlur(false).brightness(Brightness.dark).transitionBetweenRoutes(false).stretch(false).bottomMode(NavigationBarBottomMode.automatic).onSearchableBottomTap((_a0) -> {}).build())).build();
  }

  public static Widget search_callbackWired() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(CupertinoSliverNavigationBar.search(SizedBox().width(1.0).height(1.0).build()).onSearchableBottomTap((_a0) -> {}).build())).build();
  }

}
