package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class CupertinoFormSectionVariants {

  private CupertinoFormSectionVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("cupertinoFormSection_allSet", List.of(PropExpectation.notNull("header"), PropExpectation.notNull("footer"), PropExpectation.notNull("margin"), PropExpectation.notNull("backgroundColor"), PropExpectation.notNull("decoration"), PropExpectation.equalTo("clipBehavior", Clip.none))),
          Map.entry("cupertinoFormSection_boundary", List.of(PropExpectation.notNull("header"), PropExpectation.notNull("footer"), PropExpectation.notNull("margin"), PropExpectation.notNull("backgroundColor"), PropExpectation.notNull("decoration"), PropExpectation.equalTo("clipBehavior", Clip.none))),
          Map.entry("insetGrouped_allSet", List.of(PropExpectation.notNull("header"), PropExpectation.notNull("footer"), PropExpectation.notNull("margin"), PropExpectation.notNull("backgroundColor"), PropExpectation.notNull("decoration"), PropExpectation.equalTo("clipBehavior", Clip.none))),
          Map.entry("insetGrouped_boundary", List.of(PropExpectation.notNull("header"), PropExpectation.notNull("footer"), PropExpectation.notNull("margin"), PropExpectation.notNull("backgroundColor"), PropExpectation.notNull("decoration"), PropExpectation.equalTo("clipBehavior", Clip.none)))
      );

  public static Widget cupertinoFormSection_required() {
    return CupertinoFormSection.cupertinoFormSection(List.<WidgetI>of(SizedBox().width(1.0).height(1.0).build())).build();
  }

  public static Widget cupertinoFormSection_allSet() {
    return CupertinoFormSection.cupertinoFormSection(List.<WidgetI>of(SizedBox().width(1.0).height(1.0).build())).header(SizedBox().width(1.0).height(1.0).build()).footer(SizedBox().width(1.0).height(1.0).build()).margin(EdgeInsets_all(8.0).build()).backgroundColor(Color(0xff0000ff).build()).decoration(BoxDecoration.boxDecoration().build()).clipBehavior(Clip.none).build();
  }

  public static Widget cupertinoFormSection_boundary() {
    return CupertinoFormSection.cupertinoFormSection(List.<WidgetI>of(SizedBox().width(1.0).height(1.0).build())).header(SizedBox().width(1.0).height(1.0).build()).footer(SizedBox().width(1.0).height(1.0).build()).margin(EdgeInsets_all(8.0).build()).backgroundColor(Color(0xff0000ff).build()).decoration(BoxDecoration.boxDecoration().build()).clipBehavior(Clip.none).build();
  }

  public static Widget insetGrouped_required() {
    return CupertinoFormSection.insetGrouped(List.<WidgetI>of(SizedBox().width(1.0).height(1.0).build())).build();
  }

  public static Widget insetGrouped_allSet() {
    return CupertinoFormSection.insetGrouped(List.<WidgetI>of(SizedBox().width(1.0).height(1.0).build())).header(SizedBox().width(1.0).height(1.0).build()).footer(SizedBox().width(1.0).height(1.0).build()).margin(EdgeInsets_all(8.0).build()).backgroundColor(Color(0xff0000ff).build()).decoration(BoxDecoration.boxDecoration().build()).clipBehavior(Clip.none).build();
  }

  public static Widget insetGrouped_boundary() {
    return CupertinoFormSection.insetGrouped(List.<WidgetI>of(SizedBox().width(1.0).height(1.0).build())).header(SizedBox().width(1.0).height(1.0).build()).footer(SizedBox().width(1.0).height(1.0).build()).margin(EdgeInsets_all(8.0).build()).backgroundColor(Color(0xff0000ff).build()).decoration(BoxDecoration.boxDecoration().build()).clipBehavior(Clip.none).build();
  }

}
