package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class CupertinoSwitchVariants {

  private CupertinoSwitchVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("cupertinoSwitch_allSet", List.of(PropExpectation.notNull("activeColor"), PropExpectation.notNull("trackColor"), PropExpectation.notNull("activeTrackColor"), PropExpectation.notNull("inactiveTrackColor"), PropExpectation.notNull("thumbColor"), PropExpectation.notNull("inactiveThumbColor"), PropExpectation.equalTo("applyTheme", true), PropExpectation.notNull("focusColor"), PropExpectation.notNull("onLabelColor"), PropExpectation.notNull("offLabelColor"), PropExpectation.equalTo("autofocus", true), PropExpectation.equalTo("dragStartBehavior", DragStartBehavior.down))),
          Map.entry("cupertinoSwitch_boundary", List.of(PropExpectation.notNull("activeColor"), PropExpectation.notNull("trackColor"), PropExpectation.notNull("activeTrackColor"), PropExpectation.notNull("inactiveTrackColor"), PropExpectation.notNull("thumbColor"), PropExpectation.notNull("inactiveThumbColor"), PropExpectation.equalTo("applyTheme", false), PropExpectation.notNull("focusColor"), PropExpectation.notNull("onLabelColor"), PropExpectation.notNull("offLabelColor"), PropExpectation.equalTo("autofocus", false), PropExpectation.equalTo("dragStartBehavior", DragStartBehavior.down)))
      );

  public static Widget cupertinoSwitch_required() {
    return CupertinoSwitch.cupertinoSwitch(true).build();
  }

  public static Widget cupertinoSwitch_allSet() {
    return CupertinoSwitch.cupertinoSwitch(true).onChanged((_a0) -> {}).activeColor(Color(0xff0000ff).build()).trackColor(Color(0xff0000ff).build()).activeTrackColor(Color(0xff0000ff).build()).inactiveTrackColor(Color(0xff0000ff).build()).thumbColor(Color(0xff0000ff).build()).inactiveThumbColor(Color(0xff0000ff).build()).applyTheme(true).focusColor(Color(0xff0000ff).build()).onLabelColor(Color(0xff0000ff).build()).offLabelColor(Color(0xff0000ff).build()).onFocusChange((_a0) -> {}).autofocus(true).dragStartBehavior(DragStartBehavior.down).build();
  }

  public static Widget cupertinoSwitch_boundary() {
    return CupertinoSwitch.cupertinoSwitch(true).onChanged((_a0) -> {}).activeColor(Color(0xff0000ff).build()).trackColor(Color(0xff0000ff).build()).activeTrackColor(Color(0xff0000ff).build()).inactiveTrackColor(Color(0xff0000ff).build()).thumbColor(Color(0xff0000ff).build()).inactiveThumbColor(Color(0xff0000ff).build()).applyTheme(false).focusColor(Color(0xff0000ff).build()).onLabelColor(Color(0xff0000ff).build()).offLabelColor(Color(0xff0000ff).build()).onFocusChange((_a0) -> {}).autofocus(false).dragStartBehavior(DragStartBehavior.down).build();
  }

  public static Widget cupertinoSwitch_callbackWired() {
    return CupertinoSwitch.cupertinoSwitch(true).onChanged((_a0) -> {}).onFocusChange((_a0) -> {}).build();
  }

}
