package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class CupertinoPageScaffoldVariants {

  private CupertinoPageScaffoldVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("cupertinoPageScaffold_allSet", List.of(PropExpectation.notNull("backgroundColor"), PropExpectation.equalTo("resizeToAvoidBottomInset", true))),
          Map.entry("cupertinoPageScaffold_boundary", List.of(PropExpectation.notNull("backgroundColor"), PropExpectation.equalTo("resizeToAvoidBottomInset", false)))
      );

  public static Widget cupertinoPageScaffold_required() {
    return CupertinoPageScaffold.cupertinoPageScaffold().child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget cupertinoPageScaffold_allSet() {
    return CupertinoPageScaffold.cupertinoPageScaffold().child(SizedBox().width(1.0).height(1.0).build()).backgroundColor(Color(0xff0000ff).build()).resizeToAvoidBottomInset(true).build();
  }

  public static Widget cupertinoPageScaffold_boundary() {
    return CupertinoPageScaffold.cupertinoPageScaffold().child(SizedBox().width(1.0).height(1.0).build()).backgroundColor(Color(0xff0000ff).build()).resizeToAvoidBottomInset(false).build();
  }

}
