package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class CupertinoSearchTextFieldVariants {

  private CupertinoSearchTextFieldVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("cupertinoSearchTextField_allSet", List.of(PropExpectation.notNull("style"), PropExpectation.equalTo("placeholder", "hello"), PropExpectation.notNull("placeholderStyle"), PropExpectation.notNull("decoration"), PropExpectation.notNull("backgroundColor"), PropExpectation.notNull("borderRadius"), PropExpectation.notNull("padding"), PropExpectation.notNull("itemColor"), PropExpectation.equalTo("itemSize", 1.0), PropExpectation.notNull("prefixInsets"), PropExpectation.notNull("prefixIcon"), PropExpectation.notNull("suffixInsets"), PropExpectation.notNull("suffixIcon"), PropExpectation.equalTo("suffixMode", OverlayVisibilityMode.never), PropExpectation.equalTo("restorationId", "hello"), PropExpectation.equalTo("smartQuotesType", SmartQuotesType.disabled), PropExpectation.equalTo("smartDashesType", SmartDashesType.disabled), PropExpectation.equalTo("enableIMEPersonalizedLearning", true), PropExpectation.equalTo("autofocus", true), PropExpectation.equalTo("autocorrect", true), PropExpectation.equalTo("enabled", true), PropExpectation.equalTo("cursorWidth", 1.0), PropExpectation.equalTo("cursorHeight", 1.0), PropExpectation.notNull("cursorRadius"), PropExpectation.equalTo("cursorOpacityAnimates", true), PropExpectation.notNull("cursorColor"))),
          Map.entry("cupertinoSearchTextField_boundary", List.of(PropExpectation.notNull("style"), PropExpectation.equalTo("placeholder", ""), PropExpectation.notNull("placeholderStyle"), PropExpectation.notNull("decoration"), PropExpectation.notNull("backgroundColor"), PropExpectation.notNull("borderRadius"), PropExpectation.notNull("padding"), PropExpectation.notNull("itemColor"), PropExpectation.equalTo("itemSize", 0.0), PropExpectation.notNull("prefixInsets"), PropExpectation.notNull("prefixIcon"), PropExpectation.notNull("suffixInsets"), PropExpectation.notNull("suffixIcon"), PropExpectation.equalTo("suffixMode", OverlayVisibilityMode.never), PropExpectation.equalTo("restorationId", ""), PropExpectation.equalTo("smartQuotesType", SmartQuotesType.disabled), PropExpectation.equalTo("smartDashesType", SmartDashesType.disabled), PropExpectation.equalTo("enableIMEPersonalizedLearning", false), PropExpectation.equalTo("autofocus", false), PropExpectation.equalTo("autocorrect", false), PropExpectation.equalTo("enabled", false), PropExpectation.equalTo("cursorWidth", 0.0), PropExpectation.equalTo("cursorHeight", 0.0), PropExpectation.notNull("cursorRadius"), PropExpectation.equalTo("cursorOpacityAnimates", false), PropExpectation.notNull("cursorColor")))
      );

  public static Widget cupertinoSearchTextField_required() {
    return CupertinoSearchTextField.cupertinoSearchTextField().build();
  }

  public static Widget cupertinoSearchTextField_allSet() {
    return CupertinoSearchTextField.cupertinoSearchTextField().onChanged((_a0) -> {}).onSubmitted((_a0) -> {}).style(TextStyle.textStyle().build()).placeholder("hello").placeholderStyle(TextStyle.textStyle().build()).decoration(BoxDecoration.boxDecoration().build()).backgroundColor(Color(0xff0000ff).build()).borderRadius(BorderRadius_all(Radius_circular(8.0).build()).build()).padding(EdgeInsets_all(8.0).build()).itemColor(Color(0xff0000ff).build()).itemSize(1.0).prefixInsets(EdgeInsets_all(8.0).build()).prefixIcon(SizedBox().width(1.0).height(1.0).build()).suffixInsets(EdgeInsets_all(8.0).build()).suffixIcon(Icon.icon(IconData(0xe000).build()).build()).suffixMode(OverlayVisibilityMode.never).onSuffixTap(() -> {}).restorationId("hello").smartQuotesType(SmartQuotesType.disabled).smartDashesType(SmartDashesType.disabled).enableIMEPersonalizedLearning(true).autofocus(true).onTap(() -> {}).autocorrect(true).enabled(true).cursorWidth(1.0).cursorHeight(1.0).cursorRadius(Radius_circular(8.0).build()).cursorOpacityAnimates(true).cursorColor(Color(0xff0000ff).build()).build();
  }

  public static Widget cupertinoSearchTextField_boundary() {
    return CupertinoSearchTextField.cupertinoSearchTextField().onChanged((_a0) -> {}).onSubmitted((_a0) -> {}).style(TextStyle.textStyle().build()).placeholder("").placeholderStyle(TextStyle.textStyle().build()).decoration(BoxDecoration.boxDecoration().build()).backgroundColor(Color(0xff0000ff).build()).borderRadius(BorderRadius_all(Radius_circular(8.0).build()).build()).padding(EdgeInsets_all(8.0).build()).itemColor(Color(0xff0000ff).build()).itemSize(0.0).prefixInsets(EdgeInsets_all(8.0).build()).prefixIcon(SizedBox().width(1.0).height(1.0).build()).suffixInsets(EdgeInsets_all(8.0).build()).suffixIcon(Icon.icon(IconData(0xe000).build()).build()).suffixMode(OverlayVisibilityMode.never).onSuffixTap(() -> {}).restorationId("").smartQuotesType(SmartQuotesType.disabled).smartDashesType(SmartDashesType.disabled).enableIMEPersonalizedLearning(false).autofocus(false).onTap(() -> {}).autocorrect(false).enabled(false).cursorWidth(0.0).cursorHeight(0.0).cursorRadius(Radius_circular(8.0).build()).cursorOpacityAnimates(false).cursorColor(Color(0xff0000ff).build()).build();
  }

  public static Widget cupertinoSearchTextField_callbackWired() {
    return CupertinoSearchTextField.cupertinoSearchTextField().onChanged((_a0) -> {}).onSubmitted((_a0) -> {}).onSuffixTap(() -> {}).onTap(() -> {}).build();
  }

}
