package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class CustomScrollViewVariants {

  private CustomScrollViewVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("customScrollView_allSet", List.of(PropExpectation.equalTo("scrollDirection", Axis.horizontal), PropExpectation.equalTo("reverse", true), PropExpectation.equalTo("primary", true), PropExpectation.equalTo("shrinkWrap", true), PropExpectation.equalTo("anchor", 1.0), PropExpectation.equalTo("cacheExtent", 1.0), PropExpectation.equalTo("paintOrder", SliverPaintOrder.firstIsTop), PropExpectation.equalTo("semanticChildCount", 1), PropExpectation.equalTo("dragStartBehavior", DragStartBehavior.down), PropExpectation.equalTo("keyboardDismissBehavior", ScrollViewKeyboardDismissBehavior.manual), PropExpectation.equalTo("restorationId", "hello"), PropExpectation.equalTo("clipBehavior", Clip.none), PropExpectation.equalTo("hitTestBehavior", HitTestBehavior.deferToChild))),
          Map.entry("customScrollView_boundary", List.of(PropExpectation.equalTo("scrollDirection", Axis.horizontal), PropExpectation.equalTo("reverse", false), PropExpectation.equalTo("primary", false), PropExpectation.equalTo("shrinkWrap", false), PropExpectation.equalTo("anchor", 0.0), PropExpectation.equalTo("cacheExtent", 0.0), PropExpectation.equalTo("paintOrder", SliverPaintOrder.firstIsTop), PropExpectation.equalTo("semanticChildCount", 0), PropExpectation.equalTo("dragStartBehavior", DragStartBehavior.down), PropExpectation.equalTo("keyboardDismissBehavior", ScrollViewKeyboardDismissBehavior.manual), PropExpectation.equalTo("restorationId", ""), PropExpectation.equalTo("clipBehavior", Clip.none), PropExpectation.equalTo("hitTestBehavior", HitTestBehavior.deferToChild)))
      );

  public static Widget customScrollView_required() {
    return CustomScrollView.customScrollView().build();
  }

  public static Widget customScrollView_allSet() {
    return CustomScrollView.customScrollView().scrollDirection(Axis.horizontal).reverse(true).primary(true).shrinkWrap(true).anchor(1.0).cacheExtent(1.0).paintOrder(SliverPaintOrder.firstIsTop).semanticChildCount(1).dragStartBehavior(DragStartBehavior.down).keyboardDismissBehavior(ScrollViewKeyboardDismissBehavior.manual).restorationId("hello").clipBehavior(Clip.none).hitTestBehavior(HitTestBehavior.deferToChild).build();
  }

  public static Widget customScrollView_boundary() {
    return CustomScrollView.customScrollView().scrollDirection(Axis.horizontal).reverse(false).primary(false).shrinkWrap(false).anchor(0.0).cacheExtent(0.0).paintOrder(SliverPaintOrder.firstIsTop).semanticChildCount(0).dragStartBehavior(DragStartBehavior.down).keyboardDismissBehavior(ScrollViewKeyboardDismissBehavior.manual).restorationId("").clipBehavior(Clip.none).hitTestBehavior(HitTestBehavior.deferToChild).build();
  }

}
