package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class DrawerVariants {

  private DrawerVariants() {}

  public static Widget drawer_required() {
    return Material.material().child(Drawer.drawer().build()).build();
  }

  public static Widget drawer_allSet() {
    return Material.material().child(Drawer.drawer().backgroundColor(Color(0xff0000ff).build()).elevation(1.0).shadowColor(Color(0xff0000ff).build()).surfaceTintColor(Color(0xff0000ff).build()).shape(RoundedRectangleBorder.roundedRectangleBorder().build()).width(1.0).child(SizedBox().width(1.0).height(1.0).build()).semanticLabel("hello").clipBehavior(Clip.none).build()).build();
  }

  public static Widget drawer_boundary() {
    return Material.material().child(Drawer.drawer().backgroundColor(Color(0xff0000ff).build()).elevation(0.0).shadowColor(Color(0xff0000ff).build()).surfaceTintColor(Color(0xff0000ff).build()).shape(RoundedRectangleBorder.roundedRectangleBorder().build()).width(0.0).child(SizedBox().width(1.0).height(1.0).build()).semanticLabel("").clipBehavior(Clip.none).build()).build();
  }

}
