package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class ExcludeFocusTraversalVariants {

  private ExcludeFocusTraversalVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("excludeFocusTraversal_allSet", List.of(PropExpectation.equalTo("excluding", true))),
          Map.entry("excludeFocusTraversal_boundary", List.of(PropExpectation.equalTo("excluding", false)))
      );

  public static Widget excludeFocusTraversal_required() {
    return ExcludeFocusTraversal.excludeFocusTraversal().child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget excludeFocusTraversal_allSet() {
    return ExcludeFocusTraversal.excludeFocusTraversal().child(SizedBox().width(1.0).height(1.0).build()).excluding(true).build();
  }

  public static Widget excludeFocusTraversal_boundary() {
    return ExcludeFocusTraversal.excludeFocusTraversal().child(SizedBox().width(1.0).height(1.0).build()).excluding(false).build();
  }

}
