package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class ExpansionPanelListVariants {

  private ExpansionPanelListVariants() {}

  public static Widget expansionPanelList_required() {
    return SingleChildScrollView.singleChildScrollView().child(ExpansionPanelList.expansionPanelList().build()).build();
  }

  public static Widget expansionPanelList_allSet() {
    return SingleChildScrollView.singleChildScrollView().child(ExpansionPanelList.expansionPanelList().expansionCallback((_a0, _a1) -> {}).animationDuration(Duration.duration().milliseconds(200).build()).dividerColor(Color(0xff0000ff).build()).elevation(1.0).expandIconColor(Color(0xff0000ff).build()).materialGapSize(1.0).build()).build();
  }

  public static Widget expansionPanelList_boundary() {
    return SingleChildScrollView.singleChildScrollView().child(ExpansionPanelList.expansionPanelList().expansionCallback((_a0, _a1) -> {}).animationDuration(Duration.duration().build()).dividerColor(Color(0xff0000ff).build()).elevation(0.0).expandIconColor(Color(0xff0000ff).build()).materialGapSize(0.0).build()).build();
  }

  public static Widget expansionPanelList_callbackWired() {
    return SingleChildScrollView.singleChildScrollView().child(ExpansionPanelList.expansionPanelList().expansionCallback((_a0, _a1) -> {}).build()).build();
  }

  public static Widget radio_required() {
    return SingleChildScrollView.singleChildScrollView().child(ExpansionPanelList.radio().build()).build();
  }

  public static Widget radio_allSet() {
    return SingleChildScrollView.singleChildScrollView().child(ExpansionPanelList.radio().expansionCallback((_a0, _a1) -> {}).animationDuration(Duration.duration().milliseconds(200).build()).dividerColor(Color(0xff0000ff).build()).elevation(1.0).expandIconColor(Color(0xff0000ff).build()).materialGapSize(1.0).build()).build();
  }

  public static Widget radio_boundary() {
    return SingleChildScrollView.singleChildScrollView().child(ExpansionPanelList.radio().expansionCallback((_a0, _a1) -> {}).animationDuration(Duration.duration().build()).dividerColor(Color(0xff0000ff).build()).elevation(0.0).expandIconColor(Color(0xff0000ff).build()).materialGapSize(0.0).build()).build();
  }

  public static Widget radio_callbackWired() {
    return SingleChildScrollView.singleChildScrollView().child(ExpansionPanelList.radio().expansionCallback((_a0, _a1) -> {}).build()).build();
  }

}
