package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class FlexibleVariants {

  private FlexibleVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("flexible_allSet", List.of(PropExpectation.equalTo("flex", 1), PropExpectation.equalTo("fit", FlexFit.tight))),
          Map.entry("flexible_boundary", List.of(PropExpectation.equalTo("flex", 1), PropExpectation.equalTo("fit", FlexFit.tight)))
      );

  public static Widget flexible_required() {
    return Row.row().children(List.<WidgetI>of(Flexible.flexible().child(SizedBox().width(1.0).height(1.0).build()).build())).build();
  }

  public static Widget flexible_allSet() {
    return Row.row().children(List.<WidgetI>of(Flexible.flexible().child(SizedBox().width(1.0).height(1.0).build()).flex(1).fit(FlexFit.tight).build())).build();
  }

  public static Widget flexible_boundary() {
    return Row.row().children(List.<WidgetI>of(Flexible.flexible().child(SizedBox().width(1.0).height(1.0).build()).flex(1).fit(FlexFit.tight).build())).build();
  }

}
