package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class FocusScopeVariants {

  private FocusScopeVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("focusScope_allSet", List.of(PropExpectation.equalTo("autofocus", true), PropExpectation.equalTo("canRequestFocus", true), PropExpectation.equalTo("skipTraversal", true), PropExpectation.equalTo("debugLabel", "hello"), PropExpectation.equalTo("includeSemantics", true), PropExpectation.equalTo("descendantsAreFocusable", true), PropExpectation.equalTo("descendantsAreTraversable", true))),
          Map.entry("focusScope_boundary", List.of(PropExpectation.equalTo("autofocus", false), PropExpectation.equalTo("canRequestFocus", false), PropExpectation.equalTo("skipTraversal", false), PropExpectation.equalTo("debugLabel", ""), PropExpectation.equalTo("includeSemantics", false), PropExpectation.equalTo("descendantsAreFocusable", false), PropExpectation.equalTo("descendantsAreTraversable", false)))
      );

  public static Widget focusScope_required() {
    return FocusScope.focusScope(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget focusScope_allSet() {
    return FocusScope.focusScope(SizedBox().width(1.0).height(1.0).build()).autofocus(true).onFocusChange((_a0) -> {}).canRequestFocus(true).skipTraversal(true).debugLabel("hello").includeSemantics(true).descendantsAreFocusable(true).descendantsAreTraversable(true).build();
  }

  public static Widget focusScope_boundary() {
    return FocusScope.focusScope(SizedBox().width(1.0).height(1.0).build()).autofocus(false).onFocusChange((_a0) -> {}).canRequestFocus(false).skipTraversal(false).debugLabel("").includeSemantics(false).descendantsAreFocusable(false).descendantsAreTraversable(false).build();
  }

  public static Widget focusScope_callbackWired() {
    return FocusScope.focusScope(SizedBox().width(1.0).height(1.0).build()).onFocusChange((_a0) -> {}).build();
  }

}
