package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class GridTileVariants {

  private GridTileVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("gridTile_allSet", List.of(PropExpectation.notNull("header"), PropExpectation.notNull("footer"))),
          Map.entry("gridTile_boundary", List.of(PropExpectation.notNull("header"), PropExpectation.notNull("footer")))
      );

  public static Widget gridTile_required() {
    return GridTile.gridTile().child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget gridTile_allSet() {
    return GridTile.gridTile().child(SizedBox().width(1.0).height(1.0).build()).header(SizedBox().width(1.0).height(1.0).build()).footer(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget gridTile_boundary() {
    return GridTile.gridTile().child(SizedBox().width(1.0).height(1.0).build()).header(SizedBox().width(1.0).height(1.0).build()).footer(SizedBox().width(1.0).height(1.0).build()).build();
  }

}
