package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class HeroModeVariants {

  private HeroModeVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("heroMode_allSet", List.of(PropExpectation.equalTo("enabled", true))),
          Map.entry("heroMode_boundary", List.of(PropExpectation.equalTo("enabled", false)))
      );

  public static Widget heroMode_required() {
    return HeroMode.heroMode(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget heroMode_allSet() {
    return HeroMode.heroMode(SizedBox().width(1.0).height(1.0).build()).enabled(true).build();
  }

  public static Widget heroMode_boundary() {
    return HeroMode.heroMode(SizedBox().width(1.0).height(1.0).build()).enabled(false).build();
  }

}
