package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class IndexedSemanticsVariants {

  private IndexedSemanticsVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("indexedSemantics_allSet", List.of(PropExpectation.notNull("child"))),
          Map.entry("indexedSemantics_boundary", List.of(PropExpectation.notNull("child")))
      );

  public static Widget indexedSemantics_required() {
    return IndexedSemantics.indexedSemantics(1).build();
  }

  public static Widget indexedSemantics_allSet() {
    return IndexedSemantics.indexedSemantics(1).child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget indexedSemantics_boundary() {
    return IndexedSemantics.indexedSemantics(1).child(SizedBox().width(1.0).height(1.0).build()).build();
  }

}
