package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class InkVariants {

  private InkVariants() {}

  public static Widget ink_required() {
    return Material.material().child(Ink.ink().build()).build();
  }

  public static Widget ink_allSet() {
    return Material.material().child(Ink.ink().padding(EdgeInsets_all(8.0).build()).color(Color(0xff0000ff).build()).decoration(BoxDecoration.boxDecoration().build()).width(1.0).height(1.0).child(SizedBox().width(1.0).height(1.0).build()).build()).build();
  }

  public static Widget ink_boundary() {
    return Material.material().child(Ink.ink().padding(EdgeInsets_all(8.0).build()).color(Color(0xff0000ff).build()).decoration(BoxDecoration.boxDecoration().build()).width(0.0).height(0.0).child(SizedBox().width(1.0).height(1.0).build()).build()).build();
  }

}
