package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class IntrinsicHeightVariants {

  private IntrinsicHeightVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("intrinsicHeight_allSet", List.of(PropExpectation.notNull("child"))),
          Map.entry("intrinsicHeight_boundary", List.of(PropExpectation.notNull("child")))
      );

  public static Widget intrinsicHeight_required() {
    return IntrinsicHeight.intrinsicHeight().build();
  }

  public static Widget intrinsicHeight_allSet() {
    return IntrinsicHeight.intrinsicHeight().child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget intrinsicHeight_boundary() {
    return IntrinsicHeight.intrinsicHeight().child(SizedBox().width(1.0).height(1.0).build()).build();
  }

}
