package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class ListTileVariants {

  private ListTileVariants() {}

  public static Widget listTile_required() {
    return Material.material().child(ListTile.listTile().build()).build();
  }

  public static Widget listTile_allSet() {
    return Material.material().child(ListTile.listTile().leading(SizedBox().width(1.0).height(1.0).build()).title(SizedBox().width(1.0).height(1.0).build()).subtitle(SizedBox().width(1.0).height(1.0).build()).trailing(SizedBox().width(1.0).height(1.0).build()).isThreeLine(true).dense(true).shape(RoundedRectangleBorder.roundedRectangleBorder().build()).style(ListTileStyle.list).selectedColor(Color(0xff0000ff).build()).iconColor(Color(0xff0000ff).build()).textColor(Color(0xff0000ff).build()).titleTextStyle(TextStyle.textStyle().build()).subtitleTextStyle(TextStyle.textStyle().build()).leadingAndTrailingTextStyle(TextStyle.textStyle().build()).contentPadding(EdgeInsets_all(8.0).build()).enabled(true).onTap(() -> {}).onLongPress(() -> {}).onFocusChange((_a0) -> {}).selected(true).focusColor(Color(0xff0000ff).build()).hoverColor(Color(0xff0000ff).build()).splashColor(Color(0xff0000ff).build()).autofocus(true).tileColor(Color(0xff0000ff).build()).selectedTileColor(Color(0xff0000ff).build()).enableFeedback(true).horizontalTitleGap(1.0).minVerticalPadding(1.0).minLeadingWidth(1.0).minTileHeight(1.0).titleAlignment(ListTileTitleAlignment.threeLine).internalAddSemanticForOnTap(true).build()).build();
  }

  public static Widget listTile_boundary() {
    return Material.material().child(ListTile.listTile().leading(SizedBox().width(1.0).height(1.0).build()).title(SizedBox().width(1.0).height(1.0).build()).subtitle(SizedBox().width(1.0).height(1.0).build()).trailing(SizedBox().width(1.0).height(1.0).build()).isThreeLine(false).dense(false).shape(RoundedRectangleBorder.roundedRectangleBorder().build()).style(ListTileStyle.list).selectedColor(Color(0xff0000ff).build()).iconColor(Color(0xff0000ff).build()).textColor(Color(0xff0000ff).build()).titleTextStyle(TextStyle.textStyle().build()).subtitleTextStyle(TextStyle.textStyle().build()).leadingAndTrailingTextStyle(TextStyle.textStyle().build()).contentPadding(EdgeInsets_all(8.0).build()).enabled(false).onTap(() -> {}).onLongPress(() -> {}).onFocusChange((_a0) -> {}).selected(false).focusColor(Color(0xff0000ff).build()).hoverColor(Color(0xff0000ff).build()).splashColor(Color(0xff0000ff).build()).autofocus(false).tileColor(Color(0xff0000ff).build()).selectedTileColor(Color(0xff0000ff).build()).enableFeedback(false).horizontalTitleGap(0.0).minVerticalPadding(0.0).minLeadingWidth(0.0).minTileHeight(0.0).titleAlignment(ListTileTitleAlignment.threeLine).internalAddSemanticForOnTap(false).build()).build();
  }

  public static Widget listTile_callbackWired() {
    return Material.material().child(ListTile.listTile().onTap(() -> {}).onLongPress(() -> {}).onFocusChange((_a0) -> {}).build()).build();
  }

}
