package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class ListBodyVariants {

  private ListBodyVariants() {}

  public static Widget listBody_required() {
    return SingleChildScrollView.singleChildScrollView().child(ListBody.listBody().build()).build();
  }

  public static Widget listBody_allSet() {
    return SingleChildScrollView.singleChildScrollView().child(ListBody.listBody().mainAxis(Axis.horizontal).reverse(true).build()).build();
  }

  public static Widget listBody_boundary() {
    return SingleChildScrollView.singleChildScrollView().child(ListBody.listBody().mainAxis(Axis.horizontal).reverse(false).build()).build();
  }

}
