package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class MergeSemanticsVariants {

  private MergeSemanticsVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("mergeSemantics_allSet", List.of(PropExpectation.notNull("child"))),
          Map.entry("mergeSemantics_boundary", List.of(PropExpectation.notNull("child")))
      );

  public static Widget mergeSemantics_required() {
    return MergeSemantics.mergeSemantics().build();
  }

  public static Widget mergeSemantics_allSet() {
    return MergeSemantics.mergeSemantics().child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget mergeSemantics_boundary() {
    return MergeSemantics.mergeSemantics().child(SizedBox().width(1.0).height(1.0).build()).build();
  }

}
