package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class ModalBarrierVariants {

  private ModalBarrierVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("modalBarrier_allSet", List.of(PropExpectation.notNull("color"), PropExpectation.equalTo("dismissible", true), PropExpectation.equalTo("semanticsLabel", "hello"), PropExpectation.equalTo("barrierSemanticsDismissible", true), PropExpectation.equalTo("semanticsOnTapHint", "hello"))),
          Map.entry("modalBarrier_boundary", List.of(PropExpectation.notNull("color"), PropExpectation.equalTo("dismissible", false), PropExpectation.equalTo("semanticsLabel", ""), PropExpectation.equalTo("barrierSemanticsDismissible", false), PropExpectation.equalTo("semanticsOnTapHint", "")))
      );

  public static Widget modalBarrier_required() {
    return ModalBarrier.modalBarrier().build();
  }

  public static Widget modalBarrier_allSet() {
    return ModalBarrier.modalBarrier().color(Color(0xff0000ff).build()).dismissible(true).onDismiss(() -> {}).semanticsLabel("hello").barrierSemanticsDismissible(true).semanticsOnTapHint("hello").build();
  }

  public static Widget modalBarrier_boundary() {
    return ModalBarrier.modalBarrier().color(Color(0xff0000ff).build()).dismissible(false).onDismiss(() -> {}).semanticsLabel("").barrierSemanticsDismissible(false).semanticsOnTapHint("").build();
  }

  public static Widget modalBarrier_callbackWired() {
    return ModalBarrier.modalBarrier().onDismiss(() -> {}).build();
  }

}
