package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class MouseRegionVariants {

  private MouseRegionVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("mouseRegion_allSet", List.of(PropExpectation.equalTo("opaque", true), PropExpectation.equalTo("hitTestBehavior", HitTestBehavior.deferToChild), PropExpectation.notNull("child"))),
          Map.entry("mouseRegion_boundary", List.of(PropExpectation.equalTo("opaque", false), PropExpectation.equalTo("hitTestBehavior", HitTestBehavior.deferToChild), PropExpectation.notNull("child")))
      );

  public static Widget mouseRegion_required() {
    return MouseRegion.mouseRegion().build();
  }

  public static Widget mouseRegion_allSet() {
    return MouseRegion.mouseRegion().opaque(true).hitTestBehavior(HitTestBehavior.deferToChild).child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget mouseRegion_boundary() {
    return MouseRegion.mouseRegion().opaque(false).hitTestBehavior(HitTestBehavior.deferToChild).child(SizedBox().width(1.0).height(1.0).build()).build();
  }

}
