package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class NavigationDrawerVariants {

  private NavigationDrawerVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("navigationDrawer_allSet", List.of(PropExpectation.notNull("header"), PropExpectation.notNull("footer"), PropExpectation.notNull("backgroundColor"), PropExpectation.notNull("shadowColor"), PropExpectation.notNull("surfaceTintColor"), PropExpectation.equalTo("elevation", 1.0), PropExpectation.notNull("indicatorColor"), PropExpectation.notNull("indicatorShape"), PropExpectation.equalTo("selectedIndex", 1), PropExpectation.notNull("tilePadding"))),
          Map.entry("navigationDrawer_boundary", List.of(PropExpectation.notNull("header"), PropExpectation.notNull("footer"), PropExpectation.notNull("backgroundColor"), PropExpectation.notNull("shadowColor"), PropExpectation.notNull("surfaceTintColor"), PropExpectation.equalTo("elevation", 0.0), PropExpectation.notNull("indicatorColor"), PropExpectation.notNull("indicatorShape"), PropExpectation.equalTo("selectedIndex", 0), PropExpectation.notNull("tilePadding")))
      );

  public static Widget navigationDrawer_required() {
    return NavigationDrawer.navigationDrawer(List.<WidgetI>of(SizedBox().width(1.0).height(1.0).build())).build();
  }

  public static Widget navigationDrawer_allSet() {
    return NavigationDrawer.navigationDrawer(List.<WidgetI>of(SizedBox().width(1.0).height(1.0).build())).header(SizedBox().width(1.0).height(1.0).build()).footer(SizedBox().width(1.0).height(1.0).build()).backgroundColor(Color(0xff0000ff).build()).shadowColor(Color(0xff0000ff).build()).surfaceTintColor(Color(0xff0000ff).build()).elevation(1.0).indicatorColor(Color(0xff0000ff).build()).indicatorShape(RoundedRectangleBorder.roundedRectangleBorder().build()).onDestinationSelected((_a0) -> {}).selectedIndex(1).tilePadding(EdgeInsets_all(8.0).build()).build();
  }

  public static Widget navigationDrawer_boundary() {
    return NavigationDrawer.navigationDrawer(List.<WidgetI>of(SizedBox().width(1.0).height(1.0).build())).header(SizedBox().width(1.0).height(1.0).build()).footer(SizedBox().width(1.0).height(1.0).build()).backgroundColor(Color(0xff0000ff).build()).shadowColor(Color(0xff0000ff).build()).surfaceTintColor(Color(0xff0000ff).build()).elevation(0.0).indicatorColor(Color(0xff0000ff).build()).indicatorShape(RoundedRectangleBorder.roundedRectangleBorder().build()).onDestinationSelected((_a0) -> {}).selectedIndex(0).tilePadding(EdgeInsets_all(8.0).build()).build();
  }

  public static Widget navigationDrawer_callbackWired() {
    return NavigationDrawer.navigationDrawer(List.<WidgetI>of(SizedBox().width(1.0).height(1.0).build())).onDestinationSelected((_a0) -> {}).build();
  }

}
