package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class NavigationToolbarVariants {

  private NavigationToolbarVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("navigationToolbar_allSet", List.of(PropExpectation.notNull("leading"), PropExpectation.notNull("middle"), PropExpectation.notNull("trailing"), PropExpectation.equalTo("centerMiddle", true), PropExpectation.equalTo("middleSpacing", 1.0))),
          Map.entry("navigationToolbar_boundary", List.of(PropExpectation.notNull("leading"), PropExpectation.notNull("middle"), PropExpectation.notNull("trailing"), PropExpectation.equalTo("centerMiddle", false), PropExpectation.equalTo("middleSpacing", 0.0)))
      );

  public static Widget navigationToolbar_required() {
    return NavigationToolbar.navigationToolbar().build();
  }

  public static Widget navigationToolbar_allSet() {
    return NavigationToolbar.navigationToolbar().leading(SizedBox().width(1.0).height(1.0).build()).middle(SizedBox().width(1.0).height(1.0).build()).trailing(SizedBox().width(1.0).height(1.0).build()).centerMiddle(true).middleSpacing(1.0).build();
  }

  public static Widget navigationToolbar_boundary() {
    return NavigationToolbar.navigationToolbar().leading(SizedBox().width(1.0).height(1.0).build()).middle(SizedBox().width(1.0).height(1.0).build()).trailing(SizedBox().width(1.0).height(1.0).build()).centerMiddle(false).middleSpacing(0.0).build();
  }

}
