package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class PageViewVariants {

  private PageViewVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("pageView_allSet", List.of(PropExpectation.equalTo("scrollDirection", Axis.horizontal), PropExpectation.equalTo("reverse", true), PropExpectation.equalTo("pageSnapping", true), PropExpectation.equalTo("dragStartBehavior", DragStartBehavior.down), PropExpectation.equalTo("allowImplicitScrolling", true), PropExpectation.equalTo("restorationId", "hello"), PropExpectation.equalTo("clipBehavior", Clip.none), PropExpectation.equalTo("hitTestBehavior", HitTestBehavior.deferToChild), PropExpectation.equalTo("padEnds", true))),
          Map.entry("pageView_boundary", List.of(PropExpectation.equalTo("scrollDirection", Axis.horizontal), PropExpectation.equalTo("reverse", false), PropExpectation.equalTo("pageSnapping", false), PropExpectation.equalTo("dragStartBehavior", DragStartBehavior.down), PropExpectation.equalTo("allowImplicitScrolling", false), PropExpectation.equalTo("restorationId", ""), PropExpectation.equalTo("clipBehavior", Clip.none), PropExpectation.equalTo("hitTestBehavior", HitTestBehavior.deferToChild), PropExpectation.equalTo("padEnds", false)))
      );

  public static Widget pageView_required() {
    return PageView.pageView().build();
  }

  public static Widget pageView_allSet() {
    return PageView.pageView().scrollDirection(Axis.horizontal).reverse(true).pageSnapping(true).onPageChanged((_a0) -> {}).dragStartBehavior(DragStartBehavior.down).allowImplicitScrolling(true).restorationId("hello").clipBehavior(Clip.none).hitTestBehavior(HitTestBehavior.deferToChild).padEnds(true).build();
  }

  public static Widget pageView_boundary() {
    return PageView.pageView().scrollDirection(Axis.horizontal).reverse(false).pageSnapping(false).onPageChanged((_a0) -> {}).dragStartBehavior(DragStartBehavior.down).allowImplicitScrolling(false).restorationId("").clipBehavior(Clip.none).hitTestBehavior(HitTestBehavior.deferToChild).padEnds(false).build();
  }

  public static Widget pageView_callbackWired() {
    return PageView.pageView().onPageChanged((_a0) -> {}).build();
  }

}
