package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class PinnedHeaderSliverVariants {

  private PinnedHeaderSliverVariants() {}

  public static Widget pinnedHeaderSliver_required() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(PinnedHeaderSliver.pinnedHeaderSliver().child(SizedBox().width(1.0).height(1.0).build()).build())).build();
  }

}
