package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class PlaceholderVariants {

  private PlaceholderVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("placeholder_allSet", List.of(PropExpectation.notNull("color"), PropExpectation.equalTo("strokeWidth", 1.0), PropExpectation.equalTo("fallbackWidth", 1.0), PropExpectation.equalTo("fallbackHeight", 1.0), PropExpectation.notNull("child"))),
          Map.entry("placeholder_boundary", List.of(PropExpectation.notNull("color"), PropExpectation.equalTo("strokeWidth", 0.0), PropExpectation.equalTo("fallbackWidth", 0.0), PropExpectation.equalTo("fallbackHeight", 0.0), PropExpectation.notNull("child")))
      );

  public static Widget placeholder_required() {
    return Placeholder.placeholder().build();
  }

  public static Widget placeholder_allSet() {
    return Placeholder.placeholder().color(Color(0xff0000ff).build()).strokeWidth(1.0).fallbackWidth(1.0).fallbackHeight(1.0).child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget placeholder_boundary() {
    return Placeholder.placeholder().color(Color(0xff0000ff).build()).strokeWidth(0.0).fallbackWidth(0.0).fallbackHeight(0.0).child(SizedBox().width(1.0).height(1.0).build()).build();
  }

}
