package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class PopupMenuDividerVariants {

  private PopupMenuDividerVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("popupMenuDivider_allSet", List.of(PropExpectation.equalTo("height", 1.0), PropExpectation.equalTo("thickness", 1.0), PropExpectation.equalTo("indent", 1.0), PropExpectation.equalTo("endIndent", 1.0), PropExpectation.notNull("radius"), PropExpectation.notNull("color"))),
          Map.entry("popupMenuDivider_boundary", List.of(PropExpectation.equalTo("height", 0.0), PropExpectation.equalTo("thickness", 0.0), PropExpectation.equalTo("indent", 0.0), PropExpectation.equalTo("endIndent", 0.0), PropExpectation.notNull("radius"), PropExpectation.notNull("color")))
      );

  public static Widget popupMenuDivider_required() {
    return Column.column().children(List.<WidgetI>of(PopupMenuDivider.popupMenuDivider().build())).build();
  }

  public static Widget popupMenuDivider_allSet() {
    return Column.column().children(List.<WidgetI>of(PopupMenuDivider.popupMenuDivider().height(1.0).thickness(1.0).indent(1.0).endIndent(1.0).radius(BorderRadius_all(Radius_circular(8.0).build()).build()).color(Color(0xff0000ff).build()).build())).build();
  }

  public static Widget popupMenuDivider_boundary() {
    return Column.column().children(List.<WidgetI>of(PopupMenuDivider.popupMenuDivider().height(0.0).thickness(0.0).indent(0.0).endIndent(0.0).radius(BorderRadius_all(Radius_circular(8.0).build()).build()).color(Color(0xff0000ff).build()).build())).build();
  }

}
