package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class PositionedVariants {

  private PositionedVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("positioned_allSet", List.of(PropExpectation.equalTo("left", 1.0), PropExpectation.equalTo("top", 1.0), PropExpectation.equalTo("right", 1.0), PropExpectation.equalTo("bottom", 1.0), PropExpectation.equalTo("width", 1.0), PropExpectation.equalTo("height", 1.0))),
          Map.entry("positioned_boundary", List.of(PropExpectation.equalTo("left", 0.0), PropExpectation.equalTo("top", 0.0), PropExpectation.equalTo("right", 0.0), PropExpectation.equalTo("bottom", 0.0), PropExpectation.equalTo("width", 1.0), PropExpectation.equalTo("height", 1.0))),
          Map.entry("fill_allSet", List.of(PropExpectation.equalTo("left", 1.0), PropExpectation.equalTo("top", 1.0), PropExpectation.equalTo("right", 1.0), PropExpectation.equalTo("bottom", 1.0))),
          Map.entry("fill_boundary", List.of(PropExpectation.equalTo("left", 0.0), PropExpectation.equalTo("top", 0.0), PropExpectation.equalTo("right", 0.0), PropExpectation.equalTo("bottom", 0.0))),
          Map.entry("directional_allSet", List.of(PropExpectation.equalTo("start", 1.0), PropExpectation.equalTo("top", 1.0), PropExpectation.equalTo("end", 1.0), PropExpectation.equalTo("bottom", 1.0), PropExpectation.equalTo("width", 1.0), PropExpectation.equalTo("height", 1.0))),
          Map.entry("directional_boundary", List.of(PropExpectation.equalTo("start", 0.0), PropExpectation.equalTo("top", 0.0), PropExpectation.equalTo("end", 0.0), PropExpectation.equalTo("bottom", 0.0), PropExpectation.equalTo("width", 1.0), PropExpectation.equalTo("height", 1.0)))
      );

  public static Widget positioned_required() {
    return dev.equo.ewt.Stack.stack().children(List.<WidgetI>of(Positioned.positioned().child(SizedBox().width(1.0).height(1.0).build()).build())).build();
  }

  public static Widget positioned_allSet() {
    return dev.equo.ewt.Stack.stack().children(List.<WidgetI>of(Positioned.positioned().child(SizedBox().width(1.0).height(1.0).build()).left(1.0).top(1.0).right(1.0).bottom(1.0).width(1.0).height(1.0).build())).build();
  }

  public static Widget positioned_boundary() {
    return dev.equo.ewt.Stack.stack().children(List.<WidgetI>of(Positioned.positioned().child(SizedBox().width(1.0).height(1.0).build()).left(0.0).top(0.0).right(0.0).bottom(0.0).width(1.0).height(1.0).build())).build();
  }

  public static Widget fill_required() {
    return dev.equo.ewt.Stack.stack().children(List.<WidgetI>of(Positioned.fill().child(SizedBox().width(1.0).height(1.0).build()).build())).build();
  }

  public static Widget fill_allSet() {
    return dev.equo.ewt.Stack.stack().children(List.<WidgetI>of(Positioned.fill().child(SizedBox().width(1.0).height(1.0).build()).left(1.0).top(1.0).right(1.0).bottom(1.0).build())).build();
  }

  public static Widget fill_boundary() {
    return dev.equo.ewt.Stack.stack().children(List.<WidgetI>of(Positioned.fill().child(SizedBox().width(1.0).height(1.0).build()).left(0.0).top(0.0).right(0.0).bottom(0.0).build())).build();
  }

  public static Widget directional_required() {
    return dev.equo.ewt.Stack.stack().children(List.<WidgetI>of(Positioned.directional(TextDirection.rtl).child(SizedBox().width(1.0).height(1.0).build()).build())).build();
  }

  public static Widget directional_allSet() {
    return dev.equo.ewt.Stack.stack().children(List.<WidgetI>of(Positioned.directional(TextDirection.rtl).child(SizedBox().width(1.0).height(1.0).build()).start(1.0).top(1.0).end(1.0).bottom(1.0).width(1.0).height(1.0).build())).build();
  }

  public static Widget directional_boundary() {
    return dev.equo.ewt.Stack.stack().children(List.<WidgetI>of(Positioned.directional(TextDirection.rtl).child(SizedBox().width(1.0).height(1.0).build()).start(0.0).top(0.0).end(0.0).bottom(0.0).width(1.0).height(1.0).build())).build();
  }

}
