package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class RawImageVariants {

  private RawImageVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("rawImage_allSet", List.of(PropExpectation.equalTo("debugImageLabel", "hello"), PropExpectation.equalTo("width", 1.0), PropExpectation.equalTo("height", 1.0), PropExpectation.equalTo("scale", 1.0), PropExpectation.notNull("color"), PropExpectation.equalTo("colorBlendMode", BlendMode.clear), PropExpectation.equalTo("fit", BoxFit.fill), PropExpectation.notNull("alignment"), PropExpectation.equalTo("repeat", ImageRepeat.repeat), PropExpectation.equalTo("matchTextDirection", true), PropExpectation.equalTo("invertColors", true), PropExpectation.equalTo("filterQuality", FilterQuality.none), PropExpectation.equalTo("isAntiAlias", true))),
          Map.entry("rawImage_boundary", List.of(PropExpectation.equalTo("debugImageLabel", ""), PropExpectation.equalTo("width", 0.0), PropExpectation.equalTo("height", 0.0), PropExpectation.equalTo("scale", 0.0), PropExpectation.notNull("color"), PropExpectation.equalTo("colorBlendMode", BlendMode.clear), PropExpectation.equalTo("fit", BoxFit.fill), PropExpectation.notNull("alignment"), PropExpectation.equalTo("repeat", ImageRepeat.repeat), PropExpectation.equalTo("matchTextDirection", false), PropExpectation.equalTo("invertColors", false), PropExpectation.equalTo("filterQuality", FilterQuality.none), PropExpectation.equalTo("isAntiAlias", false)))
      );

  public static Widget rawImage_required() {
    return RawImage.rawImage().build();
  }

  public static Widget rawImage_allSet() {
    return RawImage.rawImage().debugImageLabel("hello").width(1.0).height(1.0).scale(1.0).color(Color(0xff0000ff).build()).colorBlendMode(BlendMode.clear).fit(BoxFit.fill).alignment(Alignment.center()).repeat(ImageRepeat.repeat).matchTextDirection(true).invertColors(true).filterQuality(FilterQuality.none).isAntiAlias(true).build();
  }

  public static Widget rawImage_boundary() {
    return RawImage.rawImage().debugImageLabel("").width(0.0).height(0.0).scale(0.0).color(Color(0xff0000ff).build()).colorBlendMode(BlendMode.clear).fit(BoxFit.fill).alignment(Alignment.center()).repeat(ImageRepeat.repeat).matchTextDirection(false).invertColors(false).filterQuality(FilterQuality.none).isAntiAlias(false).build();
  }

}
