package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class SimpleDialogOptionVariants {

  private SimpleDialogOptionVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("simpleDialogOption_allSet", List.of(PropExpectation.notNull("padding"), PropExpectation.notNull("child"))),
          Map.entry("simpleDialogOption_boundary", List.of(PropExpectation.notNull("padding"), PropExpectation.notNull("child")))
      );

  public static Widget simpleDialogOption_required() {
    return SimpleDialogOption.simpleDialogOption().build();
  }

  public static Widget simpleDialogOption_allSet() {
    return SimpleDialogOption.simpleDialogOption().onPressed(() -> {}).padding(EdgeInsets_all(8.0).build()).child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget simpleDialogOption_boundary() {
    return SimpleDialogOption.simpleDialogOption().onPressed(() -> {}).padding(EdgeInsets_all(8.0).build()).child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget simpleDialogOption_callbackWired() {
    return SimpleDialogOption.simpleDialogOption().onPressed(() -> {}).build();
  }

}
