package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class SizeChangedLayoutNotifierVariants {

  private SizeChangedLayoutNotifierVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("sizeChangedLayoutNotifier_allSet", List.of(PropExpectation.notNull("child"))),
          Map.entry("sizeChangedLayoutNotifier_boundary", List.of(PropExpectation.notNull("child")))
      );

  public static Widget sizeChangedLayoutNotifier_required() {
    return SizeChangedLayoutNotifier.sizeChangedLayoutNotifier().build();
  }

  public static Widget sizeChangedLayoutNotifier_allSet() {
    return SizeChangedLayoutNotifier.sizeChangedLayoutNotifier().child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget sizeChangedLayoutNotifier_boundary() {
    return SizeChangedLayoutNotifier.sizeChangedLayoutNotifier().child(SizedBox().width(1.0).height(1.0).build()).build();
  }

}
