package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class SizedBoxVariants {

  private SizedBoxVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("sizedBox_allSet", List.of(PropExpectation.equalTo("width", 1.0), PropExpectation.equalTo("height", 1.0), PropExpectation.notNull("child"))),
          Map.entry("sizedBox_boundary", List.of(PropExpectation.equalTo("width", 0.0), PropExpectation.equalTo("height", 0.0), PropExpectation.notNull("child"))),
          Map.entry("expand_allSet", List.of(PropExpectation.notNull("child"))),
          Map.entry("expand_boundary", List.of(PropExpectation.notNull("child"))),
          Map.entry("shrink_allSet", List.of(PropExpectation.notNull("child"))),
          Map.entry("shrink_boundary", List.of(PropExpectation.notNull("child"))),
          Map.entry("fromSize_allSet", List.of(PropExpectation.notNull("child"))),
          Map.entry("fromSize_boundary", List.of(PropExpectation.notNull("child"))),
          Map.entry("square_allSet", List.of(PropExpectation.notNull("child"), PropExpectation.equalTo("dimension", 1.0))),
          Map.entry("square_boundary", List.of(PropExpectation.notNull("child"), PropExpectation.equalTo("dimension", 0.0)))
      );

  public static Widget sizedBox_required() {
    return SizedBox.sizedBox().build();
  }

  public static Widget sizedBox_allSet() {
    return SizedBox.sizedBox().width(1.0).height(1.0).child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget sizedBox_boundary() {
    return SizedBox.sizedBox().width(0.0).height(0.0).child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget expand_required() {
    return SizedBox.expand().build();
  }

  public static Widget expand_allSet() {
    return SizedBox.expand().child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget expand_boundary() {
    return SizedBox.expand().child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget shrink_required() {
    return SizedBox.shrink().build();
  }

  public static Widget shrink_allSet() {
    return SizedBox.shrink().child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget shrink_boundary() {
    return SizedBox.shrink().child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget fromSize_required() {
    return SizedBox.fromSize().build();
  }

  public static Widget fromSize_allSet() {
    return SizedBox.fromSize().child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget fromSize_boundary() {
    return SizedBox.fromSize().child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget square_required() {
    return SizedBox.square().build();
  }

  public static Widget square_allSet() {
    return SizedBox.square().child(SizedBox().width(1.0).height(1.0).build()).dimension(1.0).build();
  }

  public static Widget square_boundary() {
    return SizedBox.square().child(SizedBox().width(1.0).height(1.0).build()).dimension(0.0).build();
  }

}
