package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class SliverFillRemainingVariants {

  private SliverFillRemainingVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("sliverFillRemaining_allSet", List.of(PropExpectation.notNull("child"), PropExpectation.equalTo("hasScrollBody", true), PropExpectation.equalTo("fillOverscroll", true))),
          Map.entry("sliverFillRemaining_boundary", List.of(PropExpectation.notNull("child"), PropExpectation.equalTo("hasScrollBody", false), PropExpectation.equalTo("fillOverscroll", false)))
      );

  public static Widget sliverFillRemaining_required() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(SliverFillRemaining.sliverFillRemaining().build())).build();
  }

  public static Widget sliverFillRemaining_allSet() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(SliverFillRemaining.sliverFillRemaining().child(SizedBox().width(1.0).height(1.0).build()).hasScrollBody(true).fillOverscroll(true).build())).build();
  }

  public static Widget sliverFillRemaining_boundary() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(SliverFillRemaining.sliverFillRemaining().child(SizedBox().width(1.0).height(1.0).build()).hasScrollBody(false).fillOverscroll(false).build())).build();
  }

}
