package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class SliverVisibilityVariants {

  private SliverVisibilityVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("sliverVisibility_allSet", List.of(PropExpectation.notNull("replacementSliver"), PropExpectation.equalTo("visible", true), PropExpectation.equalTo("maintainState", true), PropExpectation.equalTo("maintainAnimation", true), PropExpectation.equalTo("maintainSize", true), PropExpectation.equalTo("maintainSemantics", true), PropExpectation.equalTo("maintainInteractivity", true))),
          Map.entry("sliverVisibility_boundary", List.of(PropExpectation.notNull("replacementSliver"), PropExpectation.equalTo("visible", false), PropExpectation.equalTo("maintainState", false), PropExpectation.equalTo("maintainAnimation", false), PropExpectation.equalTo("maintainSize", false), PropExpectation.equalTo("maintainSemantics", false), PropExpectation.equalTo("maintainInteractivity", false))),
          Map.entry("maintain_allSet", List.of(PropExpectation.notNull("replacementSliver"), PropExpectation.equalTo("visible", true))),
          Map.entry("maintain_boundary", List.of(PropExpectation.notNull("replacementSliver"), PropExpectation.equalTo("visible", false)))
      );

  public static Widget sliverVisibility_required() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(SliverVisibility.sliverVisibility(SliverToBoxAdapter.sliverToBoxAdapter().child(SizedBox().width(1.0).height(1.0).build()).build()).build())).build();
  }

  public static Widget sliverVisibility_allSet() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(SliverVisibility.sliverVisibility(SliverToBoxAdapter.sliverToBoxAdapter().child(SizedBox().width(1.0).height(1.0).build()).build()).replacementSliver(SliverToBoxAdapter.sliverToBoxAdapter().child(SizedBox().width(1.0).height(1.0).build()).build()).visible(true).maintainState(true).maintainAnimation(true).maintainSize(true).maintainSemantics(true).maintainInteractivity(true).build())).build();
  }

  public static Widget sliverVisibility_boundary() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(SliverVisibility.sliverVisibility(SliverToBoxAdapter.sliverToBoxAdapter().child(SizedBox().width(1.0).height(1.0).build()).build()).replacementSliver(SizedBox().width(1.0).height(1.0).build()).visible(false).maintainState(false).maintainAnimation(false).maintainSize(false).maintainSemantics(false).maintainInteractivity(false).build())).build();
  }

  public static Widget maintain_required() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(SliverVisibility.maintain(SliverToBoxAdapter.sliverToBoxAdapter().child(SizedBox().width(1.0).height(1.0).build()).build()).build())).build();
  }

  public static Widget maintain_allSet() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(SliverVisibility.maintain(SliverToBoxAdapter.sliverToBoxAdapter().child(SizedBox().width(1.0).height(1.0).build()).build()).replacementSliver(SliverToBoxAdapter.sliverToBoxAdapter().child(SizedBox().width(1.0).height(1.0).build()).build()).visible(true).build())).build();
  }

  public static Widget maintain_boundary() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(SliverVisibility.maintain(SliverToBoxAdapter.sliverToBoxAdapter().child(SizedBox().width(1.0).height(1.0).build()).build()).replacementSliver(SizedBox().width(1.0).height(1.0).build()).visible(false).build())).build();
  }

}
