package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class SliverSafeAreaVariants {

  private SliverSafeAreaVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("sliverSafeArea_allSet", List.of(PropExpectation.equalTo("left", true), PropExpectation.equalTo("top", true), PropExpectation.equalTo("right", true), PropExpectation.equalTo("bottom", true), PropExpectation.notNull("minimum"))),
          Map.entry("sliverSafeArea_boundary", List.of(PropExpectation.equalTo("left", false), PropExpectation.equalTo("top", false), PropExpectation.equalTo("right", false), PropExpectation.equalTo("bottom", false), PropExpectation.notNull("minimum")))
      );

  public static Widget sliverSafeArea_required() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(SliverSafeArea.sliverSafeArea().sliver(SliverToBoxAdapter.sliverToBoxAdapter().child(SizedBox().width(1.0).height(1.0).build()).build()).build())).build();
  }

  public static Widget sliverSafeArea_allSet() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(SliverSafeArea.sliverSafeArea().sliver(SliverToBoxAdapter.sliverToBoxAdapter().child(SizedBox().width(1.0).height(1.0).build()).build()).left(true).top(true).right(true).bottom(true).minimum(EdgeInsets_all(8.0).build()).build())).build();
  }

  public static Widget sliverSafeArea_boundary() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(SliverSafeArea.sliverSafeArea().sliver(SliverToBoxAdapter.sliverToBoxAdapter().child(SizedBox().width(1.0).height(1.0).build()).build()).left(false).top(false).right(false).bottom(false).minimum(EdgeInsets_all(8.0).build()).build())).build();
  }

}
