package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class SliverConstrainedCrossAxisVariants {

  private SliverConstrainedCrossAxisVariants() {}

  public static Widget sliverConstrainedCrossAxis_required() {
    return CustomScrollView.customScrollView().slivers(List.<WidgetI>of(SliverConstrainedCrossAxis.sliverConstrainedCrossAxis(1.0, SliverToBoxAdapter.sliverToBoxAdapter().child(SizedBox().width(1.0).height(1.0).build()).build()).build())).build();
  }

}
