package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class SnackBarVariants {

  private SnackBarVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("snackBar_allSet", List.of(PropExpectation.notNull("backgroundColor"), PropExpectation.equalTo("elevation", 1.0), PropExpectation.notNull("margin"), PropExpectation.notNull("padding"), PropExpectation.equalTo("width", 1.0), PropExpectation.notNull("shape"), PropExpectation.equalTo("hitTestBehavior", HitTestBehavior.deferToChild), PropExpectation.equalTo("behavior", SnackBarBehavior.fixed), PropExpectation.equalTo("actionOverflowThreshold", 1.0), PropExpectation.equalTo("showCloseIcon", true), PropExpectation.notNull("closeIconColor"), PropExpectation.notNull("duration"), PropExpectation.equalTo("dismissDirection", DismissDirection.vertical), PropExpectation.equalTo("clipBehavior", Clip.none))),
          Map.entry("snackBar_boundary", List.of(PropExpectation.notNull("backgroundColor"), PropExpectation.equalTo("elevation", 0.0), PropExpectation.notNull("margin"), PropExpectation.notNull("padding"), PropExpectation.equalTo("width", 0.0), PropExpectation.notNull("shape"), PropExpectation.equalTo("hitTestBehavior", HitTestBehavior.deferToChild), PropExpectation.equalTo("behavior", SnackBarBehavior.fixed), PropExpectation.equalTo("actionOverflowThreshold", 0.0), PropExpectation.equalTo("showCloseIcon", false), PropExpectation.notNull("closeIconColor"), PropExpectation.notNull("duration"), PropExpectation.equalTo("dismissDirection", DismissDirection.vertical), PropExpectation.equalTo("clipBehavior", Clip.none)))
      );

  public static Widget snackBar_required() {
    return SnackBar.snackBar(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget snackBar_allSet() {
    return SnackBar.snackBar(SizedBox().width(1.0).height(1.0).build()).backgroundColor(Color(0xff0000ff).build()).elevation(1.0).margin(EdgeInsets_all(8.0).build()).padding(EdgeInsets_all(8.0).build()).width(1.0).shape(RoundedRectangleBorder.roundedRectangleBorder().build()).hitTestBehavior(HitTestBehavior.deferToChild).behavior(SnackBarBehavior.fixed).actionOverflowThreshold(1.0).showCloseIcon(true).closeIconColor(Color(0xff0000ff).build()).duration(Duration.duration().milliseconds(200).build()).onVisible(() -> {}).dismissDirection(DismissDirection.vertical).clipBehavior(Clip.none).build();
  }

  public static Widget snackBar_boundary() {
    return SnackBar.snackBar(SizedBox().width(1.0).height(1.0).build()).backgroundColor(Color(0xff0000ff).build()).elevation(0.0).margin(EdgeInsets_all(8.0).build()).padding(EdgeInsets_all(8.0).build()).width(0.0).shape(RoundedRectangleBorder.roundedRectangleBorder().build()).hitTestBehavior(HitTestBehavior.deferToChild).behavior(SnackBarBehavior.fixed).actionOverflowThreshold(0.0).showCloseIcon(false).closeIconColor(Color(0xff0000ff).build()).duration(Duration.duration().build()).onVisible(() -> {}).dismissDirection(DismissDirection.vertical).clipBehavior(Clip.none).build();
  }

  public static Widget snackBar_callbackWired() {
    return SnackBar.snackBar(SizedBox().width(1.0).height(1.0).build()).onVisible(() -> {}).build();
  }

}
