package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class SnackBarActionVariants {

  private SnackBarActionVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("snackBarAction_allSet", List.of(PropExpectation.notNull("textColor"), PropExpectation.notNull("disabledTextColor"), PropExpectation.notNull("backgroundColor"), PropExpectation.notNull("disabledBackgroundColor"))),
          Map.entry("snackBarAction_boundary", List.of(PropExpectation.notNull("textColor"), PropExpectation.notNull("disabledTextColor"), PropExpectation.notNull("backgroundColor"), PropExpectation.notNull("disabledBackgroundColor")))
      );

  public static Widget snackBarAction_required() {
    return SnackBarAction.snackBarAction().label("hello").onPressed(() -> {}).build();
  }

  public static Widget snackBarAction_allSet() {
    return SnackBarAction.snackBarAction().label("hello").onPressed(() -> {}).textColor(Color(0xff0000ff).build()).disabledTextColor(Color(0xff0000ff).build()).backgroundColor(Color(0xff0000ff).build()).disabledBackgroundColor(Color(0xff0000ff).build()).build();
  }

  public static Widget snackBarAction_boundary() {
    return SnackBarAction.snackBarAction().label("hello").onPressed(() -> {}).textColor(Color(0xff0000ff).build()).disabledTextColor(Color(0xff0000ff).build()).backgroundColor(Color(0xff0000ff).build()).disabledBackgroundColor(Color(0xff0000ff).build()).build();
  }

}
