package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class SwitchListTileVariants {

  private SwitchListTileVariants() {}

  public static Widget switchListTile_required() {
    return Material.material().child(SwitchListTile.switchListTile(true).build()).build();
  }

  public static Widget switchListTile_allSet() {
    return Material.material().child(SwitchListTile.switchListTile(true).onChanged((_a0) -> {}).activeColor(Color(0xff0000ff).build()).activeThumbColor(Color(0xff0000ff).build()).activeTrackColor(Color(0xff0000ff).build()).inactiveThumbColor(Color(0xff0000ff).build()).inactiveTrackColor(Color(0xff0000ff).build()).materialTapTargetSize(MaterialTapTargetSize.padded).dragStartBehavior(DragStartBehavior.down).splashRadius(1.0).onFocusChange((_a0) -> {}).autofocus(true).tileColor(Color(0xff0000ff).build()).title(SizedBox().width(1.0).height(1.0).build()).subtitle(SizedBox().width(1.0).height(1.0).build()).isThreeLine(true).dense(true).contentPadding(EdgeInsets_all(8.0).build()).secondary(SizedBox().width(1.0).height(1.0).build()).selected(true).controlAffinity(ListTileControlAffinity.leading).shape(RoundedRectangleBorder.roundedRectangleBorder().build()).selectedTileColor(Color(0xff0000ff).build()).enableFeedback(true).horizontalTitleGap(1.0).minVerticalPadding(1.0).minLeadingWidth(1.0).minTileHeight(1.0).hoverColor(Color(0xff0000ff).build()).internalAddSemanticForOnTap(true).build()).build();
  }

  public static Widget switchListTile_boundary() {
    return Material.material().child(SwitchListTile.switchListTile(true).onChanged((_a0) -> {}).activeColor(Color(0xff0000ff).build()).activeThumbColor(Color(0xff0000ff).build()).activeTrackColor(Color(0xff0000ff).build()).inactiveThumbColor(Color(0xff0000ff).build()).inactiveTrackColor(Color(0xff0000ff).build()).materialTapTargetSize(MaterialTapTargetSize.padded).dragStartBehavior(DragStartBehavior.down).splashRadius(0.0).onFocusChange((_a0) -> {}).autofocus(false).tileColor(Color(0xff0000ff).build()).title(SizedBox().width(1.0).height(1.0).build()).subtitle(SizedBox().width(1.0).height(1.0).build()).isThreeLine(false).dense(false).contentPadding(EdgeInsets_all(8.0).build()).secondary(SizedBox().width(1.0).height(1.0).build()).selected(false).controlAffinity(ListTileControlAffinity.leading).shape(RoundedRectangleBorder.roundedRectangleBorder().build()).selectedTileColor(Color(0xff0000ff).build()).enableFeedback(false).horizontalTitleGap(0.0).minVerticalPadding(0.0).minLeadingWidth(0.0).minTileHeight(0.0).hoverColor(Color(0xff0000ff).build()).internalAddSemanticForOnTap(false).build()).build();
  }

  public static Widget switchListTile_callbackWired() {
    return Material.material().child(SwitchListTile.switchListTile(true).onChanged((_a0) -> {}).onFocusChange((_a0) -> {}).build()).build();
  }

  public static Widget adaptive_required() {
    return Material.material().child(SwitchListTile.adaptive(true).build()).build();
  }

  public static Widget adaptive_allSet() {
    return Material.material().child(SwitchListTile.adaptive(true).onChanged((_a0) -> {}).activeColor(Color(0xff0000ff).build()).activeThumbColor(Color(0xff0000ff).build()).activeTrackColor(Color(0xff0000ff).build()).inactiveThumbColor(Color(0xff0000ff).build()).inactiveTrackColor(Color(0xff0000ff).build()).materialTapTargetSize(MaterialTapTargetSize.padded).dragStartBehavior(DragStartBehavior.down).splashRadius(1.0).onFocusChange((_a0) -> {}).autofocus(true).applyCupertinoTheme(true).tileColor(Color(0xff0000ff).build()).title(SizedBox().width(1.0).height(1.0).build()).subtitle(SizedBox().width(1.0).height(1.0).build()).isThreeLine(true).dense(true).contentPadding(EdgeInsets_all(8.0).build()).secondary(SizedBox().width(1.0).height(1.0).build()).selected(true).controlAffinity(ListTileControlAffinity.leading).shape(RoundedRectangleBorder.roundedRectangleBorder().build()).selectedTileColor(Color(0xff0000ff).build()).enableFeedback(true).horizontalTitleGap(1.0).minVerticalPadding(1.0).minLeadingWidth(1.0).minTileHeight(1.0).hoverColor(Color(0xff0000ff).build()).internalAddSemanticForOnTap(true).build()).build();
  }

  public static Widget adaptive_boundary() {
    return Material.material().child(SwitchListTile.adaptive(true).onChanged((_a0) -> {}).activeColor(Color(0xff0000ff).build()).activeThumbColor(Color(0xff0000ff).build()).activeTrackColor(Color(0xff0000ff).build()).inactiveThumbColor(Color(0xff0000ff).build()).inactiveTrackColor(Color(0xff0000ff).build()).materialTapTargetSize(MaterialTapTargetSize.padded).dragStartBehavior(DragStartBehavior.down).splashRadius(0.0).onFocusChange((_a0) -> {}).autofocus(false).applyCupertinoTheme(false).tileColor(Color(0xff0000ff).build()).title(SizedBox().width(1.0).height(1.0).build()).subtitle(SizedBox().width(1.0).height(1.0).build()).isThreeLine(false).dense(false).contentPadding(EdgeInsets_all(8.0).build()).secondary(SizedBox().width(1.0).height(1.0).build()).selected(false).controlAffinity(ListTileControlAffinity.leading).shape(RoundedRectangleBorder.roundedRectangleBorder().build()).selectedTileColor(Color(0xff0000ff).build()).enableFeedback(false).horizontalTitleGap(0.0).minVerticalPadding(0.0).minLeadingWidth(0.0).minTileHeight(0.0).hoverColor(Color(0xff0000ff).build()).internalAddSemanticForOnTap(false).build()).build();
  }

  public static Widget adaptive_callbackWired() {
    return Material.material().child(SwitchListTile.adaptive(true).onChanged((_a0) -> {}).onFocusChange((_a0) -> {}).build()).build();
  }

}
