package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class TableCellVariants {

  private TableCellVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("tableCell_allSet", List.of(PropExpectation.equalTo("verticalAlignment", TableCellVerticalAlignment.top))),
          Map.entry("tableCell_boundary", List.of(PropExpectation.equalTo("verticalAlignment", TableCellVerticalAlignment.top)))
      );

  public static Widget tableCell_required() {
    return TableCell.tableCell().child(SizedBox().width(1.0).height(1.0).build()).build();
  }

  public static Widget tableCell_allSet() {
    return TableCell.tableCell().child(SizedBox().width(1.0).height(1.0).build()).verticalAlignment(TableCellVerticalAlignment.top).build();
  }

  public static Widget tableCell_boundary() {
    return TableCell.tableCell().child(SizedBox().width(1.0).height(1.0).build()).verticalAlignment(TableCellVerticalAlignment.top).build();
  }

}
