package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class TabPageSelectorIndicatorVariants {

  private TabPageSelectorIndicatorVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("tabPageSelectorIndicator_allSet", List.of(PropExpectation.equalTo("borderStyle", BorderStyle.none))),
          Map.entry("tabPageSelectorIndicator_boundary", List.of(PropExpectation.equalTo("borderStyle", BorderStyle.none)))
      );

  public static Widget tabPageSelectorIndicator_required() {
    return TabPageSelectorIndicator.tabPageSelectorIndicator(Color(0xff0000ff).build(), Color(0xff0000ff).build(), 1.0).build();
  }

  public static Widget tabPageSelectorIndicator_allSet() {
    return TabPageSelectorIndicator.tabPageSelectorIndicator(Color(0xff0000ff).build(), Color(0xff0000ff).build(), 1.0).borderStyle(BorderStyle.none).build();
  }

  public static Widget tabPageSelectorIndicator_boundary() {
    return TabPageSelectorIndicator.tabPageSelectorIndicator(Color(0xff0000ff).build(), Color(0xff0000ff).build(), 1.0).borderStyle(BorderStyle.none).build();
  }

}
