package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class TabVariants {

  private TabVariants() {}

  public static final Map<String, List<PropExpectation>> EXPECTATIONS =
      Map.ofEntries(
          Map.entry("tab_allSet", List.of(PropExpectation.equalTo("text", "hello"), PropExpectation.notNull("icon"), PropExpectation.notNull("iconMargin"), PropExpectation.equalTo("height", 1.0), PropExpectation.notNull("child"))),
          Map.entry("tab_boundary", List.of(PropExpectation.equalTo("text", ""), PropExpectation.notNull("icon"), PropExpectation.notNull("iconMargin"), PropExpectation.equalTo("height", 0.0), PropExpectation.notNull("child")))
      );

  public static Widget tab_required() {
    return DefaultTabController.defaultTabController(1).child(Tab.tab().build()).build();
  }

  public static Widget tab_allSet() {
    return DefaultTabController.defaultTabController(1).child(Tab.tab().text("hello").icon(SizedBox().width(1.0).height(1.0).build()).iconMargin(EdgeInsets_all(8.0).build()).height(1.0).child(SizedBox().width(1.0).height(1.0).build()).build()).build();
  }

  public static Widget tab_boundary() {
    return DefaultTabController.defaultTabController(1).child(Tab.tab().text("").icon(SizedBox().width(1.0).height(1.0).build()).iconMargin(EdgeInsets_all(8.0).build()).height(0.0).child(SizedBox().width(1.0).height(1.0).build()).build()).build();
  }

}
