package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class TextFieldVariants {

  private TextFieldVariants() {}

  public static Widget textField_required() {
    return Material.material().child(TextField.textField().build()).build();
  }

  public static Widget textField_allSet() {
    return Material.material().child(TextField.textField().decoration(InputDecoration.inputDecoration().build()).textInputAction(TextInputAction.none).textCapitalization(TextCapitalization.words).style(TextStyle.textStyle().build()).textAlign(TextAlign.left).textDirection(TextDirection.rtl).readOnly(true).showCursor(true).autofocus(true).obscuringCharacter("hello").obscureText(true).autocorrect(true).smartDashesType(SmartDashesType.disabled).smartQuotesType(SmartQuotesType.disabled).enableSuggestions(true).maxLines(1).minLines(1).expands(true).maxLength(1).maxLengthEnforcement(MaxLengthEnforcement.none).onChanged((_a0) -> {}).onEditingComplete(() -> {}).onSubmitted((_a0) -> {}).enabled(true).ignorePointers(true).cursorWidth(1.0).cursorHeight(1.0).cursorRadius(Radius_circular(8.0).build()).cursorOpacityAnimates(true).cursorColor(Color(0xff0000ff).build()).cursorErrorColor(Color(0xff0000ff).build()).selectionHeightStyle(BoxHeightStyle.tight).selectionWidthStyle(BoxWidthStyle.tight).keyboardAppearance(Brightness.dark).scrollPadding(EdgeInsets_all(8.0).build()).dragStartBehavior(DragStartBehavior.down).enableInteractiveSelection(true).selectAllOnFocus(true).onTap(() -> {}).onTapAlwaysCalled(true).onTapOutside((_a0) -> {}).onTapUpOutside((_a0) -> {}).clipBehavior(Clip.none).restorationId("hello").scribbleEnabled(true).stylusHandwritingEnabled(true).enableIMEPersonalizedLearning(true).enableInlinePrediction(true).canRequestFocus(true).build()).build();
  }

  public static Widget textField_boundary() {
    return Material.material().child(TextField.textField().decoration(InputDecoration.inputDecoration().build()).textInputAction(TextInputAction.none).textCapitalization(TextCapitalization.words).style(TextStyle.textStyle().build()).textAlign(TextAlign.left).textDirection(TextDirection.rtl).readOnly(false).showCursor(false).autofocus(false).obscuringCharacter("").obscureText(false).autocorrect(false).smartDashesType(SmartDashesType.disabled).smartQuotesType(SmartQuotesType.disabled).enableSuggestions(false).maxLines(0).minLines(0).expands(false).maxLength(0).maxLengthEnforcement(MaxLengthEnforcement.none).onChanged((_a0) -> {}).onEditingComplete(() -> {}).onSubmitted((_a0) -> {}).enabled(false).ignorePointers(false).cursorWidth(0.0).cursorHeight(0.0).cursorRadius(Radius_circular(8.0).build()).cursorOpacityAnimates(false).cursorColor(Color(0xff0000ff).build()).cursorErrorColor(Color(0xff0000ff).build()).selectionHeightStyle(BoxHeightStyle.tight).selectionWidthStyle(BoxWidthStyle.tight).keyboardAppearance(Brightness.dark).scrollPadding(EdgeInsets_all(8.0).build()).dragStartBehavior(DragStartBehavior.down).enableInteractiveSelection(false).selectAllOnFocus(false).onTap(() -> {}).onTapAlwaysCalled(false).onTapOutside((_a0) -> {}).onTapUpOutside((_a0) -> {}).clipBehavior(Clip.none).restorationId("").scribbleEnabled(false).stylusHandwritingEnabled(false).enableIMEPersonalizedLearning(false).enableInlinePrediction(false).canRequestFocus(false).build()).build();
  }

  public static Widget textField_callbackWired() {
    return Material.material().child(TextField.textField().onChanged((_a0) -> {}).onEditingComplete(() -> {}).onSubmitted((_a0) -> {}).onTap(() -> {}).onTapOutside((_a0) -> {}).onTapUpOutside((_a0) -> {}).build()).build();
  }

}
