package dev.equo.ewt.support.variants;

import dev.equo.ewt.*;
import dev.equo.ewt.Stack;
import java.util.*;
import static dev.equo.ewt.EWT.*;

/** Generated by :generator:generator — do not edit by hand. */
public final class TickerModeVariants {

  private TickerModeVariants() {}

  public static Widget tickerMode_required() {
    return TickerMode.tickerMode(true, SizedBox().width(1.0).height(1.0).build()).build();
  }

}
