// Audits Flutter library coverage against lib/generation_index.dart and writes
// docs/coverage.md — a checklist of every widget in the supported libraries,
// ticked for the ones already generated.
//
// Re-run after every change to generation_index.dart:
//
//   cd generator && dart tool/coverage_audit.dart
//
// It resolves the libraries with the same analyzer the generator uses, so the
// list always reflects the Flutter version actually installed.

import 'dart:io';

import 'package:analyzer/dart/analysis/analysis_context_collection.dart';
import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/element/element.dart';
import 'package:path/path.dart' as path;

/// Libraries to audit, in the order they appear in the report.
const libraries = <String>[
  'package:flutter/widgets.dart',
  'package:flutter/material.dart',
  'package:flutter/cupertino.dart',
];

const titles = <String, List<String>>{
  'package:flutter/widgets.dart': [
    'Basic widgets',
    'package:flutter/widgets.dart — raw building blocks, no default styling',
  ],
  'package:flutter/material.dart': [
    'Material',
    'package:flutter/material.dart — Material Design components (Google)',
  ],
  'package:flutter/cupertino.dart': [
    'Cupertino',
    'package:flutter/cupertino.dart — iOS / macOS styled components (Apple)',
  ],
};

Future<void> main() async {
  final probe = path.absolute(path.join('build', 'coverage_probe.dart'));
  File(probe)
    ..createSync(recursive: true)
    ..writeAsStringSync([
      for (final l in libraries) "import '$l';",
      'void main() {}',
    ].join('\n'));

  final collection = AnalysisContextCollection(
    includedPaths: [probe],
    sdkPath: getSdkPath(),
  );
  final session = collection.contextFor(probe).currentSession;
  final unit = await session.getResolvedUnit(probe);
  if (unit is! ResolvedUnitResult) {
    stderr.writeln('Could not resolve probe file');
    exit(1);
  }

  final indexed = indexedTypes();
  final sections = <String, (List<String>, List<String>)>{};

  for (final lib in unit.libraryElement.importedLibraries) {
    final uri = lib.source.uri.toString();
    if (!libraries.contains(uri)) continue;

    final owned = <ClassElement>[];
    for (final element in lib.exportNamespace.definedNames.values) {
      if (element is! ClassElement) continue;
      if (element.isPrivate || element.isAbstract) continue;
      if (!isWidget(element)) continue;
      if (!declaredIn(element, uri)) continue;
      owned.add(element);
    }

    final covered = owned.where((c) => indexed.contains(c.name)).map((c) => c.name).toList()..sort();
    final missing = owned.where((c) => !indexed.contains(c.name)).map((c) => c.name).toList()..sort();
    sections[uri] = (covered, missing);
  }

  final out = StringBuffer();
  final flutterVersion = detectFlutterVersion();
  out.writeln('# EWT — Flutter widget coverage');
  out.writeln();
  out.writeln('Flutter $flutterVersion · generated on ${DateTime.now().toIso8601String().split('T').first}');
  out.writeln();

  out.writeln('## Summary');
  out.writeln();
  out.writeln('| Library | Supported | Total | % |');
  out.writeln('|---|---:|---:|---:|');
  var totalCovered = 0;
  var totalAll = 0;
  for (final uri in libraries) {
    final s = sections[uri];
    if (s == null) continue;
    final total = s.$1.length + s.$2.length;
    if (total == 0) continue;
    totalCovered += s.$1.length;
    totalAll += total;
    out.writeln('| ${titles[uri]![0]} | ${s.$1.length} | $total | ${s.$1.length * 100 ~/ total}% |');
  }
  out.writeln('| **Total** | **$totalCovered** | **$totalAll** | '
      '**${totalAll == 0 ? 0 : totalCovered * 100 ~/ totalAll}%** |');
  out.writeln();

  for (final uri in libraries) {
    final s = sections[uri];
    if (s == null) continue;
    final total = s.$1.length + s.$2.length;
    if (total == 0) continue;
    out.writeln('## ${titles[uri]![0]}');
    out.writeln();
    out.writeln('_${titles[uri]![1]}_');
    out.writeln();
    out.writeln('**${s.$1.length} of $total supported**');
    out.writeln();
    for (final w in s.$1) {
      out.writeln('- [x] $w');
    }
    for (final w in s.$2) {
      out.writeln('- [ ] $w');
    }
    out.writeln();
  }

  out.writeln('## Notes');
  out.writeln();
  out.writeln('- `foundation.dart` exports no widgets. What the issue calls Foundation '
      '(`Alignment`, `EdgeInsets`, `BoxDecoration`) lives in `painting.dart` and is already supported.');
  out.writeln('- Only concrete classes extending `Widget` are listed. Abstract classes and '
      'supporting types (enums, themes, controllers) are excluded.');
  out.writeln('- Generated by `generator/tool/coverage_audit.dart`. Re-run it after every change '
      'to `generation_index.dart`.');

  final target = File(path.join('..', 'docs', 'coverage.md'));
  target.createSync(recursive: true);
  target.writeAsStringSync(out.toString());

  stdout.writeln('Wrote ${path.normalize(target.absolute.path)}');
  for (final uri in libraries) {
    final s = sections[uri];
    if (s == null) continue;
    final total = s.$1.length + s.$2.length;
    if (total == 0) continue;
    stdout.writeln('  ${titles[uri]![0].padRight(18)} ${s.$1.length}/$total');
  }
  stdout.writeln('  ${'TOTAL'.padRight(18)} $totalCovered/$totalAll');
}

/// Names of the types already declared in the generation index.
Set<String> indexedTypes() {
  final src = File(path.join('lib', 'generation_index.dart')).readAsStringSync();
  final names = <String>{};
  // Matches declarations such as `w.FloatingActionButton? floatingActionButton;`
  // and skips commented-out lines.
  final re = RegExp(r'^\s*(?:\w+\.)?(\w+)\?\s+\w+;', multiLine: true);
  for (final m in re.allMatches(src)) {
    names.add(m.group(1)!);
  }
  return names;
}

bool isWidget(ClassElement element) {
  for (var t = element.supertype; t != null; t = t.element.supertype) {
    if (t.element.name == 'Widget') return true;
  }
  return false;
}

/// A class re-exported by several libraries is attributed to the one that
/// declares it (material re-exports much of widgets).
bool declaredIn(ClassElement c, String uri) {
  final src = c.library.source.uri.toString();
  return switch (uri) {
    'package:flutter/widgets.dart' => src.startsWith('package:flutter/src/widgets/'),
    'package:flutter/material.dart' => src.startsWith('package:flutter/src/material/'),
    'package:flutter/cupertino.dart' => src.startsWith('package:flutter/src/cupertino/'),
    _ => false,
  };
}

String detectFlutterVersion() {
  try {
    final r = Process.runSync('flutter', ['--version']);
    final m = RegExp(r'Flutter (\S+)').firstMatch(r.stdout.toString());
    if (m != null) return m.group(1)!;
  } catch (_) {}
  return 'desconocida';
}

String getSdkPath() {
  final executable = path.split(Platform.resolvedExecutable);
  final cache = executable.indexOf('cache');
  return path.join(path.joinAll(executable.sublist(0, cache + 1)), 'dart-sdk');
}
