// Generated by jextract

package dev.equo.ewt.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int id;
 *     DartObj icon;
 *     DartObj iconColor;
 *     DartObj iconPadding;
 *     DartObj title;
 *     DartObj titlePadding;
 *     TextStyleObjSt titleTextStyle;
 *     DartObj content;
 *     DartObj contentPadding;
 *     TextStyleObjSt contentTextStyle;
 *     DartObj actionsPadding;
 *     int actionsAlignment;
 *     int actionsOverflowAlignment;
 *     int actionsOverflowDirection;
 *     double actionsOverflowButtonSpacing;
 *     DartObj buttonPadding;
 *     DartObj backgroundColor;
 *     double elevation;
 *     DartObj shadowColor;
 *     DartObj surfaceTintColor;
 *     char *semanticLabel;
 *     EdgeInsetsObjSt insetPadding;
 *     int clipBehavior;
 *     DartObj shape;
 *     DartObj alignment;
 *     BoxConstraintsObjSt constraints;
 *     int scrollable;
 * }
 * }
 */
public class AlertDialogObjSt {

    AlertDialogObjSt() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        StarterBridge.C_INT.withName("id"),
        StarterBridge.C_INT.withName("icon"),
        StarterBridge.C_INT.withName("iconColor"),
        StarterBridge.C_INT.withName("iconPadding"),
        StarterBridge.C_INT.withName("title"),
        StarterBridge.C_INT.withName("titlePadding"),
        TextStyleObjSt.layout().withName("titleTextStyle"),
        StarterBridge.C_INT.withName("content"),
        StarterBridge.C_INT.withName("contentPadding"),
        TextStyleObjSt.layout().withName("contentTextStyle"),
        StarterBridge.C_INT.withName("actionsPadding"),
        StarterBridge.C_INT.withName("actionsAlignment"),
        StarterBridge.C_INT.withName("actionsOverflowAlignment"),
        StarterBridge.C_INT.withName("actionsOverflowDirection"),
        StarterBridge.C_DOUBLE.withName("actionsOverflowButtonSpacing"),
        StarterBridge.C_INT.withName("buttonPadding"),
        StarterBridge.C_INT.withName("backgroundColor"),
        StarterBridge.C_DOUBLE.withName("elevation"),
        StarterBridge.C_INT.withName("shadowColor"),
        StarterBridge.C_INT.withName("surfaceTintColor"),
        StarterBridge.C_POINTER.withName("semanticLabel"),
        EdgeInsetsObjSt.layout().withName("insetPadding"),
        StarterBridge.C_INT.withName("clipBehavior"),
        StarterBridge.C_INT.withName("shape"),
        StarterBridge.C_INT.withName("alignment"),
        MemoryLayout.paddingLayout(4),
        BoxConstraintsObjSt.layout().withName("constraints"),
        StarterBridge.C_INT.withName("scrollable"),
        MemoryLayout.paddingLayout(4)
    ).withName("$anon$662:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static final OfInt id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = $LAYOUT.byteOffset(groupElement("id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static int id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static void id(MemorySegment struct, int fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    private static final OfInt icon$LAYOUT = (OfInt)$LAYOUT.select(groupElement("icon"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj icon
     * }
     */
    public static final OfInt icon$layout() {
        return icon$LAYOUT;
    }

    private static final long icon$OFFSET = $LAYOUT.byteOffset(groupElement("icon"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj icon
     * }
     */
    public static final long icon$offset() {
        return icon$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj icon
     * }
     */
    public static int icon(MemorySegment struct) {
        return struct.get(icon$LAYOUT, icon$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj icon
     * }
     */
    public static void icon(MemorySegment struct, int fieldValue) {
        struct.set(icon$LAYOUT, icon$OFFSET, fieldValue);
    }

    private static final OfInt iconColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("iconColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj iconColor
     * }
     */
    public static final OfInt iconColor$layout() {
        return iconColor$LAYOUT;
    }

    private static final long iconColor$OFFSET = $LAYOUT.byteOffset(groupElement("iconColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj iconColor
     * }
     */
    public static final long iconColor$offset() {
        return iconColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj iconColor
     * }
     */
    public static int iconColor(MemorySegment struct) {
        return struct.get(iconColor$LAYOUT, iconColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj iconColor
     * }
     */
    public static void iconColor(MemorySegment struct, int fieldValue) {
        struct.set(iconColor$LAYOUT, iconColor$OFFSET, fieldValue);
    }

    private static final OfInt iconPadding$LAYOUT = (OfInt)$LAYOUT.select(groupElement("iconPadding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj iconPadding
     * }
     */
    public static final OfInt iconPadding$layout() {
        return iconPadding$LAYOUT;
    }

    private static final long iconPadding$OFFSET = $LAYOUT.byteOffset(groupElement("iconPadding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj iconPadding
     * }
     */
    public static final long iconPadding$offset() {
        return iconPadding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj iconPadding
     * }
     */
    public static int iconPadding(MemorySegment struct) {
        return struct.get(iconPadding$LAYOUT, iconPadding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj iconPadding
     * }
     */
    public static void iconPadding(MemorySegment struct, int fieldValue) {
        struct.set(iconPadding$LAYOUT, iconPadding$OFFSET, fieldValue);
    }

    private static final OfInt title$LAYOUT = (OfInt)$LAYOUT.select(groupElement("title"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj title
     * }
     */
    public static final OfInt title$layout() {
        return title$LAYOUT;
    }

    private static final long title$OFFSET = $LAYOUT.byteOffset(groupElement("title"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj title
     * }
     */
    public static final long title$offset() {
        return title$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj title
     * }
     */
    public static int title(MemorySegment struct) {
        return struct.get(title$LAYOUT, title$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj title
     * }
     */
    public static void title(MemorySegment struct, int fieldValue) {
        struct.set(title$LAYOUT, title$OFFSET, fieldValue);
    }

    private static final OfInt titlePadding$LAYOUT = (OfInt)$LAYOUT.select(groupElement("titlePadding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj titlePadding
     * }
     */
    public static final OfInt titlePadding$layout() {
        return titlePadding$LAYOUT;
    }

    private static final long titlePadding$OFFSET = $LAYOUT.byteOffset(groupElement("titlePadding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj titlePadding
     * }
     */
    public static final long titlePadding$offset() {
        return titlePadding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj titlePadding
     * }
     */
    public static int titlePadding(MemorySegment struct) {
        return struct.get(titlePadding$LAYOUT, titlePadding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj titlePadding
     * }
     */
    public static void titlePadding(MemorySegment struct, int fieldValue) {
        struct.set(titlePadding$LAYOUT, titlePadding$OFFSET, fieldValue);
    }

    private static final GroupLayout titleTextStyle$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("titleTextStyle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TextStyleObjSt titleTextStyle
     * }
     */
    public static final GroupLayout titleTextStyle$layout() {
        return titleTextStyle$LAYOUT;
    }

    private static final long titleTextStyle$OFFSET = $LAYOUT.byteOffset(groupElement("titleTextStyle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TextStyleObjSt titleTextStyle
     * }
     */
    public static final long titleTextStyle$offset() {
        return titleTextStyle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TextStyleObjSt titleTextStyle
     * }
     */
    public static MemorySegment titleTextStyle(MemorySegment struct) {
        return struct.asSlice(titleTextStyle$OFFSET, titleTextStyle$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TextStyleObjSt titleTextStyle
     * }
     */
    public static void titleTextStyle(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, titleTextStyle$OFFSET, titleTextStyle$LAYOUT.byteSize());
    }

    private static final OfInt content$LAYOUT = (OfInt)$LAYOUT.select(groupElement("content"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj content
     * }
     */
    public static final OfInt content$layout() {
        return content$LAYOUT;
    }

    private static final long content$OFFSET = $LAYOUT.byteOffset(groupElement("content"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj content
     * }
     */
    public static final long content$offset() {
        return content$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj content
     * }
     */
    public static int content(MemorySegment struct) {
        return struct.get(content$LAYOUT, content$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj content
     * }
     */
    public static void content(MemorySegment struct, int fieldValue) {
        struct.set(content$LAYOUT, content$OFFSET, fieldValue);
    }

    private static final OfInt contentPadding$LAYOUT = (OfInt)$LAYOUT.select(groupElement("contentPadding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj contentPadding
     * }
     */
    public static final OfInt contentPadding$layout() {
        return contentPadding$LAYOUT;
    }

    private static final long contentPadding$OFFSET = $LAYOUT.byteOffset(groupElement("contentPadding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj contentPadding
     * }
     */
    public static final long contentPadding$offset() {
        return contentPadding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj contentPadding
     * }
     */
    public static int contentPadding(MemorySegment struct) {
        return struct.get(contentPadding$LAYOUT, contentPadding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj contentPadding
     * }
     */
    public static void contentPadding(MemorySegment struct, int fieldValue) {
        struct.set(contentPadding$LAYOUT, contentPadding$OFFSET, fieldValue);
    }

    private static final GroupLayout contentTextStyle$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("contentTextStyle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TextStyleObjSt contentTextStyle
     * }
     */
    public static final GroupLayout contentTextStyle$layout() {
        return contentTextStyle$LAYOUT;
    }

    private static final long contentTextStyle$OFFSET = $LAYOUT.byteOffset(groupElement("contentTextStyle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TextStyleObjSt contentTextStyle
     * }
     */
    public static final long contentTextStyle$offset() {
        return contentTextStyle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TextStyleObjSt contentTextStyle
     * }
     */
    public static MemorySegment contentTextStyle(MemorySegment struct) {
        return struct.asSlice(contentTextStyle$OFFSET, contentTextStyle$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TextStyleObjSt contentTextStyle
     * }
     */
    public static void contentTextStyle(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, contentTextStyle$OFFSET, contentTextStyle$LAYOUT.byteSize());
    }

    private static final OfInt actionsPadding$LAYOUT = (OfInt)$LAYOUT.select(groupElement("actionsPadding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj actionsPadding
     * }
     */
    public static final OfInt actionsPadding$layout() {
        return actionsPadding$LAYOUT;
    }

    private static final long actionsPadding$OFFSET = $LAYOUT.byteOffset(groupElement("actionsPadding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj actionsPadding
     * }
     */
    public static final long actionsPadding$offset() {
        return actionsPadding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj actionsPadding
     * }
     */
    public static int actionsPadding(MemorySegment struct) {
        return struct.get(actionsPadding$LAYOUT, actionsPadding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj actionsPadding
     * }
     */
    public static void actionsPadding(MemorySegment struct, int fieldValue) {
        struct.set(actionsPadding$LAYOUT, actionsPadding$OFFSET, fieldValue);
    }

    private static final OfInt actionsAlignment$LAYOUT = (OfInt)$LAYOUT.select(groupElement("actionsAlignment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int actionsAlignment
     * }
     */
    public static final OfInt actionsAlignment$layout() {
        return actionsAlignment$LAYOUT;
    }

    private static final long actionsAlignment$OFFSET = $LAYOUT.byteOffset(groupElement("actionsAlignment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int actionsAlignment
     * }
     */
    public static final long actionsAlignment$offset() {
        return actionsAlignment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int actionsAlignment
     * }
     */
    public static int actionsAlignment(MemorySegment struct) {
        return struct.get(actionsAlignment$LAYOUT, actionsAlignment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int actionsAlignment
     * }
     */
    public static void actionsAlignment(MemorySegment struct, int fieldValue) {
        struct.set(actionsAlignment$LAYOUT, actionsAlignment$OFFSET, fieldValue);
    }

    private static final OfInt actionsOverflowAlignment$LAYOUT = (OfInt)$LAYOUT.select(groupElement("actionsOverflowAlignment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int actionsOverflowAlignment
     * }
     */
    public static final OfInt actionsOverflowAlignment$layout() {
        return actionsOverflowAlignment$LAYOUT;
    }

    private static final long actionsOverflowAlignment$OFFSET = $LAYOUT.byteOffset(groupElement("actionsOverflowAlignment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int actionsOverflowAlignment
     * }
     */
    public static final long actionsOverflowAlignment$offset() {
        return actionsOverflowAlignment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int actionsOverflowAlignment
     * }
     */
    public static int actionsOverflowAlignment(MemorySegment struct) {
        return struct.get(actionsOverflowAlignment$LAYOUT, actionsOverflowAlignment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int actionsOverflowAlignment
     * }
     */
    public static void actionsOverflowAlignment(MemorySegment struct, int fieldValue) {
        struct.set(actionsOverflowAlignment$LAYOUT, actionsOverflowAlignment$OFFSET, fieldValue);
    }

    private static final OfInt actionsOverflowDirection$LAYOUT = (OfInt)$LAYOUT.select(groupElement("actionsOverflowDirection"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int actionsOverflowDirection
     * }
     */
    public static final OfInt actionsOverflowDirection$layout() {
        return actionsOverflowDirection$LAYOUT;
    }

    private static final long actionsOverflowDirection$OFFSET = $LAYOUT.byteOffset(groupElement("actionsOverflowDirection"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int actionsOverflowDirection
     * }
     */
    public static final long actionsOverflowDirection$offset() {
        return actionsOverflowDirection$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int actionsOverflowDirection
     * }
     */
    public static int actionsOverflowDirection(MemorySegment struct) {
        return struct.get(actionsOverflowDirection$LAYOUT, actionsOverflowDirection$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int actionsOverflowDirection
     * }
     */
    public static void actionsOverflowDirection(MemorySegment struct, int fieldValue) {
        struct.set(actionsOverflowDirection$LAYOUT, actionsOverflowDirection$OFFSET, fieldValue);
    }

    private static final OfDouble actionsOverflowButtonSpacing$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("actionsOverflowButtonSpacing"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double actionsOverflowButtonSpacing
     * }
     */
    public static final OfDouble actionsOverflowButtonSpacing$layout() {
        return actionsOverflowButtonSpacing$LAYOUT;
    }

    private static final long actionsOverflowButtonSpacing$OFFSET = $LAYOUT.byteOffset(groupElement("actionsOverflowButtonSpacing"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double actionsOverflowButtonSpacing
     * }
     */
    public static final long actionsOverflowButtonSpacing$offset() {
        return actionsOverflowButtonSpacing$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double actionsOverflowButtonSpacing
     * }
     */
    public static double actionsOverflowButtonSpacing(MemorySegment struct) {
        return struct.get(actionsOverflowButtonSpacing$LAYOUT, actionsOverflowButtonSpacing$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double actionsOverflowButtonSpacing
     * }
     */
    public static void actionsOverflowButtonSpacing(MemorySegment struct, double fieldValue) {
        struct.set(actionsOverflowButtonSpacing$LAYOUT, actionsOverflowButtonSpacing$OFFSET, fieldValue);
    }

    private static final OfInt buttonPadding$LAYOUT = (OfInt)$LAYOUT.select(groupElement("buttonPadding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj buttonPadding
     * }
     */
    public static final OfInt buttonPadding$layout() {
        return buttonPadding$LAYOUT;
    }

    private static final long buttonPadding$OFFSET = $LAYOUT.byteOffset(groupElement("buttonPadding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj buttonPadding
     * }
     */
    public static final long buttonPadding$offset() {
        return buttonPadding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj buttonPadding
     * }
     */
    public static int buttonPadding(MemorySegment struct) {
        return struct.get(buttonPadding$LAYOUT, buttonPadding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj buttonPadding
     * }
     */
    public static void buttonPadding(MemorySegment struct, int fieldValue) {
        struct.set(buttonPadding$LAYOUT, buttonPadding$OFFSET, fieldValue);
    }

    private static final OfInt backgroundColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("backgroundColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj backgroundColor
     * }
     */
    public static final OfInt backgroundColor$layout() {
        return backgroundColor$LAYOUT;
    }

    private static final long backgroundColor$OFFSET = $LAYOUT.byteOffset(groupElement("backgroundColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj backgroundColor
     * }
     */
    public static final long backgroundColor$offset() {
        return backgroundColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj backgroundColor
     * }
     */
    public static int backgroundColor(MemorySegment struct) {
        return struct.get(backgroundColor$LAYOUT, backgroundColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj backgroundColor
     * }
     */
    public static void backgroundColor(MemorySegment struct, int fieldValue) {
        struct.set(backgroundColor$LAYOUT, backgroundColor$OFFSET, fieldValue);
    }

    private static final OfDouble elevation$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("elevation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double elevation
     * }
     */
    public static final OfDouble elevation$layout() {
        return elevation$LAYOUT;
    }

    private static final long elevation$OFFSET = $LAYOUT.byteOffset(groupElement("elevation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double elevation
     * }
     */
    public static final long elevation$offset() {
        return elevation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double elevation
     * }
     */
    public static double elevation(MemorySegment struct) {
        return struct.get(elevation$LAYOUT, elevation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double elevation
     * }
     */
    public static void elevation(MemorySegment struct, double fieldValue) {
        struct.set(elevation$LAYOUT, elevation$OFFSET, fieldValue);
    }

    private static final OfInt shadowColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("shadowColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj shadowColor
     * }
     */
    public static final OfInt shadowColor$layout() {
        return shadowColor$LAYOUT;
    }

    private static final long shadowColor$OFFSET = $LAYOUT.byteOffset(groupElement("shadowColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj shadowColor
     * }
     */
    public static final long shadowColor$offset() {
        return shadowColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj shadowColor
     * }
     */
    public static int shadowColor(MemorySegment struct) {
        return struct.get(shadowColor$LAYOUT, shadowColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj shadowColor
     * }
     */
    public static void shadowColor(MemorySegment struct, int fieldValue) {
        struct.set(shadowColor$LAYOUT, shadowColor$OFFSET, fieldValue);
    }

    private static final OfInt surfaceTintColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("surfaceTintColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj surfaceTintColor
     * }
     */
    public static final OfInt surfaceTintColor$layout() {
        return surfaceTintColor$LAYOUT;
    }

    private static final long surfaceTintColor$OFFSET = $LAYOUT.byteOffset(groupElement("surfaceTintColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj surfaceTintColor
     * }
     */
    public static final long surfaceTintColor$offset() {
        return surfaceTintColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj surfaceTintColor
     * }
     */
    public static int surfaceTintColor(MemorySegment struct) {
        return struct.get(surfaceTintColor$LAYOUT, surfaceTintColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj surfaceTintColor
     * }
     */
    public static void surfaceTintColor(MemorySegment struct, int fieldValue) {
        struct.set(surfaceTintColor$LAYOUT, surfaceTintColor$OFFSET, fieldValue);
    }

    private static final AddressLayout semanticLabel$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("semanticLabel"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *semanticLabel
     * }
     */
    public static final AddressLayout semanticLabel$layout() {
        return semanticLabel$LAYOUT;
    }

    private static final long semanticLabel$OFFSET = $LAYOUT.byteOffset(groupElement("semanticLabel"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *semanticLabel
     * }
     */
    public static final long semanticLabel$offset() {
        return semanticLabel$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *semanticLabel
     * }
     */
    public static MemorySegment semanticLabel(MemorySegment struct) {
        return struct.get(semanticLabel$LAYOUT, semanticLabel$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *semanticLabel
     * }
     */
    public static void semanticLabel(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(semanticLabel$LAYOUT, semanticLabel$OFFSET, fieldValue);
    }

    private static final GroupLayout insetPadding$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("insetPadding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * EdgeInsetsObjSt insetPadding
     * }
     */
    public static final GroupLayout insetPadding$layout() {
        return insetPadding$LAYOUT;
    }

    private static final long insetPadding$OFFSET = $LAYOUT.byteOffset(groupElement("insetPadding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * EdgeInsetsObjSt insetPadding
     * }
     */
    public static final long insetPadding$offset() {
        return insetPadding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * EdgeInsetsObjSt insetPadding
     * }
     */
    public static MemorySegment insetPadding(MemorySegment struct) {
        return struct.asSlice(insetPadding$OFFSET, insetPadding$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * EdgeInsetsObjSt insetPadding
     * }
     */
    public static void insetPadding(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, insetPadding$OFFSET, insetPadding$LAYOUT.byteSize());
    }

    private static final OfInt clipBehavior$LAYOUT = (OfInt)$LAYOUT.select(groupElement("clipBehavior"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int clipBehavior
     * }
     */
    public static final OfInt clipBehavior$layout() {
        return clipBehavior$LAYOUT;
    }

    private static final long clipBehavior$OFFSET = $LAYOUT.byteOffset(groupElement("clipBehavior"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int clipBehavior
     * }
     */
    public static final long clipBehavior$offset() {
        return clipBehavior$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int clipBehavior
     * }
     */
    public static int clipBehavior(MemorySegment struct) {
        return struct.get(clipBehavior$LAYOUT, clipBehavior$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int clipBehavior
     * }
     */
    public static void clipBehavior(MemorySegment struct, int fieldValue) {
        struct.set(clipBehavior$LAYOUT, clipBehavior$OFFSET, fieldValue);
    }

    private static final OfInt shape$LAYOUT = (OfInt)$LAYOUT.select(groupElement("shape"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj shape
     * }
     */
    public static final OfInt shape$layout() {
        return shape$LAYOUT;
    }

    private static final long shape$OFFSET = $LAYOUT.byteOffset(groupElement("shape"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj shape
     * }
     */
    public static final long shape$offset() {
        return shape$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj shape
     * }
     */
    public static int shape(MemorySegment struct) {
        return struct.get(shape$LAYOUT, shape$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj shape
     * }
     */
    public static void shape(MemorySegment struct, int fieldValue) {
        struct.set(shape$LAYOUT, shape$OFFSET, fieldValue);
    }

    private static final OfInt alignment$LAYOUT = (OfInt)$LAYOUT.select(groupElement("alignment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj alignment
     * }
     */
    public static final OfInt alignment$layout() {
        return alignment$LAYOUT;
    }

    private static final long alignment$OFFSET = $LAYOUT.byteOffset(groupElement("alignment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj alignment
     * }
     */
    public static final long alignment$offset() {
        return alignment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj alignment
     * }
     */
    public static int alignment(MemorySegment struct) {
        return struct.get(alignment$LAYOUT, alignment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj alignment
     * }
     */
    public static void alignment(MemorySegment struct, int fieldValue) {
        struct.set(alignment$LAYOUT, alignment$OFFSET, fieldValue);
    }

    private static final GroupLayout constraints$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("constraints"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * BoxConstraintsObjSt constraints
     * }
     */
    public static final GroupLayout constraints$layout() {
        return constraints$LAYOUT;
    }

    private static final long constraints$OFFSET = $LAYOUT.byteOffset(groupElement("constraints"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * BoxConstraintsObjSt constraints
     * }
     */
    public static final long constraints$offset() {
        return constraints$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * BoxConstraintsObjSt constraints
     * }
     */
    public static MemorySegment constraints(MemorySegment struct) {
        return struct.asSlice(constraints$OFFSET, constraints$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * BoxConstraintsObjSt constraints
     * }
     */
    public static void constraints(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, constraints$OFFSET, constraints$LAYOUT.byteSize());
    }

    private static final OfInt scrollable$LAYOUT = (OfInt)$LAYOUT.select(groupElement("scrollable"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int scrollable
     * }
     */
    public static final OfInt scrollable$layout() {
        return scrollable$LAYOUT;
    }

    private static final long scrollable$OFFSET = $LAYOUT.byteOffset(groupElement("scrollable"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int scrollable
     * }
     */
    public static final long scrollable$offset() {
        return scrollable$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int scrollable
     * }
     */
    public static int scrollable(MemorySegment struct) {
        return struct.get(scrollable$LAYOUT, scrollable$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int scrollable
     * }
     */
    public static void scrollable(MemorySegment struct, int fieldValue) {
        struct.set(scrollable$LAYOUT, scrollable$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

