// Generated by jextract

package dev.equo.ewt.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int id;
 *     DartObj color;
 *     DartObj shadowColor;
 *     DartObj surfaceTintColor;
 *     double elevation;
 *     DartObj shape;
 *     int borderOnForeground;
 *     int clipBehavior;
 *     DartObj margin;
 *     int semanticContainer;
 *     DartObj child;
 * }
 * }
 */
public class CardObjSt {

    CardObjSt() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        StarterBridge.C_INT.withName("id"),
        StarterBridge.C_INT.withName("color"),
        StarterBridge.C_INT.withName("shadowColor"),
        StarterBridge.C_INT.withName("surfaceTintColor"),
        StarterBridge.C_DOUBLE.withName("elevation"),
        StarterBridge.C_INT.withName("shape"),
        StarterBridge.C_INT.withName("borderOnForeground"),
        StarterBridge.C_INT.withName("clipBehavior"),
        StarterBridge.C_INT.withName("margin"),
        StarterBridge.C_INT.withName("semanticContainer"),
        StarterBridge.C_INT.withName("child")
    ).withName("$anon$859:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static final OfInt id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = $LAYOUT.byteOffset(groupElement("id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static int id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static void id(MemorySegment struct, int fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    private static final OfInt color$LAYOUT = (OfInt)$LAYOUT.select(groupElement("color"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj color
     * }
     */
    public static final OfInt color$layout() {
        return color$LAYOUT;
    }

    private static final long color$OFFSET = $LAYOUT.byteOffset(groupElement("color"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj color
     * }
     */
    public static final long color$offset() {
        return color$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj color
     * }
     */
    public static int color(MemorySegment struct) {
        return struct.get(color$LAYOUT, color$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj color
     * }
     */
    public static void color(MemorySegment struct, int fieldValue) {
        struct.set(color$LAYOUT, color$OFFSET, fieldValue);
    }

    private static final OfInt shadowColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("shadowColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj shadowColor
     * }
     */
    public static final OfInt shadowColor$layout() {
        return shadowColor$LAYOUT;
    }

    private static final long shadowColor$OFFSET = $LAYOUT.byteOffset(groupElement("shadowColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj shadowColor
     * }
     */
    public static final long shadowColor$offset() {
        return shadowColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj shadowColor
     * }
     */
    public static int shadowColor(MemorySegment struct) {
        return struct.get(shadowColor$LAYOUT, shadowColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj shadowColor
     * }
     */
    public static void shadowColor(MemorySegment struct, int fieldValue) {
        struct.set(shadowColor$LAYOUT, shadowColor$OFFSET, fieldValue);
    }

    private static final OfInt surfaceTintColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("surfaceTintColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj surfaceTintColor
     * }
     */
    public static final OfInt surfaceTintColor$layout() {
        return surfaceTintColor$LAYOUT;
    }

    private static final long surfaceTintColor$OFFSET = $LAYOUT.byteOffset(groupElement("surfaceTintColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj surfaceTintColor
     * }
     */
    public static final long surfaceTintColor$offset() {
        return surfaceTintColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj surfaceTintColor
     * }
     */
    public static int surfaceTintColor(MemorySegment struct) {
        return struct.get(surfaceTintColor$LAYOUT, surfaceTintColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj surfaceTintColor
     * }
     */
    public static void surfaceTintColor(MemorySegment struct, int fieldValue) {
        struct.set(surfaceTintColor$LAYOUT, surfaceTintColor$OFFSET, fieldValue);
    }

    private static final OfDouble elevation$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("elevation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double elevation
     * }
     */
    public static final OfDouble elevation$layout() {
        return elevation$LAYOUT;
    }

    private static final long elevation$OFFSET = $LAYOUT.byteOffset(groupElement("elevation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double elevation
     * }
     */
    public static final long elevation$offset() {
        return elevation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double elevation
     * }
     */
    public static double elevation(MemorySegment struct) {
        return struct.get(elevation$LAYOUT, elevation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double elevation
     * }
     */
    public static void elevation(MemorySegment struct, double fieldValue) {
        struct.set(elevation$LAYOUT, elevation$OFFSET, fieldValue);
    }

    private static final OfInt shape$LAYOUT = (OfInt)$LAYOUT.select(groupElement("shape"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj shape
     * }
     */
    public static final OfInt shape$layout() {
        return shape$LAYOUT;
    }

    private static final long shape$OFFSET = $LAYOUT.byteOffset(groupElement("shape"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj shape
     * }
     */
    public static final long shape$offset() {
        return shape$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj shape
     * }
     */
    public static int shape(MemorySegment struct) {
        return struct.get(shape$LAYOUT, shape$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj shape
     * }
     */
    public static void shape(MemorySegment struct, int fieldValue) {
        struct.set(shape$LAYOUT, shape$OFFSET, fieldValue);
    }

    private static final OfInt borderOnForeground$LAYOUT = (OfInt)$LAYOUT.select(groupElement("borderOnForeground"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int borderOnForeground
     * }
     */
    public static final OfInt borderOnForeground$layout() {
        return borderOnForeground$LAYOUT;
    }

    private static final long borderOnForeground$OFFSET = $LAYOUT.byteOffset(groupElement("borderOnForeground"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int borderOnForeground
     * }
     */
    public static final long borderOnForeground$offset() {
        return borderOnForeground$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int borderOnForeground
     * }
     */
    public static int borderOnForeground(MemorySegment struct) {
        return struct.get(borderOnForeground$LAYOUT, borderOnForeground$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int borderOnForeground
     * }
     */
    public static void borderOnForeground(MemorySegment struct, int fieldValue) {
        struct.set(borderOnForeground$LAYOUT, borderOnForeground$OFFSET, fieldValue);
    }

    private static final OfInt clipBehavior$LAYOUT = (OfInt)$LAYOUT.select(groupElement("clipBehavior"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int clipBehavior
     * }
     */
    public static final OfInt clipBehavior$layout() {
        return clipBehavior$LAYOUT;
    }

    private static final long clipBehavior$OFFSET = $LAYOUT.byteOffset(groupElement("clipBehavior"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int clipBehavior
     * }
     */
    public static final long clipBehavior$offset() {
        return clipBehavior$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int clipBehavior
     * }
     */
    public static int clipBehavior(MemorySegment struct) {
        return struct.get(clipBehavior$LAYOUT, clipBehavior$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int clipBehavior
     * }
     */
    public static void clipBehavior(MemorySegment struct, int fieldValue) {
        struct.set(clipBehavior$LAYOUT, clipBehavior$OFFSET, fieldValue);
    }

    private static final OfInt margin$LAYOUT = (OfInt)$LAYOUT.select(groupElement("margin"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj margin
     * }
     */
    public static final OfInt margin$layout() {
        return margin$LAYOUT;
    }

    private static final long margin$OFFSET = $LAYOUT.byteOffset(groupElement("margin"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj margin
     * }
     */
    public static final long margin$offset() {
        return margin$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj margin
     * }
     */
    public static int margin(MemorySegment struct) {
        return struct.get(margin$LAYOUT, margin$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj margin
     * }
     */
    public static void margin(MemorySegment struct, int fieldValue) {
        struct.set(margin$LAYOUT, margin$OFFSET, fieldValue);
    }

    private static final OfInt semanticContainer$LAYOUT = (OfInt)$LAYOUT.select(groupElement("semanticContainer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int semanticContainer
     * }
     */
    public static final OfInt semanticContainer$layout() {
        return semanticContainer$LAYOUT;
    }

    private static final long semanticContainer$OFFSET = $LAYOUT.byteOffset(groupElement("semanticContainer"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int semanticContainer
     * }
     */
    public static final long semanticContainer$offset() {
        return semanticContainer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int semanticContainer
     * }
     */
    public static int semanticContainer(MemorySegment struct) {
        return struct.get(semanticContainer$LAYOUT, semanticContainer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int semanticContainer
     * }
     */
    public static void semanticContainer(MemorySegment struct, int fieldValue) {
        struct.set(semanticContainer$LAYOUT, semanticContainer$OFFSET, fieldValue);
    }

    private static final OfInt child$LAYOUT = (OfInt)$LAYOUT.select(groupElement("child"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static final OfInt child$layout() {
        return child$LAYOUT;
    }

    private static final long child$OFFSET = $LAYOUT.byteOffset(groupElement("child"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static final long child$offset() {
        return child$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static int child(MemorySegment struct) {
        return struct.get(child$LAYOUT, child$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static void child(MemorySegment struct, int fieldValue) {
        struct.set(child$LAYOUT, child$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

