// Generated by jextract

package dev.equo.ewt.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int id;
 *     int length;
 *     int initialIndex;
 *     DartObj animationDuration;
 *     DartObj child;
 * }
 * }
 */
public class DefaultTabControllerObjSt {

    DefaultTabControllerObjSt() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        StarterBridge.C_INT.withName("id"),
        StarterBridge.C_INT.withName("length"),
        StarterBridge.C_INT.withName("initialIndex"),
        StarterBridge.C_INT.withName("animationDuration"),
        StarterBridge.C_INT.withName("child")
    ).withName("$anon$1289:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static final OfInt id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = $LAYOUT.byteOffset(groupElement("id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static int id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static void id(MemorySegment struct, int fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    private static final OfInt length$LAYOUT = (OfInt)$LAYOUT.select(groupElement("length"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int length
     * }
     */
    public static final OfInt length$layout() {
        return length$LAYOUT;
    }

    private static final long length$OFFSET = $LAYOUT.byteOffset(groupElement("length"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int length
     * }
     */
    public static final long length$offset() {
        return length$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int length
     * }
     */
    public static int length(MemorySegment struct) {
        return struct.get(length$LAYOUT, length$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int length
     * }
     */
    public static void length(MemorySegment struct, int fieldValue) {
        struct.set(length$LAYOUT, length$OFFSET, fieldValue);
    }

    private static final OfInt initialIndex$LAYOUT = (OfInt)$LAYOUT.select(groupElement("initialIndex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int initialIndex
     * }
     */
    public static final OfInt initialIndex$layout() {
        return initialIndex$LAYOUT;
    }

    private static final long initialIndex$OFFSET = $LAYOUT.byteOffset(groupElement("initialIndex"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int initialIndex
     * }
     */
    public static final long initialIndex$offset() {
        return initialIndex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int initialIndex
     * }
     */
    public static int initialIndex(MemorySegment struct) {
        return struct.get(initialIndex$LAYOUT, initialIndex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int initialIndex
     * }
     */
    public static void initialIndex(MemorySegment struct, int fieldValue) {
        struct.set(initialIndex$LAYOUT, initialIndex$OFFSET, fieldValue);
    }

    private static final OfInt animationDuration$LAYOUT = (OfInt)$LAYOUT.select(groupElement("animationDuration"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj animationDuration
     * }
     */
    public static final OfInt animationDuration$layout() {
        return animationDuration$LAYOUT;
    }

    private static final long animationDuration$OFFSET = $LAYOUT.byteOffset(groupElement("animationDuration"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj animationDuration
     * }
     */
    public static final long animationDuration$offset() {
        return animationDuration$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj animationDuration
     * }
     */
    public static int animationDuration(MemorySegment struct) {
        return struct.get(animationDuration$LAYOUT, animationDuration$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj animationDuration
     * }
     */
    public static void animationDuration(MemorySegment struct, int fieldValue) {
        struct.set(animationDuration$LAYOUT, animationDuration$OFFSET, fieldValue);
    }

    private static final OfInt child$LAYOUT = (OfInt)$LAYOUT.select(groupElement("child"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static final OfInt child$layout() {
        return child$LAYOUT;
    }

    private static final long child$OFFSET = $LAYOUT.byteOffset(groupElement("child"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static final long child$offset() {
        return child$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static int child(MemorySegment struct) {
        return struct.get(child$LAYOUT, child$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static void child(MemorySegment struct, int fieldValue) {
        struct.set(child$LAYOUT, child$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

