// Generated by jextract

package dev.equo.ewt.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int id;
 *     DartObj child;
 *     int behavior;
 *     int excludeFromSemantics;
 *     int dragStartBehavior;
 *     int trackpadScrollCausesScale;
 *     DartObj trackpadScrollToScaleFactor;
 * }
 * }
 */
public class GestureDetectorObjSt {

    GestureDetectorObjSt() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        StarterBridge.C_INT.withName("id"),
        StarterBridge.C_INT.withName("child"),
        StarterBridge.C_INT.withName("behavior"),
        StarterBridge.C_INT.withName("excludeFromSemantics"),
        StarterBridge.C_INT.withName("dragStartBehavior"),
        StarterBridge.C_INT.withName("trackpadScrollCausesScale"),
        StarterBridge.C_INT.withName("trackpadScrollToScaleFactor")
    ).withName("$anon$1064:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static final OfInt id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = $LAYOUT.byteOffset(groupElement("id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static int id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static void id(MemorySegment struct, int fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    private static final OfInt child$LAYOUT = (OfInt)$LAYOUT.select(groupElement("child"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static final OfInt child$layout() {
        return child$LAYOUT;
    }

    private static final long child$OFFSET = $LAYOUT.byteOffset(groupElement("child"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static final long child$offset() {
        return child$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static int child(MemorySegment struct) {
        return struct.get(child$LAYOUT, child$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static void child(MemorySegment struct, int fieldValue) {
        struct.set(child$LAYOUT, child$OFFSET, fieldValue);
    }

    private static final OfInt behavior$LAYOUT = (OfInt)$LAYOUT.select(groupElement("behavior"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int behavior
     * }
     */
    public static final OfInt behavior$layout() {
        return behavior$LAYOUT;
    }

    private static final long behavior$OFFSET = $LAYOUT.byteOffset(groupElement("behavior"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int behavior
     * }
     */
    public static final long behavior$offset() {
        return behavior$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int behavior
     * }
     */
    public static int behavior(MemorySegment struct) {
        return struct.get(behavior$LAYOUT, behavior$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int behavior
     * }
     */
    public static void behavior(MemorySegment struct, int fieldValue) {
        struct.set(behavior$LAYOUT, behavior$OFFSET, fieldValue);
    }

    private static final OfInt excludeFromSemantics$LAYOUT = (OfInt)$LAYOUT.select(groupElement("excludeFromSemantics"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int excludeFromSemantics
     * }
     */
    public static final OfInt excludeFromSemantics$layout() {
        return excludeFromSemantics$LAYOUT;
    }

    private static final long excludeFromSemantics$OFFSET = $LAYOUT.byteOffset(groupElement("excludeFromSemantics"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int excludeFromSemantics
     * }
     */
    public static final long excludeFromSemantics$offset() {
        return excludeFromSemantics$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int excludeFromSemantics
     * }
     */
    public static int excludeFromSemantics(MemorySegment struct) {
        return struct.get(excludeFromSemantics$LAYOUT, excludeFromSemantics$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int excludeFromSemantics
     * }
     */
    public static void excludeFromSemantics(MemorySegment struct, int fieldValue) {
        struct.set(excludeFromSemantics$LAYOUT, excludeFromSemantics$OFFSET, fieldValue);
    }

    private static final OfInt dragStartBehavior$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dragStartBehavior"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int dragStartBehavior
     * }
     */
    public static final OfInt dragStartBehavior$layout() {
        return dragStartBehavior$LAYOUT;
    }

    private static final long dragStartBehavior$OFFSET = $LAYOUT.byteOffset(groupElement("dragStartBehavior"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int dragStartBehavior
     * }
     */
    public static final long dragStartBehavior$offset() {
        return dragStartBehavior$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int dragStartBehavior
     * }
     */
    public static int dragStartBehavior(MemorySegment struct) {
        return struct.get(dragStartBehavior$LAYOUT, dragStartBehavior$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int dragStartBehavior
     * }
     */
    public static void dragStartBehavior(MemorySegment struct, int fieldValue) {
        struct.set(dragStartBehavior$LAYOUT, dragStartBehavior$OFFSET, fieldValue);
    }

    private static final OfInt trackpadScrollCausesScale$LAYOUT = (OfInt)$LAYOUT.select(groupElement("trackpadScrollCausesScale"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int trackpadScrollCausesScale
     * }
     */
    public static final OfInt trackpadScrollCausesScale$layout() {
        return trackpadScrollCausesScale$LAYOUT;
    }

    private static final long trackpadScrollCausesScale$OFFSET = $LAYOUT.byteOffset(groupElement("trackpadScrollCausesScale"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int trackpadScrollCausesScale
     * }
     */
    public static final long trackpadScrollCausesScale$offset() {
        return trackpadScrollCausesScale$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int trackpadScrollCausesScale
     * }
     */
    public static int trackpadScrollCausesScale(MemorySegment struct) {
        return struct.get(trackpadScrollCausesScale$LAYOUT, trackpadScrollCausesScale$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int trackpadScrollCausesScale
     * }
     */
    public static void trackpadScrollCausesScale(MemorySegment struct, int fieldValue) {
        struct.set(trackpadScrollCausesScale$LAYOUT, trackpadScrollCausesScale$OFFSET, fieldValue);
    }

    private static final OfInt trackpadScrollToScaleFactor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("trackpadScrollToScaleFactor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj trackpadScrollToScaleFactor
     * }
     */
    public static final OfInt trackpadScrollToScaleFactor$layout() {
        return trackpadScrollToScaleFactor$LAYOUT;
    }

    private static final long trackpadScrollToScaleFactor$OFFSET = $LAYOUT.byteOffset(groupElement("trackpadScrollToScaleFactor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj trackpadScrollToScaleFactor
     * }
     */
    public static final long trackpadScrollToScaleFactor$offset() {
        return trackpadScrollToScaleFactor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj trackpadScrollToScaleFactor
     * }
     */
    public static int trackpadScrollToScaleFactor(MemorySegment struct) {
        return struct.get(trackpadScrollToScaleFactor$LAYOUT, trackpadScrollToScaleFactor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj trackpadScrollToScaleFactor
     * }
     */
    public static void trackpadScrollToScaleFactor(MemorySegment struct, int fieldValue) {
        struct.set(trackpadScrollToScaleFactor$LAYOUT, trackpadScrollToScaleFactor$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

