// Generated by jextract

package dev.equo.ewt.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int id;
 *     DartObj leading;
 *     DartObj title;
 *     DartObj subtitle;
 *     DartObj trailing;
 *     int isThreeLine;
 *     int dense;
 *     VisualDensityObjSt visualDensity;
 *     DartObj shape;
 *     DartObj selectedColor;
 *     DartObj iconColor;
 *     DartObj textColor;
 *     TextStyleObjSt titleTextStyle;
 *     TextStyleObjSt subtitleTextStyle;
 *     TextStyleObjSt leadingAndTrailingTextStyle;
 *     int style;
 *     DartObj contentPadding;
 *     int enabled;
 *     int selected;
 *     DartObj focusColor;
 *     DartObj hoverColor;
 *     DartObj splashColor;
 *     int autofocus;
 *     DartObj tileColor;
 *     DartObj selectedTileColor;
 *     int enableFeedback;
 *     double horizontalTitleGap;
 *     double minVerticalPadding;
 *     double minLeadingWidth;
 *     double minTileHeight;
 *     int titleAlignment;
 *     int internalAddSemanticForOnTap;
 * }
 * }
 */
public class ListTileObjSt {

    ListTileObjSt() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        StarterBridge.C_INT.withName("id"),
        StarterBridge.C_INT.withName("leading"),
        StarterBridge.C_INT.withName("title"),
        StarterBridge.C_INT.withName("subtitle"),
        StarterBridge.C_INT.withName("trailing"),
        StarterBridge.C_INT.withName("isThreeLine"),
        StarterBridge.C_INT.withName("dense"),
        MemoryLayout.paddingLayout(4),
        VisualDensityObjSt.layout().withName("visualDensity"),
        StarterBridge.C_INT.withName("shape"),
        StarterBridge.C_INT.withName("selectedColor"),
        StarterBridge.C_INT.withName("iconColor"),
        StarterBridge.C_INT.withName("textColor"),
        TextStyleObjSt.layout().withName("titleTextStyle"),
        TextStyleObjSt.layout().withName("subtitleTextStyle"),
        TextStyleObjSt.layout().withName("leadingAndTrailingTextStyle"),
        StarterBridge.C_INT.withName("style"),
        StarterBridge.C_INT.withName("contentPadding"),
        StarterBridge.C_INT.withName("enabled"),
        StarterBridge.C_INT.withName("selected"),
        StarterBridge.C_INT.withName("focusColor"),
        StarterBridge.C_INT.withName("hoverColor"),
        StarterBridge.C_INT.withName("splashColor"),
        StarterBridge.C_INT.withName("autofocus"),
        StarterBridge.C_INT.withName("tileColor"),
        StarterBridge.C_INT.withName("selectedTileColor"),
        StarterBridge.C_INT.withName("enableFeedback"),
        MemoryLayout.paddingLayout(4),
        StarterBridge.C_DOUBLE.withName("horizontalTitleGap"),
        StarterBridge.C_DOUBLE.withName("minVerticalPadding"),
        StarterBridge.C_DOUBLE.withName("minLeadingWidth"),
        StarterBridge.C_DOUBLE.withName("minTileHeight"),
        StarterBridge.C_INT.withName("titleAlignment"),
        StarterBridge.C_INT.withName("internalAddSemanticForOnTap")
    ).withName("$anon$902:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static final OfInt id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = $LAYOUT.byteOffset(groupElement("id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static int id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static void id(MemorySegment struct, int fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    private static final OfInt leading$LAYOUT = (OfInt)$LAYOUT.select(groupElement("leading"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj leading
     * }
     */
    public static final OfInt leading$layout() {
        return leading$LAYOUT;
    }

    private static final long leading$OFFSET = $LAYOUT.byteOffset(groupElement("leading"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj leading
     * }
     */
    public static final long leading$offset() {
        return leading$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj leading
     * }
     */
    public static int leading(MemorySegment struct) {
        return struct.get(leading$LAYOUT, leading$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj leading
     * }
     */
    public static void leading(MemorySegment struct, int fieldValue) {
        struct.set(leading$LAYOUT, leading$OFFSET, fieldValue);
    }

    private static final OfInt title$LAYOUT = (OfInt)$LAYOUT.select(groupElement("title"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj title
     * }
     */
    public static final OfInt title$layout() {
        return title$LAYOUT;
    }

    private static final long title$OFFSET = $LAYOUT.byteOffset(groupElement("title"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj title
     * }
     */
    public static final long title$offset() {
        return title$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj title
     * }
     */
    public static int title(MemorySegment struct) {
        return struct.get(title$LAYOUT, title$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj title
     * }
     */
    public static void title(MemorySegment struct, int fieldValue) {
        struct.set(title$LAYOUT, title$OFFSET, fieldValue);
    }

    private static final OfInt subtitle$LAYOUT = (OfInt)$LAYOUT.select(groupElement("subtitle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj subtitle
     * }
     */
    public static final OfInt subtitle$layout() {
        return subtitle$LAYOUT;
    }

    private static final long subtitle$OFFSET = $LAYOUT.byteOffset(groupElement("subtitle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj subtitle
     * }
     */
    public static final long subtitle$offset() {
        return subtitle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj subtitle
     * }
     */
    public static int subtitle(MemorySegment struct) {
        return struct.get(subtitle$LAYOUT, subtitle$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj subtitle
     * }
     */
    public static void subtitle(MemorySegment struct, int fieldValue) {
        struct.set(subtitle$LAYOUT, subtitle$OFFSET, fieldValue);
    }

    private static final OfInt trailing$LAYOUT = (OfInt)$LAYOUT.select(groupElement("trailing"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj trailing
     * }
     */
    public static final OfInt trailing$layout() {
        return trailing$LAYOUT;
    }

    private static final long trailing$OFFSET = $LAYOUT.byteOffset(groupElement("trailing"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj trailing
     * }
     */
    public static final long trailing$offset() {
        return trailing$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj trailing
     * }
     */
    public static int trailing(MemorySegment struct) {
        return struct.get(trailing$LAYOUT, trailing$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj trailing
     * }
     */
    public static void trailing(MemorySegment struct, int fieldValue) {
        struct.set(trailing$LAYOUT, trailing$OFFSET, fieldValue);
    }

    private static final OfInt isThreeLine$LAYOUT = (OfInt)$LAYOUT.select(groupElement("isThreeLine"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int isThreeLine
     * }
     */
    public static final OfInt isThreeLine$layout() {
        return isThreeLine$LAYOUT;
    }

    private static final long isThreeLine$OFFSET = $LAYOUT.byteOffset(groupElement("isThreeLine"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int isThreeLine
     * }
     */
    public static final long isThreeLine$offset() {
        return isThreeLine$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int isThreeLine
     * }
     */
    public static int isThreeLine(MemorySegment struct) {
        return struct.get(isThreeLine$LAYOUT, isThreeLine$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int isThreeLine
     * }
     */
    public static void isThreeLine(MemorySegment struct, int fieldValue) {
        struct.set(isThreeLine$LAYOUT, isThreeLine$OFFSET, fieldValue);
    }

    private static final OfInt dense$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dense"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int dense
     * }
     */
    public static final OfInt dense$layout() {
        return dense$LAYOUT;
    }

    private static final long dense$OFFSET = $LAYOUT.byteOffset(groupElement("dense"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int dense
     * }
     */
    public static final long dense$offset() {
        return dense$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int dense
     * }
     */
    public static int dense(MemorySegment struct) {
        return struct.get(dense$LAYOUT, dense$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int dense
     * }
     */
    public static void dense(MemorySegment struct, int fieldValue) {
        struct.set(dense$LAYOUT, dense$OFFSET, fieldValue);
    }

    private static final GroupLayout visualDensity$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("visualDensity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VisualDensityObjSt visualDensity
     * }
     */
    public static final GroupLayout visualDensity$layout() {
        return visualDensity$LAYOUT;
    }

    private static final long visualDensity$OFFSET = $LAYOUT.byteOffset(groupElement("visualDensity"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VisualDensityObjSt visualDensity
     * }
     */
    public static final long visualDensity$offset() {
        return visualDensity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VisualDensityObjSt visualDensity
     * }
     */
    public static MemorySegment visualDensity(MemorySegment struct) {
        return struct.asSlice(visualDensity$OFFSET, visualDensity$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VisualDensityObjSt visualDensity
     * }
     */
    public static void visualDensity(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, visualDensity$OFFSET, visualDensity$LAYOUT.byteSize());
    }

    private static final OfInt shape$LAYOUT = (OfInt)$LAYOUT.select(groupElement("shape"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj shape
     * }
     */
    public static final OfInt shape$layout() {
        return shape$LAYOUT;
    }

    private static final long shape$OFFSET = $LAYOUT.byteOffset(groupElement("shape"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj shape
     * }
     */
    public static final long shape$offset() {
        return shape$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj shape
     * }
     */
    public static int shape(MemorySegment struct) {
        return struct.get(shape$LAYOUT, shape$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj shape
     * }
     */
    public static void shape(MemorySegment struct, int fieldValue) {
        struct.set(shape$LAYOUT, shape$OFFSET, fieldValue);
    }

    private static final OfInt selectedColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("selectedColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj selectedColor
     * }
     */
    public static final OfInt selectedColor$layout() {
        return selectedColor$LAYOUT;
    }

    private static final long selectedColor$OFFSET = $LAYOUT.byteOffset(groupElement("selectedColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj selectedColor
     * }
     */
    public static final long selectedColor$offset() {
        return selectedColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj selectedColor
     * }
     */
    public static int selectedColor(MemorySegment struct) {
        return struct.get(selectedColor$LAYOUT, selectedColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj selectedColor
     * }
     */
    public static void selectedColor(MemorySegment struct, int fieldValue) {
        struct.set(selectedColor$LAYOUT, selectedColor$OFFSET, fieldValue);
    }

    private static final OfInt iconColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("iconColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj iconColor
     * }
     */
    public static final OfInt iconColor$layout() {
        return iconColor$LAYOUT;
    }

    private static final long iconColor$OFFSET = $LAYOUT.byteOffset(groupElement("iconColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj iconColor
     * }
     */
    public static final long iconColor$offset() {
        return iconColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj iconColor
     * }
     */
    public static int iconColor(MemorySegment struct) {
        return struct.get(iconColor$LAYOUT, iconColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj iconColor
     * }
     */
    public static void iconColor(MemorySegment struct, int fieldValue) {
        struct.set(iconColor$LAYOUT, iconColor$OFFSET, fieldValue);
    }

    private static final OfInt textColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("textColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj textColor
     * }
     */
    public static final OfInt textColor$layout() {
        return textColor$LAYOUT;
    }

    private static final long textColor$OFFSET = $LAYOUT.byteOffset(groupElement("textColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj textColor
     * }
     */
    public static final long textColor$offset() {
        return textColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj textColor
     * }
     */
    public static int textColor(MemorySegment struct) {
        return struct.get(textColor$LAYOUT, textColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj textColor
     * }
     */
    public static void textColor(MemorySegment struct, int fieldValue) {
        struct.set(textColor$LAYOUT, textColor$OFFSET, fieldValue);
    }

    private static final GroupLayout titleTextStyle$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("titleTextStyle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TextStyleObjSt titleTextStyle
     * }
     */
    public static final GroupLayout titleTextStyle$layout() {
        return titleTextStyle$LAYOUT;
    }

    private static final long titleTextStyle$OFFSET = $LAYOUT.byteOffset(groupElement("titleTextStyle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TextStyleObjSt titleTextStyle
     * }
     */
    public static final long titleTextStyle$offset() {
        return titleTextStyle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TextStyleObjSt titleTextStyle
     * }
     */
    public static MemorySegment titleTextStyle(MemorySegment struct) {
        return struct.asSlice(titleTextStyle$OFFSET, titleTextStyle$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TextStyleObjSt titleTextStyle
     * }
     */
    public static void titleTextStyle(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, titleTextStyle$OFFSET, titleTextStyle$LAYOUT.byteSize());
    }

    private static final GroupLayout subtitleTextStyle$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("subtitleTextStyle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TextStyleObjSt subtitleTextStyle
     * }
     */
    public static final GroupLayout subtitleTextStyle$layout() {
        return subtitleTextStyle$LAYOUT;
    }

    private static final long subtitleTextStyle$OFFSET = $LAYOUT.byteOffset(groupElement("subtitleTextStyle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TextStyleObjSt subtitleTextStyle
     * }
     */
    public static final long subtitleTextStyle$offset() {
        return subtitleTextStyle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TextStyleObjSt subtitleTextStyle
     * }
     */
    public static MemorySegment subtitleTextStyle(MemorySegment struct) {
        return struct.asSlice(subtitleTextStyle$OFFSET, subtitleTextStyle$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TextStyleObjSt subtitleTextStyle
     * }
     */
    public static void subtitleTextStyle(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, subtitleTextStyle$OFFSET, subtitleTextStyle$LAYOUT.byteSize());
    }

    private static final GroupLayout leadingAndTrailingTextStyle$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("leadingAndTrailingTextStyle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TextStyleObjSt leadingAndTrailingTextStyle
     * }
     */
    public static final GroupLayout leadingAndTrailingTextStyle$layout() {
        return leadingAndTrailingTextStyle$LAYOUT;
    }

    private static final long leadingAndTrailingTextStyle$OFFSET = $LAYOUT.byteOffset(groupElement("leadingAndTrailingTextStyle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TextStyleObjSt leadingAndTrailingTextStyle
     * }
     */
    public static final long leadingAndTrailingTextStyle$offset() {
        return leadingAndTrailingTextStyle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TextStyleObjSt leadingAndTrailingTextStyle
     * }
     */
    public static MemorySegment leadingAndTrailingTextStyle(MemorySegment struct) {
        return struct.asSlice(leadingAndTrailingTextStyle$OFFSET, leadingAndTrailingTextStyle$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TextStyleObjSt leadingAndTrailingTextStyle
     * }
     */
    public static void leadingAndTrailingTextStyle(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, leadingAndTrailingTextStyle$OFFSET, leadingAndTrailingTextStyle$LAYOUT.byteSize());
    }

    private static final OfInt style$LAYOUT = (OfInt)$LAYOUT.select(groupElement("style"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int style
     * }
     */
    public static final OfInt style$layout() {
        return style$LAYOUT;
    }

    private static final long style$OFFSET = $LAYOUT.byteOffset(groupElement("style"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int style
     * }
     */
    public static final long style$offset() {
        return style$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int style
     * }
     */
    public static int style(MemorySegment struct) {
        return struct.get(style$LAYOUT, style$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int style
     * }
     */
    public static void style(MemorySegment struct, int fieldValue) {
        struct.set(style$LAYOUT, style$OFFSET, fieldValue);
    }

    private static final OfInt contentPadding$LAYOUT = (OfInt)$LAYOUT.select(groupElement("contentPadding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj contentPadding
     * }
     */
    public static final OfInt contentPadding$layout() {
        return contentPadding$LAYOUT;
    }

    private static final long contentPadding$OFFSET = $LAYOUT.byteOffset(groupElement("contentPadding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj contentPadding
     * }
     */
    public static final long contentPadding$offset() {
        return contentPadding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj contentPadding
     * }
     */
    public static int contentPadding(MemorySegment struct) {
        return struct.get(contentPadding$LAYOUT, contentPadding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj contentPadding
     * }
     */
    public static void contentPadding(MemorySegment struct, int fieldValue) {
        struct.set(contentPadding$LAYOUT, contentPadding$OFFSET, fieldValue);
    }

    private static final OfInt enabled$LAYOUT = (OfInt)$LAYOUT.select(groupElement("enabled"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int enabled
     * }
     */
    public static final OfInt enabled$layout() {
        return enabled$LAYOUT;
    }

    private static final long enabled$OFFSET = $LAYOUT.byteOffset(groupElement("enabled"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int enabled
     * }
     */
    public static final long enabled$offset() {
        return enabled$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int enabled
     * }
     */
    public static int enabled(MemorySegment struct) {
        return struct.get(enabled$LAYOUT, enabled$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int enabled
     * }
     */
    public static void enabled(MemorySegment struct, int fieldValue) {
        struct.set(enabled$LAYOUT, enabled$OFFSET, fieldValue);
    }

    private static final OfInt selected$LAYOUT = (OfInt)$LAYOUT.select(groupElement("selected"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int selected
     * }
     */
    public static final OfInt selected$layout() {
        return selected$LAYOUT;
    }

    private static final long selected$OFFSET = $LAYOUT.byteOffset(groupElement("selected"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int selected
     * }
     */
    public static final long selected$offset() {
        return selected$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int selected
     * }
     */
    public static int selected(MemorySegment struct) {
        return struct.get(selected$LAYOUT, selected$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int selected
     * }
     */
    public static void selected(MemorySegment struct, int fieldValue) {
        struct.set(selected$LAYOUT, selected$OFFSET, fieldValue);
    }

    private static final OfInt focusColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("focusColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj focusColor
     * }
     */
    public static final OfInt focusColor$layout() {
        return focusColor$LAYOUT;
    }

    private static final long focusColor$OFFSET = $LAYOUT.byteOffset(groupElement("focusColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj focusColor
     * }
     */
    public static final long focusColor$offset() {
        return focusColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj focusColor
     * }
     */
    public static int focusColor(MemorySegment struct) {
        return struct.get(focusColor$LAYOUT, focusColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj focusColor
     * }
     */
    public static void focusColor(MemorySegment struct, int fieldValue) {
        struct.set(focusColor$LAYOUT, focusColor$OFFSET, fieldValue);
    }

    private static final OfInt hoverColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("hoverColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj hoverColor
     * }
     */
    public static final OfInt hoverColor$layout() {
        return hoverColor$LAYOUT;
    }

    private static final long hoverColor$OFFSET = $LAYOUT.byteOffset(groupElement("hoverColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj hoverColor
     * }
     */
    public static final long hoverColor$offset() {
        return hoverColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj hoverColor
     * }
     */
    public static int hoverColor(MemorySegment struct) {
        return struct.get(hoverColor$LAYOUT, hoverColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj hoverColor
     * }
     */
    public static void hoverColor(MemorySegment struct, int fieldValue) {
        struct.set(hoverColor$LAYOUT, hoverColor$OFFSET, fieldValue);
    }

    private static final OfInt splashColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("splashColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj splashColor
     * }
     */
    public static final OfInt splashColor$layout() {
        return splashColor$LAYOUT;
    }

    private static final long splashColor$OFFSET = $LAYOUT.byteOffset(groupElement("splashColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj splashColor
     * }
     */
    public static final long splashColor$offset() {
        return splashColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj splashColor
     * }
     */
    public static int splashColor(MemorySegment struct) {
        return struct.get(splashColor$LAYOUT, splashColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj splashColor
     * }
     */
    public static void splashColor(MemorySegment struct, int fieldValue) {
        struct.set(splashColor$LAYOUT, splashColor$OFFSET, fieldValue);
    }

    private static final OfInt autofocus$LAYOUT = (OfInt)$LAYOUT.select(groupElement("autofocus"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int autofocus
     * }
     */
    public static final OfInt autofocus$layout() {
        return autofocus$LAYOUT;
    }

    private static final long autofocus$OFFSET = $LAYOUT.byteOffset(groupElement("autofocus"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int autofocus
     * }
     */
    public static final long autofocus$offset() {
        return autofocus$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int autofocus
     * }
     */
    public static int autofocus(MemorySegment struct) {
        return struct.get(autofocus$LAYOUT, autofocus$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int autofocus
     * }
     */
    public static void autofocus(MemorySegment struct, int fieldValue) {
        struct.set(autofocus$LAYOUT, autofocus$OFFSET, fieldValue);
    }

    private static final OfInt tileColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("tileColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj tileColor
     * }
     */
    public static final OfInt tileColor$layout() {
        return tileColor$LAYOUT;
    }

    private static final long tileColor$OFFSET = $LAYOUT.byteOffset(groupElement("tileColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj tileColor
     * }
     */
    public static final long tileColor$offset() {
        return tileColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj tileColor
     * }
     */
    public static int tileColor(MemorySegment struct) {
        return struct.get(tileColor$LAYOUT, tileColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj tileColor
     * }
     */
    public static void tileColor(MemorySegment struct, int fieldValue) {
        struct.set(tileColor$LAYOUT, tileColor$OFFSET, fieldValue);
    }

    private static final OfInt selectedTileColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("selectedTileColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj selectedTileColor
     * }
     */
    public static final OfInt selectedTileColor$layout() {
        return selectedTileColor$LAYOUT;
    }

    private static final long selectedTileColor$OFFSET = $LAYOUT.byteOffset(groupElement("selectedTileColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj selectedTileColor
     * }
     */
    public static final long selectedTileColor$offset() {
        return selectedTileColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj selectedTileColor
     * }
     */
    public static int selectedTileColor(MemorySegment struct) {
        return struct.get(selectedTileColor$LAYOUT, selectedTileColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj selectedTileColor
     * }
     */
    public static void selectedTileColor(MemorySegment struct, int fieldValue) {
        struct.set(selectedTileColor$LAYOUT, selectedTileColor$OFFSET, fieldValue);
    }

    private static final OfInt enableFeedback$LAYOUT = (OfInt)$LAYOUT.select(groupElement("enableFeedback"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int enableFeedback
     * }
     */
    public static final OfInt enableFeedback$layout() {
        return enableFeedback$LAYOUT;
    }

    private static final long enableFeedback$OFFSET = $LAYOUT.byteOffset(groupElement("enableFeedback"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int enableFeedback
     * }
     */
    public static final long enableFeedback$offset() {
        return enableFeedback$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int enableFeedback
     * }
     */
    public static int enableFeedback(MemorySegment struct) {
        return struct.get(enableFeedback$LAYOUT, enableFeedback$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int enableFeedback
     * }
     */
    public static void enableFeedback(MemorySegment struct, int fieldValue) {
        struct.set(enableFeedback$LAYOUT, enableFeedback$OFFSET, fieldValue);
    }

    private static final OfDouble horizontalTitleGap$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("horizontalTitleGap"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double horizontalTitleGap
     * }
     */
    public static final OfDouble horizontalTitleGap$layout() {
        return horizontalTitleGap$LAYOUT;
    }

    private static final long horizontalTitleGap$OFFSET = $LAYOUT.byteOffset(groupElement("horizontalTitleGap"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double horizontalTitleGap
     * }
     */
    public static final long horizontalTitleGap$offset() {
        return horizontalTitleGap$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double horizontalTitleGap
     * }
     */
    public static double horizontalTitleGap(MemorySegment struct) {
        return struct.get(horizontalTitleGap$LAYOUT, horizontalTitleGap$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double horizontalTitleGap
     * }
     */
    public static void horizontalTitleGap(MemorySegment struct, double fieldValue) {
        struct.set(horizontalTitleGap$LAYOUT, horizontalTitleGap$OFFSET, fieldValue);
    }

    private static final OfDouble minVerticalPadding$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("minVerticalPadding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double minVerticalPadding
     * }
     */
    public static final OfDouble minVerticalPadding$layout() {
        return minVerticalPadding$LAYOUT;
    }

    private static final long minVerticalPadding$OFFSET = $LAYOUT.byteOffset(groupElement("minVerticalPadding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double minVerticalPadding
     * }
     */
    public static final long minVerticalPadding$offset() {
        return minVerticalPadding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double minVerticalPadding
     * }
     */
    public static double minVerticalPadding(MemorySegment struct) {
        return struct.get(minVerticalPadding$LAYOUT, minVerticalPadding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double minVerticalPadding
     * }
     */
    public static void minVerticalPadding(MemorySegment struct, double fieldValue) {
        struct.set(minVerticalPadding$LAYOUT, minVerticalPadding$OFFSET, fieldValue);
    }

    private static final OfDouble minLeadingWidth$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("minLeadingWidth"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double minLeadingWidth
     * }
     */
    public static final OfDouble minLeadingWidth$layout() {
        return minLeadingWidth$LAYOUT;
    }

    private static final long minLeadingWidth$OFFSET = $LAYOUT.byteOffset(groupElement("minLeadingWidth"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double minLeadingWidth
     * }
     */
    public static final long minLeadingWidth$offset() {
        return minLeadingWidth$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double minLeadingWidth
     * }
     */
    public static double minLeadingWidth(MemorySegment struct) {
        return struct.get(minLeadingWidth$LAYOUT, minLeadingWidth$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double minLeadingWidth
     * }
     */
    public static void minLeadingWidth(MemorySegment struct, double fieldValue) {
        struct.set(minLeadingWidth$LAYOUT, minLeadingWidth$OFFSET, fieldValue);
    }

    private static final OfDouble minTileHeight$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("minTileHeight"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double minTileHeight
     * }
     */
    public static final OfDouble minTileHeight$layout() {
        return minTileHeight$LAYOUT;
    }

    private static final long minTileHeight$OFFSET = $LAYOUT.byteOffset(groupElement("minTileHeight"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double minTileHeight
     * }
     */
    public static final long minTileHeight$offset() {
        return minTileHeight$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double minTileHeight
     * }
     */
    public static double minTileHeight(MemorySegment struct) {
        return struct.get(minTileHeight$LAYOUT, minTileHeight$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double minTileHeight
     * }
     */
    public static void minTileHeight(MemorySegment struct, double fieldValue) {
        struct.set(minTileHeight$LAYOUT, minTileHeight$OFFSET, fieldValue);
    }

    private static final OfInt titleAlignment$LAYOUT = (OfInt)$LAYOUT.select(groupElement("titleAlignment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int titleAlignment
     * }
     */
    public static final OfInt titleAlignment$layout() {
        return titleAlignment$LAYOUT;
    }

    private static final long titleAlignment$OFFSET = $LAYOUT.byteOffset(groupElement("titleAlignment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int titleAlignment
     * }
     */
    public static final long titleAlignment$offset() {
        return titleAlignment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int titleAlignment
     * }
     */
    public static int titleAlignment(MemorySegment struct) {
        return struct.get(titleAlignment$LAYOUT, titleAlignment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int titleAlignment
     * }
     */
    public static void titleAlignment(MemorySegment struct, int fieldValue) {
        struct.set(titleAlignment$LAYOUT, titleAlignment$OFFSET, fieldValue);
    }

    private static final OfInt internalAddSemanticForOnTap$LAYOUT = (OfInt)$LAYOUT.select(groupElement("internalAddSemanticForOnTap"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int internalAddSemanticForOnTap
     * }
     */
    public static final OfInt internalAddSemanticForOnTap$layout() {
        return internalAddSemanticForOnTap$LAYOUT;
    }

    private static final long internalAddSemanticForOnTap$OFFSET = $LAYOUT.byteOffset(groupElement("internalAddSemanticForOnTap"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int internalAddSemanticForOnTap
     * }
     */
    public static final long internalAddSemanticForOnTap$offset() {
        return internalAddSemanticForOnTap$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int internalAddSemanticForOnTap
     * }
     */
    public static int internalAddSemanticForOnTap(MemorySegment struct) {
        return struct.get(internalAddSemanticForOnTap$LAYOUT, internalAddSemanticForOnTap$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int internalAddSemanticForOnTap
     * }
     */
    public static void internalAddSemanticForOnTap(MemorySegment struct, int fieldValue) {
        struct.set(internalAddSemanticForOnTap$LAYOUT, internalAddSemanticForOnTap$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

