// Generated by jextract

package dev.equo.ewt.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int id;
 *     int scrollDirection;
 *     int reverse;
 *     DartObj padding;
 *     int primary;
 *     DartObj child;
 *     int dragStartBehavior;
 *     int clipBehavior;
 *     int hitTestBehavior;
 *     char *restorationId;
 *     int keyboardDismissBehavior;
 * }
 * }
 */
public class SingleChildScrollViewObjSt {

    SingleChildScrollViewObjSt() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        StarterBridge.C_INT.withName("id"),
        StarterBridge.C_INT.withName("scrollDirection"),
        StarterBridge.C_INT.withName("reverse"),
        StarterBridge.C_INT.withName("padding"),
        StarterBridge.C_INT.withName("primary"),
        StarterBridge.C_INT.withName("child"),
        StarterBridge.C_INT.withName("dragStartBehavior"),
        StarterBridge.C_INT.withName("clipBehavior"),
        StarterBridge.C_INT.withName("hitTestBehavior"),
        MemoryLayout.paddingLayout(4),
        StarterBridge.C_POINTER.withName("restorationId"),
        StarterBridge.C_INT.withName("keyboardDismissBehavior"),
        MemoryLayout.paddingLayout(4)
    ).withName("$anon$950:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static final OfInt id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = $LAYOUT.byteOffset(groupElement("id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static int id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static void id(MemorySegment struct, int fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    private static final OfInt scrollDirection$LAYOUT = (OfInt)$LAYOUT.select(groupElement("scrollDirection"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int scrollDirection
     * }
     */
    public static final OfInt scrollDirection$layout() {
        return scrollDirection$LAYOUT;
    }

    private static final long scrollDirection$OFFSET = $LAYOUT.byteOffset(groupElement("scrollDirection"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int scrollDirection
     * }
     */
    public static final long scrollDirection$offset() {
        return scrollDirection$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int scrollDirection
     * }
     */
    public static int scrollDirection(MemorySegment struct) {
        return struct.get(scrollDirection$LAYOUT, scrollDirection$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int scrollDirection
     * }
     */
    public static void scrollDirection(MemorySegment struct, int fieldValue) {
        struct.set(scrollDirection$LAYOUT, scrollDirection$OFFSET, fieldValue);
    }

    private static final OfInt reverse$LAYOUT = (OfInt)$LAYOUT.select(groupElement("reverse"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int reverse
     * }
     */
    public static final OfInt reverse$layout() {
        return reverse$LAYOUT;
    }

    private static final long reverse$OFFSET = $LAYOUT.byteOffset(groupElement("reverse"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int reverse
     * }
     */
    public static final long reverse$offset() {
        return reverse$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int reverse
     * }
     */
    public static int reverse(MemorySegment struct) {
        return struct.get(reverse$LAYOUT, reverse$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int reverse
     * }
     */
    public static void reverse(MemorySegment struct, int fieldValue) {
        struct.set(reverse$LAYOUT, reverse$OFFSET, fieldValue);
    }

    private static final OfInt padding$LAYOUT = (OfInt)$LAYOUT.select(groupElement("padding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj padding
     * }
     */
    public static final OfInt padding$layout() {
        return padding$LAYOUT;
    }

    private static final long padding$OFFSET = $LAYOUT.byteOffset(groupElement("padding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj padding
     * }
     */
    public static final long padding$offset() {
        return padding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj padding
     * }
     */
    public static int padding(MemorySegment struct) {
        return struct.get(padding$LAYOUT, padding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj padding
     * }
     */
    public static void padding(MemorySegment struct, int fieldValue) {
        struct.set(padding$LAYOUT, padding$OFFSET, fieldValue);
    }

    private static final OfInt primary$LAYOUT = (OfInt)$LAYOUT.select(groupElement("primary"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int primary
     * }
     */
    public static final OfInt primary$layout() {
        return primary$LAYOUT;
    }

    private static final long primary$OFFSET = $LAYOUT.byteOffset(groupElement("primary"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int primary
     * }
     */
    public static final long primary$offset() {
        return primary$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int primary
     * }
     */
    public static int primary(MemorySegment struct) {
        return struct.get(primary$LAYOUT, primary$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int primary
     * }
     */
    public static void primary(MemorySegment struct, int fieldValue) {
        struct.set(primary$LAYOUT, primary$OFFSET, fieldValue);
    }

    private static final OfInt child$LAYOUT = (OfInt)$LAYOUT.select(groupElement("child"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static final OfInt child$layout() {
        return child$LAYOUT;
    }

    private static final long child$OFFSET = $LAYOUT.byteOffset(groupElement("child"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static final long child$offset() {
        return child$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static int child(MemorySegment struct) {
        return struct.get(child$LAYOUT, child$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static void child(MemorySegment struct, int fieldValue) {
        struct.set(child$LAYOUT, child$OFFSET, fieldValue);
    }

    private static final OfInt dragStartBehavior$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dragStartBehavior"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int dragStartBehavior
     * }
     */
    public static final OfInt dragStartBehavior$layout() {
        return dragStartBehavior$LAYOUT;
    }

    private static final long dragStartBehavior$OFFSET = $LAYOUT.byteOffset(groupElement("dragStartBehavior"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int dragStartBehavior
     * }
     */
    public static final long dragStartBehavior$offset() {
        return dragStartBehavior$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int dragStartBehavior
     * }
     */
    public static int dragStartBehavior(MemorySegment struct) {
        return struct.get(dragStartBehavior$LAYOUT, dragStartBehavior$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int dragStartBehavior
     * }
     */
    public static void dragStartBehavior(MemorySegment struct, int fieldValue) {
        struct.set(dragStartBehavior$LAYOUT, dragStartBehavior$OFFSET, fieldValue);
    }

    private static final OfInt clipBehavior$LAYOUT = (OfInt)$LAYOUT.select(groupElement("clipBehavior"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int clipBehavior
     * }
     */
    public static final OfInt clipBehavior$layout() {
        return clipBehavior$LAYOUT;
    }

    private static final long clipBehavior$OFFSET = $LAYOUT.byteOffset(groupElement("clipBehavior"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int clipBehavior
     * }
     */
    public static final long clipBehavior$offset() {
        return clipBehavior$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int clipBehavior
     * }
     */
    public static int clipBehavior(MemorySegment struct) {
        return struct.get(clipBehavior$LAYOUT, clipBehavior$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int clipBehavior
     * }
     */
    public static void clipBehavior(MemorySegment struct, int fieldValue) {
        struct.set(clipBehavior$LAYOUT, clipBehavior$OFFSET, fieldValue);
    }

    private static final OfInt hitTestBehavior$LAYOUT = (OfInt)$LAYOUT.select(groupElement("hitTestBehavior"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int hitTestBehavior
     * }
     */
    public static final OfInt hitTestBehavior$layout() {
        return hitTestBehavior$LAYOUT;
    }

    private static final long hitTestBehavior$OFFSET = $LAYOUT.byteOffset(groupElement("hitTestBehavior"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int hitTestBehavior
     * }
     */
    public static final long hitTestBehavior$offset() {
        return hitTestBehavior$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int hitTestBehavior
     * }
     */
    public static int hitTestBehavior(MemorySegment struct) {
        return struct.get(hitTestBehavior$LAYOUT, hitTestBehavior$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int hitTestBehavior
     * }
     */
    public static void hitTestBehavior(MemorySegment struct, int fieldValue) {
        struct.set(hitTestBehavior$LAYOUT, hitTestBehavior$OFFSET, fieldValue);
    }

    private static final AddressLayout restorationId$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("restorationId"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *restorationId
     * }
     */
    public static final AddressLayout restorationId$layout() {
        return restorationId$LAYOUT;
    }

    private static final long restorationId$OFFSET = $LAYOUT.byteOffset(groupElement("restorationId"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *restorationId
     * }
     */
    public static final long restorationId$offset() {
        return restorationId$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *restorationId
     * }
     */
    public static MemorySegment restorationId(MemorySegment struct) {
        return struct.get(restorationId$LAYOUT, restorationId$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *restorationId
     * }
     */
    public static void restorationId(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(restorationId$LAYOUT, restorationId$OFFSET, fieldValue);
    }

    private static final OfInt keyboardDismissBehavior$LAYOUT = (OfInt)$LAYOUT.select(groupElement("keyboardDismissBehavior"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int keyboardDismissBehavior
     * }
     */
    public static final OfInt keyboardDismissBehavior$layout() {
        return keyboardDismissBehavior$LAYOUT;
    }

    private static final long keyboardDismissBehavior$OFFSET = $LAYOUT.byteOffset(groupElement("keyboardDismissBehavior"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int keyboardDismissBehavior
     * }
     */
    public static final long keyboardDismissBehavior$offset() {
        return keyboardDismissBehavior$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int keyboardDismissBehavior
     * }
     */
    public static int keyboardDismissBehavior(MemorySegment struct) {
        return struct.get(keyboardDismissBehavior$LAYOUT, keyboardDismissBehavior$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int keyboardDismissBehavior
     * }
     */
    public static void keyboardDismissBehavior(MemorySegment struct, int fieldValue) {
        struct.set(keyboardDismissBehavior$LAYOUT, keyboardDismissBehavior$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

