// Generated by jextract

package dev.equo.ewt.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int id;
 *     int value;
 *     DartObj activeColor;
 *     DartObj activeThumbColor;
 *     DartObj activeTrackColor;
 *     DartObj inactiveThumbColor;
 *     DartObj inactiveTrackColor;
 *     int materialTapTargetSize;
 *     int applyCupertinoTheme;
 *     int dragStartBehavior;
 *     DartObj focusColor;
 *     DartObj hoverColor;
 *     double splashRadius;
 *     int autofocus;
 *     DartObj padding;
 * }
 * }
 */
public class SwitchObjSt {

    SwitchObjSt() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        StarterBridge.C_INT.withName("id"),
        StarterBridge.C_INT.withName("value"),
        StarterBridge.C_INT.withName("activeColor"),
        StarterBridge.C_INT.withName("activeThumbColor"),
        StarterBridge.C_INT.withName("activeTrackColor"),
        StarterBridge.C_INT.withName("inactiveThumbColor"),
        StarterBridge.C_INT.withName("inactiveTrackColor"),
        StarterBridge.C_INT.withName("materialTapTargetSize"),
        StarterBridge.C_INT.withName("applyCupertinoTheme"),
        StarterBridge.C_INT.withName("dragStartBehavior"),
        StarterBridge.C_INT.withName("focusColor"),
        StarterBridge.C_INT.withName("hoverColor"),
        StarterBridge.C_DOUBLE.withName("splashRadius"),
        StarterBridge.C_INT.withName("autofocus"),
        StarterBridge.C_INT.withName("padding")
    ).withName("$anon$1175:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static final OfInt id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = $LAYOUT.byteOffset(groupElement("id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static int id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static void id(MemorySegment struct, int fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    private static final OfInt value$LAYOUT = (OfInt)$LAYOUT.select(groupElement("value"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int value
     * }
     */
    public static final OfInt value$layout() {
        return value$LAYOUT;
    }

    private static final long value$OFFSET = $LAYOUT.byteOffset(groupElement("value"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int value
     * }
     */
    public static final long value$offset() {
        return value$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int value
     * }
     */
    public static int value(MemorySegment struct) {
        return struct.get(value$LAYOUT, value$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int value
     * }
     */
    public static void value(MemorySegment struct, int fieldValue) {
        struct.set(value$LAYOUT, value$OFFSET, fieldValue);
    }

    private static final OfInt activeColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("activeColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj activeColor
     * }
     */
    public static final OfInt activeColor$layout() {
        return activeColor$LAYOUT;
    }

    private static final long activeColor$OFFSET = $LAYOUT.byteOffset(groupElement("activeColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj activeColor
     * }
     */
    public static final long activeColor$offset() {
        return activeColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj activeColor
     * }
     */
    public static int activeColor(MemorySegment struct) {
        return struct.get(activeColor$LAYOUT, activeColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj activeColor
     * }
     */
    public static void activeColor(MemorySegment struct, int fieldValue) {
        struct.set(activeColor$LAYOUT, activeColor$OFFSET, fieldValue);
    }

    private static final OfInt activeThumbColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("activeThumbColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj activeThumbColor
     * }
     */
    public static final OfInt activeThumbColor$layout() {
        return activeThumbColor$LAYOUT;
    }

    private static final long activeThumbColor$OFFSET = $LAYOUT.byteOffset(groupElement("activeThumbColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj activeThumbColor
     * }
     */
    public static final long activeThumbColor$offset() {
        return activeThumbColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj activeThumbColor
     * }
     */
    public static int activeThumbColor(MemorySegment struct) {
        return struct.get(activeThumbColor$LAYOUT, activeThumbColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj activeThumbColor
     * }
     */
    public static void activeThumbColor(MemorySegment struct, int fieldValue) {
        struct.set(activeThumbColor$LAYOUT, activeThumbColor$OFFSET, fieldValue);
    }

    private static final OfInt activeTrackColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("activeTrackColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj activeTrackColor
     * }
     */
    public static final OfInt activeTrackColor$layout() {
        return activeTrackColor$LAYOUT;
    }

    private static final long activeTrackColor$OFFSET = $LAYOUT.byteOffset(groupElement("activeTrackColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj activeTrackColor
     * }
     */
    public static final long activeTrackColor$offset() {
        return activeTrackColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj activeTrackColor
     * }
     */
    public static int activeTrackColor(MemorySegment struct) {
        return struct.get(activeTrackColor$LAYOUT, activeTrackColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj activeTrackColor
     * }
     */
    public static void activeTrackColor(MemorySegment struct, int fieldValue) {
        struct.set(activeTrackColor$LAYOUT, activeTrackColor$OFFSET, fieldValue);
    }

    private static final OfInt inactiveThumbColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("inactiveThumbColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj inactiveThumbColor
     * }
     */
    public static final OfInt inactiveThumbColor$layout() {
        return inactiveThumbColor$LAYOUT;
    }

    private static final long inactiveThumbColor$OFFSET = $LAYOUT.byteOffset(groupElement("inactiveThumbColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj inactiveThumbColor
     * }
     */
    public static final long inactiveThumbColor$offset() {
        return inactiveThumbColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj inactiveThumbColor
     * }
     */
    public static int inactiveThumbColor(MemorySegment struct) {
        return struct.get(inactiveThumbColor$LAYOUT, inactiveThumbColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj inactiveThumbColor
     * }
     */
    public static void inactiveThumbColor(MemorySegment struct, int fieldValue) {
        struct.set(inactiveThumbColor$LAYOUT, inactiveThumbColor$OFFSET, fieldValue);
    }

    private static final OfInt inactiveTrackColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("inactiveTrackColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj inactiveTrackColor
     * }
     */
    public static final OfInt inactiveTrackColor$layout() {
        return inactiveTrackColor$LAYOUT;
    }

    private static final long inactiveTrackColor$OFFSET = $LAYOUT.byteOffset(groupElement("inactiveTrackColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj inactiveTrackColor
     * }
     */
    public static final long inactiveTrackColor$offset() {
        return inactiveTrackColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj inactiveTrackColor
     * }
     */
    public static int inactiveTrackColor(MemorySegment struct) {
        return struct.get(inactiveTrackColor$LAYOUT, inactiveTrackColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj inactiveTrackColor
     * }
     */
    public static void inactiveTrackColor(MemorySegment struct, int fieldValue) {
        struct.set(inactiveTrackColor$LAYOUT, inactiveTrackColor$OFFSET, fieldValue);
    }

    private static final OfInt materialTapTargetSize$LAYOUT = (OfInt)$LAYOUT.select(groupElement("materialTapTargetSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int materialTapTargetSize
     * }
     */
    public static final OfInt materialTapTargetSize$layout() {
        return materialTapTargetSize$LAYOUT;
    }

    private static final long materialTapTargetSize$OFFSET = $LAYOUT.byteOffset(groupElement("materialTapTargetSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int materialTapTargetSize
     * }
     */
    public static final long materialTapTargetSize$offset() {
        return materialTapTargetSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int materialTapTargetSize
     * }
     */
    public static int materialTapTargetSize(MemorySegment struct) {
        return struct.get(materialTapTargetSize$LAYOUT, materialTapTargetSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int materialTapTargetSize
     * }
     */
    public static void materialTapTargetSize(MemorySegment struct, int fieldValue) {
        struct.set(materialTapTargetSize$LAYOUT, materialTapTargetSize$OFFSET, fieldValue);
    }

    private static final OfInt applyCupertinoTheme$LAYOUT = (OfInt)$LAYOUT.select(groupElement("applyCupertinoTheme"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int applyCupertinoTheme
     * }
     */
    public static final OfInt applyCupertinoTheme$layout() {
        return applyCupertinoTheme$LAYOUT;
    }

    private static final long applyCupertinoTheme$OFFSET = $LAYOUT.byteOffset(groupElement("applyCupertinoTheme"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int applyCupertinoTheme
     * }
     */
    public static final long applyCupertinoTheme$offset() {
        return applyCupertinoTheme$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int applyCupertinoTheme
     * }
     */
    public static int applyCupertinoTheme(MemorySegment struct) {
        return struct.get(applyCupertinoTheme$LAYOUT, applyCupertinoTheme$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int applyCupertinoTheme
     * }
     */
    public static void applyCupertinoTheme(MemorySegment struct, int fieldValue) {
        struct.set(applyCupertinoTheme$LAYOUT, applyCupertinoTheme$OFFSET, fieldValue);
    }

    private static final OfInt dragStartBehavior$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dragStartBehavior"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int dragStartBehavior
     * }
     */
    public static final OfInt dragStartBehavior$layout() {
        return dragStartBehavior$LAYOUT;
    }

    private static final long dragStartBehavior$OFFSET = $LAYOUT.byteOffset(groupElement("dragStartBehavior"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int dragStartBehavior
     * }
     */
    public static final long dragStartBehavior$offset() {
        return dragStartBehavior$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int dragStartBehavior
     * }
     */
    public static int dragStartBehavior(MemorySegment struct) {
        return struct.get(dragStartBehavior$LAYOUT, dragStartBehavior$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int dragStartBehavior
     * }
     */
    public static void dragStartBehavior(MemorySegment struct, int fieldValue) {
        struct.set(dragStartBehavior$LAYOUT, dragStartBehavior$OFFSET, fieldValue);
    }

    private static final OfInt focusColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("focusColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj focusColor
     * }
     */
    public static final OfInt focusColor$layout() {
        return focusColor$LAYOUT;
    }

    private static final long focusColor$OFFSET = $LAYOUT.byteOffset(groupElement("focusColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj focusColor
     * }
     */
    public static final long focusColor$offset() {
        return focusColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj focusColor
     * }
     */
    public static int focusColor(MemorySegment struct) {
        return struct.get(focusColor$LAYOUT, focusColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj focusColor
     * }
     */
    public static void focusColor(MemorySegment struct, int fieldValue) {
        struct.set(focusColor$LAYOUT, focusColor$OFFSET, fieldValue);
    }

    private static final OfInt hoverColor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("hoverColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj hoverColor
     * }
     */
    public static final OfInt hoverColor$layout() {
        return hoverColor$LAYOUT;
    }

    private static final long hoverColor$OFFSET = $LAYOUT.byteOffset(groupElement("hoverColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj hoverColor
     * }
     */
    public static final long hoverColor$offset() {
        return hoverColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj hoverColor
     * }
     */
    public static int hoverColor(MemorySegment struct) {
        return struct.get(hoverColor$LAYOUT, hoverColor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj hoverColor
     * }
     */
    public static void hoverColor(MemorySegment struct, int fieldValue) {
        struct.set(hoverColor$LAYOUT, hoverColor$OFFSET, fieldValue);
    }

    private static final OfDouble splashRadius$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("splashRadius"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double splashRadius
     * }
     */
    public static final OfDouble splashRadius$layout() {
        return splashRadius$LAYOUT;
    }

    private static final long splashRadius$OFFSET = $LAYOUT.byteOffset(groupElement("splashRadius"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double splashRadius
     * }
     */
    public static final long splashRadius$offset() {
        return splashRadius$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double splashRadius
     * }
     */
    public static double splashRadius(MemorySegment struct) {
        return struct.get(splashRadius$LAYOUT, splashRadius$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double splashRadius
     * }
     */
    public static void splashRadius(MemorySegment struct, double fieldValue) {
        struct.set(splashRadius$LAYOUT, splashRadius$OFFSET, fieldValue);
    }

    private static final OfInt autofocus$LAYOUT = (OfInt)$LAYOUT.select(groupElement("autofocus"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int autofocus
     * }
     */
    public static final OfInt autofocus$layout() {
        return autofocus$LAYOUT;
    }

    private static final long autofocus$OFFSET = $LAYOUT.byteOffset(groupElement("autofocus"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int autofocus
     * }
     */
    public static final long autofocus$offset() {
        return autofocus$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int autofocus
     * }
     */
    public static int autofocus(MemorySegment struct) {
        return struct.get(autofocus$LAYOUT, autofocus$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int autofocus
     * }
     */
    public static void autofocus(MemorySegment struct, int fieldValue) {
        struct.set(autofocus$LAYOUT, autofocus$OFFSET, fieldValue);
    }

    private static final OfInt padding$LAYOUT = (OfInt)$LAYOUT.select(groupElement("padding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj padding
     * }
     */
    public static final OfInt padding$layout() {
        return padding$LAYOUT;
    }

    private static final long padding$OFFSET = $LAYOUT.byteOffset(groupElement("padding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj padding
     * }
     */
    public static final long padding$offset() {
        return padding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj padding
     * }
     */
    public static int padding(MemorySegment struct) {
        return struct.get(padding$LAYOUT, padding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj padding
     * }
     */
    public static void padding(MemorySegment struct, int fieldValue) {
        struct.set(padding$LAYOUT, padding$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

