// Generated by jextract

package dev.equo.ewt.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int id;
 *     char *text;
 *     DartObj child;
 *     DartObj icon;
 *     DartObj iconMargin;
 *     double height;
 * }
 * }
 */
public class TabObjSt {

    TabObjSt() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        StarterBridge.C_INT.withName("id"),
        MemoryLayout.paddingLayout(4),
        StarterBridge.C_POINTER.withName("text"),
        StarterBridge.C_INT.withName("child"),
        StarterBridge.C_INT.withName("icon"),
        StarterBridge.C_INT.withName("iconMargin"),
        MemoryLayout.paddingLayout(4),
        StarterBridge.C_DOUBLE.withName("height")
    ).withName("$anon$1248:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static final OfInt id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = $LAYOUT.byteOffset(groupElement("id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static int id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static void id(MemorySegment struct, int fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    private static final AddressLayout text$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("text"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *text
     * }
     */
    public static final AddressLayout text$layout() {
        return text$LAYOUT;
    }

    private static final long text$OFFSET = $LAYOUT.byteOffset(groupElement("text"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *text
     * }
     */
    public static final long text$offset() {
        return text$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *text
     * }
     */
    public static MemorySegment text(MemorySegment struct) {
        return struct.get(text$LAYOUT, text$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *text
     * }
     */
    public static void text(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(text$LAYOUT, text$OFFSET, fieldValue);
    }

    private static final OfInt child$LAYOUT = (OfInt)$LAYOUT.select(groupElement("child"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static final OfInt child$layout() {
        return child$LAYOUT;
    }

    private static final long child$OFFSET = $LAYOUT.byteOffset(groupElement("child"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static final long child$offset() {
        return child$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static int child(MemorySegment struct) {
        return struct.get(child$LAYOUT, child$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static void child(MemorySegment struct, int fieldValue) {
        struct.set(child$LAYOUT, child$OFFSET, fieldValue);
    }

    private static final OfInt icon$LAYOUT = (OfInt)$LAYOUT.select(groupElement("icon"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj icon
     * }
     */
    public static final OfInt icon$layout() {
        return icon$LAYOUT;
    }

    private static final long icon$OFFSET = $LAYOUT.byteOffset(groupElement("icon"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj icon
     * }
     */
    public static final long icon$offset() {
        return icon$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj icon
     * }
     */
    public static int icon(MemorySegment struct) {
        return struct.get(icon$LAYOUT, icon$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj icon
     * }
     */
    public static void icon(MemorySegment struct, int fieldValue) {
        struct.set(icon$LAYOUT, icon$OFFSET, fieldValue);
    }

    private static final OfInt iconMargin$LAYOUT = (OfInt)$LAYOUT.select(groupElement("iconMargin"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj iconMargin
     * }
     */
    public static final OfInt iconMargin$layout() {
        return iconMargin$LAYOUT;
    }

    private static final long iconMargin$OFFSET = $LAYOUT.byteOffset(groupElement("iconMargin"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj iconMargin
     * }
     */
    public static final long iconMargin$offset() {
        return iconMargin$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj iconMargin
     * }
     */
    public static int iconMargin(MemorySegment struct) {
        return struct.get(iconMargin$LAYOUT, iconMargin$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj iconMargin
     * }
     */
    public static void iconMargin(MemorySegment struct, int fieldValue) {
        struct.set(iconMargin$LAYOUT, iconMargin$OFFSET, fieldValue);
    }

    private static final OfDouble height$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("height"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double height
     * }
     */
    public static final OfDouble height$layout() {
        return height$LAYOUT;
    }

    private static final long height$OFFSET = $LAYOUT.byteOffset(groupElement("height"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double height
     * }
     */
    public static final long height$offset() {
        return height$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double height
     * }
     */
    public static double height(MemorySegment struct) {
        return struct.get(height$LAYOUT, height$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double height
     * }
     */
    public static void height(MemorySegment struct, double fieldValue) {
        struct.set(height$LAYOUT, height$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

