// Generated by jextract

package dev.equo.ewt.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int id;
 *     DartObj child;
 *     DartObj replacement;
 *     int visible;
 *     int maintainState;
 *     int maintainAnimation;
 *     int maintainSize;
 *     int maintainSemantics;
 *     int maintainInteractivity;
 *     int maintainFocusability;
 * }
 * }
 */
public class VisibilityObjSt {

    VisibilityObjSt() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        StarterBridge.C_INT.withName("id"),
        StarterBridge.C_INT.withName("child"),
        StarterBridge.C_INT.withName("replacement"),
        StarterBridge.C_INT.withName("visible"),
        StarterBridge.C_INT.withName("maintainState"),
        StarterBridge.C_INT.withName("maintainAnimation"),
        StarterBridge.C_INT.withName("maintainSize"),
        StarterBridge.C_INT.withName("maintainSemantics"),
        StarterBridge.C_INT.withName("maintainInteractivity"),
        StarterBridge.C_INT.withName("maintainFocusability")
    ).withName("$anon$433:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static final OfInt id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = $LAYOUT.byteOffset(groupElement("id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static int id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int id
     * }
     */
    public static void id(MemorySegment struct, int fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    private static final OfInt child$LAYOUT = (OfInt)$LAYOUT.select(groupElement("child"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static final OfInt child$layout() {
        return child$LAYOUT;
    }

    private static final long child$OFFSET = $LAYOUT.byteOffset(groupElement("child"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static final long child$offset() {
        return child$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static int child(MemorySegment struct) {
        return struct.get(child$LAYOUT, child$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj child
     * }
     */
    public static void child(MemorySegment struct, int fieldValue) {
        struct.set(child$LAYOUT, child$OFFSET, fieldValue);
    }

    private static final OfInt replacement$LAYOUT = (OfInt)$LAYOUT.select(groupElement("replacement"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DartObj replacement
     * }
     */
    public static final OfInt replacement$layout() {
        return replacement$LAYOUT;
    }

    private static final long replacement$OFFSET = $LAYOUT.byteOffset(groupElement("replacement"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DartObj replacement
     * }
     */
    public static final long replacement$offset() {
        return replacement$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DartObj replacement
     * }
     */
    public static int replacement(MemorySegment struct) {
        return struct.get(replacement$LAYOUT, replacement$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DartObj replacement
     * }
     */
    public static void replacement(MemorySegment struct, int fieldValue) {
        struct.set(replacement$LAYOUT, replacement$OFFSET, fieldValue);
    }

    private static final OfInt visible$LAYOUT = (OfInt)$LAYOUT.select(groupElement("visible"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int visible
     * }
     */
    public static final OfInt visible$layout() {
        return visible$LAYOUT;
    }

    private static final long visible$OFFSET = $LAYOUT.byteOffset(groupElement("visible"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int visible
     * }
     */
    public static final long visible$offset() {
        return visible$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int visible
     * }
     */
    public static int visible(MemorySegment struct) {
        return struct.get(visible$LAYOUT, visible$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int visible
     * }
     */
    public static void visible(MemorySegment struct, int fieldValue) {
        struct.set(visible$LAYOUT, visible$OFFSET, fieldValue);
    }

    private static final OfInt maintainState$LAYOUT = (OfInt)$LAYOUT.select(groupElement("maintainState"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int maintainState
     * }
     */
    public static final OfInt maintainState$layout() {
        return maintainState$LAYOUT;
    }

    private static final long maintainState$OFFSET = $LAYOUT.byteOffset(groupElement("maintainState"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int maintainState
     * }
     */
    public static final long maintainState$offset() {
        return maintainState$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int maintainState
     * }
     */
    public static int maintainState(MemorySegment struct) {
        return struct.get(maintainState$LAYOUT, maintainState$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int maintainState
     * }
     */
    public static void maintainState(MemorySegment struct, int fieldValue) {
        struct.set(maintainState$LAYOUT, maintainState$OFFSET, fieldValue);
    }

    private static final OfInt maintainAnimation$LAYOUT = (OfInt)$LAYOUT.select(groupElement("maintainAnimation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int maintainAnimation
     * }
     */
    public static final OfInt maintainAnimation$layout() {
        return maintainAnimation$LAYOUT;
    }

    private static final long maintainAnimation$OFFSET = $LAYOUT.byteOffset(groupElement("maintainAnimation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int maintainAnimation
     * }
     */
    public static final long maintainAnimation$offset() {
        return maintainAnimation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int maintainAnimation
     * }
     */
    public static int maintainAnimation(MemorySegment struct) {
        return struct.get(maintainAnimation$LAYOUT, maintainAnimation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int maintainAnimation
     * }
     */
    public static void maintainAnimation(MemorySegment struct, int fieldValue) {
        struct.set(maintainAnimation$LAYOUT, maintainAnimation$OFFSET, fieldValue);
    }

    private static final OfInt maintainSize$LAYOUT = (OfInt)$LAYOUT.select(groupElement("maintainSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int maintainSize
     * }
     */
    public static final OfInt maintainSize$layout() {
        return maintainSize$LAYOUT;
    }

    private static final long maintainSize$OFFSET = $LAYOUT.byteOffset(groupElement("maintainSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int maintainSize
     * }
     */
    public static final long maintainSize$offset() {
        return maintainSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int maintainSize
     * }
     */
    public static int maintainSize(MemorySegment struct) {
        return struct.get(maintainSize$LAYOUT, maintainSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int maintainSize
     * }
     */
    public static void maintainSize(MemorySegment struct, int fieldValue) {
        struct.set(maintainSize$LAYOUT, maintainSize$OFFSET, fieldValue);
    }

    private static final OfInt maintainSemantics$LAYOUT = (OfInt)$LAYOUT.select(groupElement("maintainSemantics"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int maintainSemantics
     * }
     */
    public static final OfInt maintainSemantics$layout() {
        return maintainSemantics$LAYOUT;
    }

    private static final long maintainSemantics$OFFSET = $LAYOUT.byteOffset(groupElement("maintainSemantics"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int maintainSemantics
     * }
     */
    public static final long maintainSemantics$offset() {
        return maintainSemantics$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int maintainSemantics
     * }
     */
    public static int maintainSemantics(MemorySegment struct) {
        return struct.get(maintainSemantics$LAYOUT, maintainSemantics$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int maintainSemantics
     * }
     */
    public static void maintainSemantics(MemorySegment struct, int fieldValue) {
        struct.set(maintainSemantics$LAYOUT, maintainSemantics$OFFSET, fieldValue);
    }

    private static final OfInt maintainInteractivity$LAYOUT = (OfInt)$LAYOUT.select(groupElement("maintainInteractivity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int maintainInteractivity
     * }
     */
    public static final OfInt maintainInteractivity$layout() {
        return maintainInteractivity$LAYOUT;
    }

    private static final long maintainInteractivity$OFFSET = $LAYOUT.byteOffset(groupElement("maintainInteractivity"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int maintainInteractivity
     * }
     */
    public static final long maintainInteractivity$offset() {
        return maintainInteractivity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int maintainInteractivity
     * }
     */
    public static int maintainInteractivity(MemorySegment struct) {
        return struct.get(maintainInteractivity$LAYOUT, maintainInteractivity$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int maintainInteractivity
     * }
     */
    public static void maintainInteractivity(MemorySegment struct, int fieldValue) {
        struct.set(maintainInteractivity$LAYOUT, maintainInteractivity$OFFSET, fieldValue);
    }

    private static final OfInt maintainFocusability$LAYOUT = (OfInt)$LAYOUT.select(groupElement("maintainFocusability"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int maintainFocusability
     * }
     */
    public static final OfInt maintainFocusability$layout() {
        return maintainFocusability$LAYOUT;
    }

    private static final long maintainFocusability$OFFSET = $LAYOUT.byteOffset(groupElement("maintainFocusability"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int maintainFocusability
     * }
     */
    public static final long maintainFocusability$offset() {
        return maintainFocusability$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int maintainFocusability
     * }
     */
    public static int maintainFocusability(MemorySegment struct) {
        return struct.get(maintainFocusability$LAYOUT, maintainFocusability$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int maintainFocusability
     * }
     */
    public static void maintainFocusability(MemorySegment struct, int fieldValue) {
        struct.set(maintainFocusability$LAYOUT, maintainFocusability$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

