typedef DartObj (*WidgetBuilderFFI)(DartObj context);
typedef int (*SelectableDayPredicateFFI)(DartObj day);
typedef DartObj (*TransitionBuilderFFI)(DartObj context, DartObj child);
typedef void (*ValueChangedForDatePickerEntryModeFFI)(int value);
typedef void (*EntryModeChangeCallbackFFI)(int mode);
typedef int (*SelectableDayForRangePredicateFFI)(DartObj day, DartObj selectedStartDay, DartObj selectedEndDay);
typedef void (*FutureThenCallbackForObjectOptFFI)(DartObj* value);
typedef void (*PointerEnterEventListenerFFI)(DartObj event);
typedef void (*PointerExitEventListenerFFI)(DartObj event);
typedef void (*PointerHoverEventListenerFFI)(DartObj event);
typedef void (*VoidCallbackFFI)(void);
typedef DartObj (*NullableIndexedWidgetBuilderFFI)(DartObj context, int index);
typedef DartObj (*IndexedWidgetBuilderFFI)(DartObj context, int index);
typedef void (*ValueChangedForIntFFI)(int value);
typedef void (*GestureScaleEndCallbackFFI)(DartObj details);
typedef void (*GestureScaleStartCallbackFFI)(DartObj details);
typedef void (*GestureScaleUpdateCallbackFFI)(DartObj details);
typedef DartObj (*DragAnchorStrategyFFI)(DartObj draggable, DartObj context, DartObj position);
typedef void (*DragUpdateCallbackFFI)(DartObj details);
typedef void (*DraggableCanceledCallbackFFI)(DartObj velocity, DartObj offset);
typedef void (*DragEndCallbackFFI)(DartObj details);
typedef int (*AllowedButtonsFilterFFI)(int buttons);
typedef DartObj (*DragTargetBuilderForTFFI)(DartObj context, ArrayC candidateData, ArrayC rejectedData);
typedef int (*DragTargetWillAcceptForTFFI)(DartObj data);
typedef int (*DragTargetWillAcceptWithDetailsForTFFI)(DartObj details);
typedef void (*DragTargetAcceptForTFFI)(DartObj data);
typedef void (*DragTargetAcceptWithDetailsForTFFI)(DartObj details);
typedef void (*DragTargetLeaveForTFFI)(DartObj data);
typedef void (*DragTargetMoveForTFFI)(DartObj details);
typedef DartObj (*HeroFlightShuttleBuilderFFI)(DartObj flightContext, DartObj animation, int flightDirection, DartObj fromHeroContext, DartObj toHeroContext);
typedef DartObj (*AnimatedSwitcherTransitionBuilderFFI)(DartObj child, DartObj animation);
typedef DartObj (*AnimatedSwitcherLayoutBuilderFFI)(DartObj currentChild, ArrayC previousChildren);
typedef void (*ValueChangedForBoolFFI)(int value);
typedef void (*PointerDownEventListenerFFI)(DartObj event);
typedef void (*PointerUpEventListenerFFI)(DartObj event);
typedef void (*TapRegionCallbackFFI)(DartObj event);
typedef void (*TapRegionUpCallbackFFI)(DartObj event);
typedef void (*DrawerCallbackFFI)(int isOpened);
typedef DartObj (*DartObjCallbackDartObjDartObjFFI)(DartObj , DartObj );
typedef char* (*GenerateAppTitleFFI)(DartObj context);
typedef void (*ValueChangedForStringFFI)(char* value);
typedef void (*GestureTapCallbackFFI)(void);
typedef DartObj (*InputCounterWidgetBuilderFFI)(DartObj context, int currentLength, int isFocused, int maxLength);
typedef void (*GestureTapDownCallbackFFI)(DartObj details);
typedef void (*GestureTapUpCallbackFFI)(DartObj details);
typedef void (*GestureTapMoveCallbackFFI)(DartObj details);
typedef void (*GestureTapCancelCallbackFFI)(void);
typedef void (*GestureLongPressDownCallbackFFI)(DartObj details);
typedef void (*GestureLongPressCancelCallbackFFI)(void);
typedef void (*GestureLongPressCallbackFFI)(void);
typedef void (*GestureLongPressStartCallbackFFI)(DartObj details);
typedef void (*GestureLongPressMoveUpdateCallbackFFI)(DartObj details);
typedef void (*GestureLongPressUpCallbackFFI)(void);
typedef void (*GestureLongPressEndCallbackFFI)(DartObj details);
typedef void (*GestureDragDownCallbackFFI)(DartObj details);
typedef void (*GestureDragStartCallbackFFI)(DartObj details);
typedef void (*GestureDragUpdateCallbackFFI)(DartObj details);
typedef void (*GestureDragEndCallbackFFI)(DartObj details);
typedef void (*GestureDragCancelCallbackFFI)(void);
typedef void (*GestureForcePressStartCallbackFFI)(DartObj details);
typedef void (*GestureForcePressPeakCallbackFFI)(DartObj details);
typedef void (*GestureForcePressUpdateCallbackFFI)(DartObj details);
typedef void (*GestureForcePressEndCallbackFFI)(DartObj details);
typedef void (*ValueChangedForBoolOptFFI)(int* value);
typedef void (*ValueChangedForDoubleFFI)(double value);
typedef char* (*SemanticFormatterCallbackFFI)(double value);
typedef void (*TooltipTriggeredCallbackFFI)(void);
typedef void (*TabValueChangedForBoolFFI)(int value, int index);
typedef void (*ValueSetterForBoolOptFFI)(int* value);
typedef void (*DataColumnSortCallbackFFI)(int columnIndex, int ascending);
typedef ArrayC (*DropdownButtonBuilderFFI)(DartObj context);
typedef void (*ValueChangedForTOptFFI)(DartObj* value);
typedef DartObj (*ExpansionPanelHeaderBuilderFFI)(DartObj context, int isExpanded);
typedef void (*ExpansionPanelCallbackFFI)(int panelIndex, int isExpanded);
typedef ArrayC (*PopupMenuItemBuilderForTFFI)(DartObj context);
typedef void (*PopupMenuItemSelectedForTFFI)(DartObj value);
typedef void (*PopupMenuCanceledFFI)(void);
typedef void (*ValueChangedForAnimationStatusFFI)(int value);
typedef void (*ValueChangedForDateTimeFFI)(DartObj value);
typedef void (*ValueChangedForDurationFFI)(DartObj value);
typedef DartObj (*SelectionOverlayBuilderFFI)(DartObj context, int columnCount, int selectedIndex);
typedef DartObj (*CupertinoContextMenuBuilderFFI)(DartObj context, DartObj animation);
typedef DartObj (*DartObjCallbackDartObjBoxConstraintsObjStFFI)(DartObj context, DartObj constraints);
typedef DartObj (*OrientationWidgetBuilderFFI)(DartObj context, int orientation);
typedef void (*PopInvokedCallbackFFI)(int didPop);
typedef void (*PopInvokedWithResultCallbackForObjectOptFFI)(int didPop, DartObj* result);
typedef DartObj (*WillPopCallbackFFI)(void);
typedef void (*StateSetterFFI)(VoidCallbackFFI fn);
typedef DartObj (*StatefulWidgetBuilderFFI)(DartObj context, StateSetterFFI setState);
typedef DartObj (*ImageFrameBuilderFFI)(DartObj context, DartObj child, int frame, int wasSynchronouslyLoaded);
typedef void (*BottomSheetDragStartHandlerFFI)(DartObj details);
typedef void (*BottomSheetDragEndHandlerFFI)(DartObj details, int isClosing);
typedef void (*MoveCursorHandlerFFI)(int extendSelection);
typedef void (*SetTextHandlerFFI)(char* text);
typedef DartObj (*AsyncCallbackFFI)(void);
typedef void (*PopResultCallbackForTFFI)(DartObj result);
typedef DartObj (*StepIconBuilderFFI)(int stepIndex, int stepState);
typedef DartObj (*RefreshCallbackFFI)(void);
typedef void (*ValueChangedForRefreshIndicatorStatusOptFFI)(int* value);
typedef DartObj (*ValueGetterForFutureFFI)(void);
typedef void (*FormFieldSetterForStringFFI)(char* newValue);
typedef char* (*FormFieldValidatorForStringFFI)(char* value);
typedef ArrayC (*NestedScrollViewHeaderSliversBuilderFFI)(DartObj context, int innerBoxIsScrolled);
typedef void (*VoidCallbackDartObjFFI)(DartObj );
typedef DartObj (*DartObjCallbackDartObjFFI)(DartObj );
typedef DartObj (*DartObjCallbackFFI)(void);
