typedef DartObj (*WidgetBuilderFFI)(DartObj context);
typedef DartObj (*TransitionBuilderFFI)(DartObj context, DartObj child);
typedef void (*VoidCallbackFFI)(void);
typedef void (*ValueChangedForBoolFFI)(int value);
typedef void (*DrawerCallbackFFI)(int isOpened);
typedef DartObj (*DartObjCallbackDartObjDartObjFFI)(DartObj , DartObj );
typedef char* (*GenerateAppTitleFFI)(DartObj context);
typedef void (*ValueChangedForStringFFI)(char* value);
typedef void (*GestureTapCallbackFFI)(void);
typedef DartObj (*InputCounterWidgetBuilderFFI)(DartObj context, int currentLength, int isFocused, int maxLength);
typedef void (*GestureTapCancelCallbackFFI)(void);
typedef void (*GestureLongPressCancelCallbackFFI)(void);
typedef void (*GestureLongPressCallbackFFI)(void);
typedef void (*GestureLongPressUpCallbackFFI)(void);
typedef void (*GestureDragCancelCallbackFFI)(void);
typedef void (*VoidCallbackDartObjFFI)(DartObj );
typedef DartObj (*DartObjCallbackDartObjFFI)(DartObj );
typedef DartObj (*DartObjCallbackFFI)(void);
typedef void (*VoidCallbackintFFI)(int ctrlId);
typedef DartObj (*WidgetCallbackFFI)(void);
