typedef DartObj (*WidgetBuilderFFI)(DartObj context);
typedef DartObj (*TransitionBuilderFFI)(DartObj context, DartObj child);
typedef void (*VoidCallbackFFI)(void);
typedef DartObj (*NullableIndexedWidgetBuilderFFI)(DartObj context, int index);
typedef DartObj (*IndexedWidgetBuilderFFI)(DartObj context, int index);
typedef void (*ValueChangedForIntFFI)(int value);
typedef void (*ValueChangedForBoolFFI)(int value);
typedef void (*DrawerCallbackFFI)(int isOpened);
typedef DartObj (*DartObjCallbackDartObjDartObjFFI)(DartObj , DartObj );
typedef char* (*GenerateAppTitleFFI)(DartObj context);
typedef void (*ValueChangedForStringFFI)(char* value);
typedef void (*GestureTapCallbackFFI)(void);
typedef DartObj (*InputCounterWidgetBuilderFFI)(DartObj context, int currentLength, int isFocused, int maxLength);
typedef void (*GestureTapCancelCallbackFFI)(void);
typedef void (*GestureLongPressCancelCallbackFFI)(void);
typedef void (*GestureLongPressCallbackFFI)(void);
typedef void (*GestureLongPressUpCallbackFFI)(void);
typedef void (*GestureDragCancelCallbackFFI)(void);
typedef void (*ValueChangedForBoolOptFFI)(int* value);
typedef void (*ValueChangedForDoubleFFI)(double value);
typedef char* (*SemanticFormatterCallbackFFI)(double value);
typedef void (*TooltipTriggeredCallbackFFI)(void);
typedef void (*TabValueChangedForBoolFFI)(int value, int index);
typedef void (*VoidCallbackDartObjFFI)(DartObj );
typedef DartObj (*DartObjCallbackDartObjFFI)(DartObj );
typedef DartObj (*DartObjCallbackFFI)(void);
